---
permalink: san-host/concept_transitioning_luns_with_mount_points_using_dmmp_devices_names.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, lun, mount, points, dmmp, device, name 
summary: 'DMMP 디바이스 이름을 사용하여 LUN을 마운트 지점으로 전환하기 전에 DMMP 디바이스 이름을 해당 파일 시스템 UUID 번호로 교체해야 합니다. 컷오버 단계를 준비하기 위해 특정 단계를 수행해야 하며 전환 후 호스트에서 DMMP 디바이스를 다시 마운트해야 합니다. Red Hat Enterprise Linux\(RHEL\) 5 및 RHEL 6에 대해서도 동일한 절차를 수행합니다.' 
---
= DMMP 디바이스 이름을 사용하여 마운트 지점으로 LUN 전환
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
DMMP 디바이스 이름을 사용하여 LUN을 마운트 지점으로 전환하기 전에 DMMP 디바이스 이름을 해당 파일 시스템 UUID 번호로 교체해야 합니다. 컷오버 단계를 준비하기 위해 특정 단계를 수행해야 하며 전환 후 호스트에서 DMMP 디바이스를 다시 마운트해야 합니다. RHEL(Red Hat Enterprise Linux) 5 및 RHEL 6에 대해서도 동일한 절차를 수행합니다.

* 관련 정보 *

xref:task_preparing_rhel_luns_transition_using_inventory_assessment_workbook.adoc[Inventory Assessment 워크북을 사용하여 DMMP 디바이스 이름을 사용하여 마운트 지점으로 RHEL LUN 준비]

xref:task_preparing_rhel_luns_for_transition_using_the_cli.adoc[CLI를 사용하여 전환하기 위해 DMMP 별칭 이름을 사용하여 마운트 지점으로 RHEL LUN 준비]

xref:task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.adoc[Linux 호스트에서 DMMP 디바이스 이름을 사용하여 마운트 지점으로 LUN을 전환할 때 컷오버 단계를 준비합니다]

xref:task_remounting_dmmp_devices_on_linux_hosts_after_transition.adoc[전환 후 Linux 호스트에서 DMMP 디바이스를 다시 마운트합니다]
