---
permalink: san-host/task_testing_dmmp_devices_with_file_systems_on_rhel_hosts_before_cutover_phase.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, dmmp, devices, rhel, hosts, cutover, phase 
summary: '7-Mode 전환 툴(7MTT\) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 RHEL\(Red Hat Enterprise Linux\) 호스트의 복사 기반 전환을 수행하는 경우, 전환된 clustered Data ONTAP LUN을 테스트하여 전환 단계 전에 DMMP 디바이스를 마운트할 수 있는지 확인할 수 있습니다. 테스트 중에 소스 호스트에서 소스 7-Mode LUN에 대한 I/O를 계속 실행할 수 있습니다.' 
---
= 복사 기반 전환의 전환 단계 전에 RHEL 호스트에서 파일 시스템으로 DMMP 디바이스를 테스트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7MTT(7-Mode 전환 툴) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 RHEL(Red Hat Enterprise Linux) 호스트의 복사 기반 전환을 수행하는 경우, 전환된 clustered Data ONTAP LUN을 테스트하여 전환 단계 전에 DMMP 디바이스를 마운트할 수 있는지 확인할 수 있습니다. 테스트 중에 소스 호스트에서 소스 7-Mode LUN에 대한 I/O를 계속 실행할 수 있습니다.

새로운 clustered Data ONTAP LUN을 테스트 호스트에 매핑해야 하며 LUN을 전환할 준비가 되어 있어야 합니다.

테스트 호스트와 소스 호스트 간에 하드웨어 패리티를 유지해야 합니다.

테스트 호스트에서 다음 단계를 수행합니다.

. 기본 데이터 복사가 완료되면 7MTT 사용자 인터페이스(UI)에서 * 테스트 모드 * 를 선택합니다.
. 7MTT UI에서 * 구성 적용 * 을 클릭합니다.
. Clustered Data ONTAP LUN에 대한 새 SCSI 디바이스 이름을 가져옵니다.
+
``sanlun lun show *’

+
다음 예에서는 '/dev/sdl'이 'lun_dmmp_raw' LUN의 SCSI 디바이스 이름이고, '/dev/sdk'는 'lun_dmmp_raw_alias' LUN의 SCSI 디바이스 이름입니다.

+
[listing]
----
[root@ibmx3550-229-108 /]# sanlun lun show
controller(7mode/E-Series)/
vserver (cDOT/FlashRay) lun-pathname               filename
-----------------------------------------------------------
vs_brb  /vol/dmmp_raw_vol/lun_dmmp_raw              /dev/sdl
vs_brb  /vol/dmmp_raw_alias_vol/lun_dmmp_raw_alias  /dev/sdk
----
. Clustered Data ONTAP LUN에 대해 DMMP 디바이스를 구성합니다.
+
' * multipath * '

. Clustered Data ONTAP LUN의 디바이스 핸들 ID를 확인합니다.
+
'* multipath-ll*'

+
장치 핸들 ID의 예는 다음과 같습니다. "'3600a09804d532d79565d47617679764d'"

. DMMP 장치에 구성된 파일 시스템을 확인합니다.
+
``blkid|grep-i_device_handle_ID_ *'

. 소스 호스트의 '/etc/fstab' 파일에 논리적 볼륨의 마운트 지점 항목이 있는지 확인합니다.
. 소스 호스트의 논리 볼륨에 대한 마운트 지점 항목이 있는 경우 테스트 호스트에서 '/etc/fstab' 파일을 수동으로 편집하여 마운트 지점 항목을 추가합니다.
. LUN을 마운트합니다.
+
' * mount-a *'

. DMMP 장치가 마운트되었는지 확인합니다.
+
' * 마운트 * '

. 필요에 따라 테스트를 수행합니다.
. 테스트를 완료한 후 테스트 호스트를 종료합니다.
+
' * shutdown -h -t0 now * '

. 7MTT UI에서 * 테스트 완료 * 를 클릭합니다.


Clustered Data ONTAP LUN을 소스 호스트에 다시 매핑하려면 소스 호스트에서 컷오버 단계를 준비해야 합니다. Clustered Data ONTAP LUN을 테스트 호스트에 매핑된 상태로 유지하려면 테스트 호스트에 추가 단계가 필요하지 않습니다.

* 관련 정보 *

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[재고 평가 워크북에서 전이가 완료된 정보를 수집합니다]

xref:task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.adoc[Linux 호스트에서 DMMP 디바이스 이름을 사용하여 마운트 지점으로 LUN을 전환할 때 컷오버 단계를 준비합니다]
