---
permalink: san-host/task_preparing_for_post_transition_esxi_host_remediation.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, post, esxi, host, remediation 
summary: '7MTT(7-Mode 전환 툴)\)가 완료된 후 다양한 ESXi 호스트 수정 작업을 수행해야 합니다. 이러한 작업을 수행하기 전에 몇 가지 단계를 완료해야 합니다.' 
---
= 전환 후 ESXi 호스트 문제 해결 준비
:icons: font
:imagesdir: ../media/


[role="lead"]
7MTT(7-Mode 전환 툴) 전환이 완료된 후 다양한 ESXi 호스트 개선 작업을 수행해야 합니다. 이러한 작업을 수행하기 전에 몇 가지 단계를 완료해야 합니다.

* CTBT(Copy-Based 전이)의 경우 7MTT에서 스토리지 컷오버 작업을 시작하기 전에 다음 단계를 수행하십시오.
* CFT(Copy-Free 전이)의 경우, 7MTT에서 내보내기 및 중지 7-Mode 시스템 작업을 시작하기 전에 다음 단계를 수행하십시오.


.단계
. 7-Mode에서 ONTAP로 LUN 매핑 파일을 생성합니다.
+
** CBTs의 경우, 7MTT가 설치된 Linux 호스트에서 다음 명령을 실행합니다. + " * transition CBT export lunmap-p_project-name_-o_file_path_ *"
+
예를 들면 다음과 같습니다.

+
'* 전이 CBT 내보내기 lunmap-p SanWorkLoad-o c:/Libraires/Documents/7-to-C-LUN-mapping.csv *

** CFT의 경우, 7MTT가 설치된 시스템에서 + ` * transition CFT export lunmap -p_project -name_-s_svm -name_-o_output -file_ * ' 명령을 실행합니다
+
예를 들면 다음과 같습니다.

+
' * transition CFT export lunmap -p SanWorkLoad -s svm1-o c:/Libraires/Documents/7-to-C-LUN-mapping-svm1.csv *

+

NOTE: 각 SVM(스토리지 가상 머신)에 대해 이 명령을 실행해야 합니다.



. igroup 및 이니시에이터 매핑이 있는지 확인합니다.
+
7MTT는 7-Mode에서 작동하는 Data ONTAP에서 사용되는 이니시에이터를 통해 동일한 igroup을 다시 생성하고, clustered Data ONTAP LUN을 호스트에 다시 매핑합니다.

. 새로운 clustered Data ONTAP 타겟에 대해 조닝이 적절한지 확인합니다.
. CFT(Copy-Free Transition)를 수행하는 경우 'vol rehost'를 실행합니다.
+
를 참조하십시오 link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html["7-Mode 전환 툴 Copy-Free Transition Guide를 참조하십시오"] '볼륨 리호스트' 절차를 참조하십시오.


