---
permalink: san-host/task_bringing_windows_hosts_online_after_transition.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, windows, host, online 
summary: 'Windows 호스트용 7MTT(7-Mode Transition Tool)를 사용하여 LUN을 전환한 후 호스트를 온라인으로 전환하여 데이터 서비스를 다시 시작하려면 몇 가지 단계를 완료해야 합니다.' 
---
= 전환 후 Windows 호스트를 온라인으로 전환합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 호스트용 7MTT(7-Mode Transition Tool)를 사용하여 LUN을 전환한 후 호스트를 온라인으로 전환하여 데이터 서비스를 다시 시작하려면 몇 가지 단계를 완료해야 합니다.

CFT(Copy-Free Transition)를 수행하는 경우 'vol rehost' 절차를 완료해야 합니다. 를 참조하십시오 link:https://docs.netapp.com/us-en/ontap-7mode-transition/copy-free/index.html["7-Mode 전환 툴 Copy-Free Transition Guide를 참조하십시오"] 를 참조하십시오.

* CTBT(Copy-Based Transition)의 경우 7MTT(7-Mode Transition Tool)에서 스토리지 컷오버 작업을 완료한 후 다음 단계를 수행합니다.
* CFT의 경우, 7MTT에서 가져오기 및 데이터 구성 작업을 완료한 후 다음 단계를 수행합니다.
+
.. 7-Mode에서 ONTAP로 LUN 매핑 파일을 생성합니다.
+
*** 복사 기반 전환의 경우 7MTT가 설치된 호스트에서 + " * transition CBT export lunMAP -p_project -name_-o_file_path_ * " 명령을 실행합니다
+
예를 들면 다음과 같습니다.

+
'* 전이 CBT 내보내기 lunmap-p SanWorkLoad-o c:/Libraires/Documents/7-to-C-LUN-mapping.csv *

*** 복사를 사용하지 않는 전환을 사용하려면 7MTT가 설치된 시스템에서 + ` * transition CFT export lunmap -p_project -name_-s_svm -name_-o_output -file_ * ' 명령을 실행합니다
+

NOTE: 각 SVM(스토리지 가상 머신)에 대해 이 명령을 실행해야 합니다.

+
예를 들면 다음과 같습니다.

+
' * transition CFT export lunmap -p SANWorkLoad -s svml -o c:/libraries/Documents/7-to-C-LUN-mapping-svml.csv *



.. Windows 호스트가 SAN 부팅되고 부팅 LUN이 전환된 경우 호스트의 전원을 켭니다.
.. FC BIOS를 업데이트하여 시스템이 clustered Data ONTAP 컨트롤러의 LUN에서 부팅하도록 활성화합니다.
+
자세한 내용은 HBA 설명서를 참조하십시오.

.. Windows 호스트에서 디스크 관리자에서 디스크를 다시 검색합니다.
.. 호스트에 매핑된 LUN의 LUN 일련 번호, LUN ID 및 해당 Windows 물리적 디스크 번호를 확인합니다.
+
*** Data ONTAP ONTAPDSM을 실행하는 시스템의 경우: Data ONTAPDSM 관리 확장 스냅인 또는 get-sandisk Windows PowerShell cmdlet을 사용합니다.
*** MSDSM을 실행하는 시스템의 경우 ICT(Inventory Collect Tool)를 사용합니다.
+
LUN ID, LUN 일련 번호 및 해당 일련 번호는 SAN Host LUNs 탭 아래에 표시됩니다.



.. LUN 일련 번호, LUN ID 및 해당하는 Windows 물리적 디스크 번호를 LUN 맵 출력 및 사전 전환 상태에서 수집된 데이터와 함께 사용하여 LUN이 성공적으로 전환되었는지 여부를 확인하십시오.
.. 전환된 LUN의 물리적 디스크 수가 변경되었는지 확인합니다.
.. 디스크를 온라인 상태로 전환합니다.
+
*** Windows 디스크 관리자를 사용하여 클러스터 장애 조치에 속하지 않은 온라인 디스크를 가져옵니다.
*** Failover Cluster Manager를 사용하여 Cluster Failover의 일부인 온라인 디스크를 가져옵니다.


.. 전환 중인 호스트가 Windows Server 2003을 실행 중이고 쿼럼 장치를 마이그레이션한 경우 모든 클러스터 노드에서 클러스터 서비스를 시작합니다.
.. 호스트에서 Hyper-V가 활성화되어 있고 패스스루 디바이스가 VM에 구성되어 있는 경우 Hyper-V Manager에서 설정을 수정합니다.
+
전환 결과로 패스스루 디바이스에 해당하는 LUN의 물리적 디스크 번호가 변경될 수 있습니다.





* 관련 정보 *

xref:concept_what_the_inventory_collect_tool_is.adoc[재고 수집 도구의 정의]
