---
permalink: san-host/task_testing_data_luns_on_solaris_hosts_with_zfs_file_system_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, data, lun, solaris, zfs, cutover, copy, based 
summary: '7MTT\(7-Mode 전환 툴) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 Solaris 호스트 ZFS 데이터 LUN을 전환하는 경우 전환된 clustered Data ONTAP LUN을 테스트하여 MPIO 디바이스를 컷오버 단계 전에 마운트할 수 있는지 확인할 수 있습니다.' 
---
= 복사 기반 전환의 컷오버 단계 전에 ZFS 파일 시스템을 사용하는 Solaris 호스트에서 데이터 LUN 테스트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7MTT(7-Mode 전환 툴) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 Solaris 호스트 ZFS 데이터 LUN을 전환하는 경우 전환된 clustered Data ONTAP LUN을 테스트하여 MPIO 디바이스를 컷오버 단계 전에 마운트할 수 있는지 확인할 수 있습니다.

* 테스트 단계 전환을 시작하기 전에 ZFS 데이터 LUN이 있는 소스 호스트를 오프라인으로 전환해야 합니다.
+
참조: Oracle Doc ID 1316472.1: ZFS zpool은 온라인_이지만 LUN 복사본은 지원되지 않습니다. 자세한 내용은

* 새로운 clustered Data ONTAP LUN을 테스트 호스트에 매핑해야 하며 LUN을 전환할 준비가 되어 있어야 합니다.
* 운영 호스트에서 zpool을 내보내면 애플리케이션이 중단되고 7-Mode LUN 전에 모든 I/O 작업이 중지되어야 합니다.


테스트 호스트와 소스 호스트 간에 하드웨어 패리티를 유지해야 하며 테스트 호스트에서 다음 단계를 수행해야 합니다.

Clustered Data ONTAP LUN은 테스트 중에 읽기/쓰기 모드로 전환됩니다. 테스트가 완료되고 컷오버 단계에 대비하는 동안 읽기 전용 모드로 전환됩니다.

. 운영(소스) 호스트에서 zpool을 내보냅니다.
+
'*#zpool export_pool-name_ *'

+
[listing]
----
# zpool export n_pool

# zpool import
  pool: n_pool
    id: 5049703405981005579
 state: ONLINE
action: The pool can be imported using its name or numeric identifier.
config:

        n_pool                                   ONLINE
          c0t60A98000383035356C2447384D396550d0  ONLINE
          c0t60A98000383035356C2447384D39654Ed0  ONLINE
----
. 기본 데이터 복사가 완료되면 7MTT 사용자 인터페이스(UI)에서 * 테스트 모드 * 를 선택합니다.
. 7MTT UI에서 * 구성 적용 * 을 클릭합니다.
+

NOTE: 이 단계를 완료한 후 애플리케이션을 다시 온라인 상태로 설정하고 I/O 작업을 7-Mode LUN으로 시작할 수 있습니다. 후속 단계로 인해 응용 프로그램이 중단되지는 않습니다.

. 운영 호스트에서 zpool을 가져옵니다.
+
'*#zpool import_pool-name_ *'

+
[listing]
----
# zpool import n_pool
----
. 테스트 호스트에서 새 clustered Data ONTAP LUN을 다시 검색합니다.
+
.. FC 호스트 포트(유형 fc-fabric):+' *#cfgadm –l *'를 식별합니다
.. 첫 번째 fc-fabric 포트: + " *#cfgadm –c unconfigure C1 * "의 구성을 해제합니다
.. 첫 번째 fc-fabric 포트: + " *#cfgadm –c unconfigure C2 * "를 구성합니다
.. 다른 FC-패브릭 포트에 대해서도 이 단계를 반복합니다.
.. 호스트 포트 및 연결된 장치에 대한 정보 표시: + "*#cfgadm –al *"
.. '*#devfsadm-CV *' 드라이버를 다시 로드합니다
+
'*#devfsadm-i iscsi *'



. Clustered Data ONTAP LUN이 있는지 확인합니다.
+
'*#sanlun lun show *'

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
vs_5           /vol/zfs/zfs2    /dev/rdsk/c5t600A0980383030444D2B466542485935d0s2 scsi_vhci0 FCP        6g      C
vs_5           /vol/zfs/zfs1    /dev/rdsk/c5t600A0980383030444D2B466542485934d0s2 scsi_vhci0 FCP        6g      C
vs_5           /vol/ufs/ufs2    /dev/rdsk/c5t600A0980383030444D2B466542485937d0s2 scsi_vhci0 FCP        5g      C
vs_5           /vol/ufs/ufs1    /dev/rdsk/c5t600A0980383030444D2B466542485936d0s2 scsi_vhci0 FCP        5g      C
----
. 테스트할 zpool이 가져오기 위해 사용 가능한지 확인합니다.
+
'*#zpool import *'

+
[listing]
----
# zpool import
  pool: n_pool
    id: 5049703405981005579
 state: ONLINE
action: The pool can be imported using its name or numeric identifier.
config:

        n_pool                                   ONLINE
          c5t600A0980383030444D2B466542485935d0  ONLINE
          c5t600A0980383030444D2B466542485934d0  ONLINE
----
. 풀 이름 또는 풀 ID를 사용하여 zpool을 가져옵니다.
+
** '*#zpool 임포트 풀-이름 *'
** `#zpool import pool-id * '


+
[listing]
----
#zpool import n_pool
----
+
를 누릅니다

+
[listing]
----
#zpool import 5049703405981005579
----
. ZFS 데이터 세트가 마운트되었는지 확인합니다.
+
** ' * ZFS list * '
** "* df-ah*"


+
[listing]
----
# zfs list
NAME           USED  AVAIL  REFER  MOUNTPOINT
n_pool        2.67G  9.08G   160K  /n_pool
n_pool/pool1  1.50G  2.50G  1.50G  /n_pool/pool1
n_pool/pool2  1.16G  2.84G  1.16G  /n_pool/pool2
----
. 필요에 따라 테스트를 수행합니다.
. 테스트 호스트를 종료합니다.
. 7MTT UI에서 * 테스트 완료 * 를 클릭합니다.


Clustered Data ONTAP LUN을 소스 호스트에 다시 매핑하려면 소스 호스트에서 컷오버 단계를 준비해야 합니다. Clustered Data ONTAP LUN을 테스트 호스트에 매핑된 상태로 유지하려면 테스트 호스트에 추가 단계가 필요하지 않습니다.
