---
permalink: san-host/task_reattaching_rdm_luns_to_vms.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, rdm, lun, vm 
summary: 'RDM(Raw Device Mapped) LUN에 연결된 VM이 전환 후 작동하려면 VM에서 LUN을 호스팅하는 RDM 디스크를 제거해야 합니다. 그런 다음 7MTT\(7-Mode 전환 툴)에서 제공하는 LUN 일련 번호를 기반으로 RDM 디스크를 VM에 다시 연결해야 합니다.' 
---
= RDM LUN을 VM에 다시 연결합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
RDM(Raw Device Mapped) LUN에 연결된 VM이 전환 후 작동하려면 VM에서 LUN을 호스팅하는 RDM 디스크를 제거해야 합니다. 그런 다음 7MTT(7-Mode 전환 툴)에서 제공하는 LUN 일련 번호를 기반으로 RDM 디스크를 VM에 다시 연결해야 합니다.

* 복사본 기반 전환의 경우 7MTT에서 스토리지 컷오버 작업을 시작하기 전에 다음 단계를 수행하십시오.
* 복사를 수행하지 않는 전환의 경우, 7MTT에서 내보내기 및 중지 7-Mode 시스템 작업을 시작하기 전에 다음 단계를 수행하십시오.


.단계
. Inventory Assessment 워크북 _ 에서 * 호스트 VM 디스크 세부 정보 * 탭으로 이동합니다.
. Type * 열에서 PTRDM 또는 NPTRDM이 있는 ESXi 호스트 VM을 식별합니다.
. VM 이름, * Disk * 열의 디스크 경로 세부 정보 및 * Device Mapped * 열의 naa ID를 확인합니다.
. 전환 후 생성된 7MTT 매핑 파일에 naa ID가 나열되어 있는지 확인합니다.
. naa ID가 매핑 파일의 * LUN WWID * 열에 해당 새 naa ID가 있는지 확인합니다.
+
새로운 clustered Data ONTAP LUN naa ID입니다.

. LUN WWID * 열의 clustered Data ONTAP LUN naa ID와 디스크 경로 세부 정보를 사용하여 Clustered Data ONTAP LUN을 VM에 다시 연결합니다.


* 관련 정보 *

xref:task_removing_stale_rdm_using_vsphere_client.adoc[vSphere Client를 사용하여 오래된 RDM을 제거합니다]

xref:task_reattaching_rdm_to_vms_using_vsphere_client.adoc[vSphere Client를 사용하여 RDM을 VM에 다시 연결합니다]

xref:task_reattaching_rdm_using_esxi_cli_console.adoc[ESXi CLI/콘솔을 사용하여 RDM 다시 연결]
