---
permalink: san-host/task_enabling_caw_on_a_datastore_using_esxi_cli.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, enable, caw, datastore, esxi, cli 
summary: '7-Mode에서 작동하는 Data ONTAP에서 비교 및 쓰기\(caw\)를 지원하지 않은 경우 clustered Data ONTAP으로 전환할 때 수동으로 caw 지원을 활성화해야 합니다. Clustered Data ONTAP은 기본적으로 caw를 지원합니다.' 
---
= ESXi CLI를 사용하여 데이터 저장소에서 caw를 사용하도록 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode에서 작동하는 Data ONTAP에서 비교 및 쓰기(caw)를 지원하지 않은 경우 clustered Data ONTAP으로 전환할 때 수동으로 caw 지원을 활성화해야 합니다. Clustered Data ONTAP은 기본적으로 caw를 지원합니다.

* VMFS 데이터 저장소에서 실행 중인 입출력 또는 VM이 없어야 합니다.
* 데이터 저장소가 마이그레이션된 경우 다시 마운트해야 합니다.
* 7MTT(7-Mode 전환 툴) 매핑 파일에서 새로운 ONTAP LUN naa ID를 가지고 있어야 합니다.


VMFS 데이터 저장소에서 활성 실행 중인 입출력 또는 VM이 없는 경우에만 caw를 설정해야 합니다.

* VMFS 데이터 저장소에서 활성 실행 중인 입출력 또는 VM이 없는 경우에만 caw를 설정해야 합니다.
* 복사본 기반 전환의 경우 7MTT에서 스토리지 컷오버 작업을 완료한 후 다음 단계를 수행하십시오.
* 7MTT에서 데이터 및 구성 가져오기 작업이 완료된 후 복사를 수행하지 않는 전환을 수행하려면 다음 단계를 수행하십시오.


.단계
. ICT(Inventory Collect Tool)에서 생성한 _Inventory Assessment Workbook_을 엽니다.
. SAN Host Filesystems 탭으로 이동합니다.
. 데이터 저장소의 caw 상태를 확인합니다.
+
데이터 저장소에 대한 * ATS/caw * 값이 * Disabled * 로 표시되고 파일 시스템 열에 * VMFS.x * 가 표시되어야 합니다.

. Disk 열에 데이터 저장소의 이름을 기록합니다
. SSH를 사용하여 ESXi 콘솔에 로그인합니다.
. 장치 및 파티션 세부 정보를 나열합니다.
+
`~#vmkfstools-pH-v1_datastore_path_ *'

+
datastore_path는 _Inventory Assessment Workbook_의 Disk 열에 있는 데이터 저장소 이름입니다.

+
'*#vmkfstools-pH-v1/VMFS/볼륨/datastoreName*'

+
[listing]
----
VMFS-5.60 file system spanning 1 partitions.
File system label (if any): datastorename
Mode: public
Capacity 9.8 GB, 8.2 GB available, file block size 1 MB, max file size 64
TB
Volume Creation Time: Mon Dec 9 10:29:18 2013
Files (max/free): 27408/27394
Ptr Blocks (max/free): 64512/64495
Sub Blocks (max/free): 3968/3964
Secondary Ptr Blocks (max/free): 256/256
File Blocks (overcommit/used/overcommit %): 0/1593/0
Ptr Blocks (overcommit/used/overcommit %): 0/17/0
Sub Blocks (overcommit/used/overcommit %): 0/4/0
Volume Metadata size: 590675968
UUID: 52a59b7e-52d2fb6c-11d6-001ec9d631cb
Partitions spanned (on "lvm"):
naa.600a098044314c6c442b446d51376749:1
naa.600a098054314c6c445d446f79716431:1
naa.600a098054314c6c445d446f79716433:1
Is Native Snapshot Capable: YES
----
. 첫 번째 장치 이름과 파티션 번호를 확인합니다.
+
앞의 예에서, 'naa.600a098044314c6c442b446d51376749:1'은 장치 이름과 파티션 번호입니다.

. 디바이스 ID와 파티션 번호를 사용하여 데이터 저장소에서 caw를 설정합니다.
+
'*~#vmkfstools--configATOnly 1/VMFS/devices/disks/__device-ID:Partition__*'

. VMFS 볼륨이 ATS 전용으로 구성되었는지 확인합니다.
+
'*#vmkfstools-pH-v1/VMFS/볼륨/VMFS-volume-name *'

+
[listing]
----
VMFS-5.54 file system spanning 1 partitions.
File system label (if any): ats-test-1
Mode: public ATS-only
----


* 관련 정보 *

xref:task_remounting_vmfs_volumes_after_transition_using_vsphere_client.adoc[vSphere Client를 사용하여 전환 후 VMFS 볼륨을 다시 마운트합니다]

xref:task_remounting_vmfs_volumes_after_transition_using_esxi_cli_console.adoc[ESXi CLI를 사용하여 전환 후 VMFS 볼륨을 다시 마운트합니다]

https://pubs.vmware.com/vsphere-55/index.jsp?topic=/com.vmware.vsphere.storage.doc/GUID-6887003D-2322-49AC-A56C-7AFE7350DB5D.html["VMware 설명서"]
