---
permalink: san-host/task_preparing_to_transition_solaris_host_data_luns_with_sun_volume_manager.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, transition, solaris, host, lun, sun, volume, manager 
summary: Sun Volume Manager를 사용하는 Solaris 호스트 데이터 LUN을 7-Mode에서 작동하는 ONTAP에서 clustered ONTAP으로 전환하기 전에 전환 프로세스에 필요한 정보를 수집해야 합니다. 
---
= Sun Volume Manager를 사용하여 Solaris 호스트 LUN 전환 준비
:icons: font
:imagesdir: ../media/


[role="lead"]
Sun Volume Manager를 사용하는 Solaris 호스트 데이터 LUN을 7-Mode에서 작동하는 ONTAP에서 clustered ONTAP으로 전환하기 전에 전환 프로세스에 필요한 정보를 수집해야 합니다.

이 작업은 복사 기반 전환 및 무복사 전환에 적용됩니다.

.단계
. LUN을 표시하여 전환할 LUN의 이름을 식별합니다.
+
' * lun show * '

+
[listing]
----
 fas8040-shu01> lun show
        /vol/ufs/ufs1                  5g (5368709120)    (r/w, online, mapped)
        /vol/ufs/ufs2                  5g (5368709120)    (r/w, online, mapped)
        /vol/zfs/zfs1                  6g (6442450944)    (r/w, online, mapped)
        /vol/zfs/zfs2                  6g (6442450944)    (r/w, online, mapped)
----
. 호스트에서 LUN의 디바이스 파일 이름을 찾습니다.
+
'*#sanlun lun show *'

+
디바이스 파일 이름이 디바이스 파일 이름 열에 나열됩니다.

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
fas8040-shu01        /vol/zfs/zfs2    /dev/rdsk/c0t60A98000383035356C2447384D396550d0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/zfs/zfs1    /dev/rdsk/c0t60A98000383035356C2447384D39654Ed0s2 scsi_vhci0 FCP        6g      7
fas8040-shu01        /vol/ufs/ufs2    /dev/rdsk/c0t60A98000383035356C2447384D39654Ad0s2 scsi_vhci0 FCP        5g      7
fas8040-shu01        /vol/ufs/ufs1    /dev/rdsk/c0t60A98000383035356C2447384D396548d0s2 scsi_vhci0 FCP        5g
----
. SVM을 나열하고 기록한 다음 SVM과 관련된 디스크를 확보하십시오.
+
``메타셋 *’

+
'* metaset-s_set-name_ *'

+
[listing]
----
# metaset
Set name = svm, Set number = 1
Host                Owner
  Solarisx2-shu04        Yes
Drive                                            Dbase
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes
----
+
[listing]
----
# metastat -s svm
svm/d2: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D396548d0s0          0     No      Yes

svm/d1: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D39654Ad0s0          0     No      Yes

Device Relocation Information:
Device                                           Reloc  Device ID
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes    id1,sd@n60a98000383035356c2447384d396548
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes    id1,sd@n60a98000383035356c2447384d39654a
----
. 마운트 지점을 나열하고 기록합니다.
+
" * df – ah * "

+
[listing]
----
# df -ah
Filesystem             size   used  avail capacity  Mounted on
/dev/md/svm/dsk/d1     4.9G   1.5G   3.4G    31%    /d1
/dev/md/svm/dsk/d2     4.9G   991M   3.9G    20%    /d2
----

