---
permalink: san-host/task_testing_san_boot_luns_on_rhel_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, boot, lun, rhel, cutover, copy, based 
summary: '7-Mode 전환 툴(7MTT\) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 Red Hat Enterprise Linux\(RHEL\) 호스트의 복사 기반 전환을 수행하는 경우 전환 단계 전에 전환된 ONTAP SAN 부팅 LUN을 테스트할 수 있습니다. 테스트 중에 소스 호스트에서 소스 7-Mode LUN에 대한 I/O를 계속 실행할 수 있습니다.' 
---
= 복사 기반 전환의 컷오버 단계 전에 RHEL 호스트에서 SAN 부팅 LUN 테스트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7MTT(7-Mode 전환 툴) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 RHEL(Red Hat Enterprise Linux) 호스트의 복사 기반 전환을 수행하는 경우 전환 단계 전에 전환된 ONTAP SAN 부팅 LUN을 테스트할 수 있습니다. 테스트 중에 소스 호스트에서 소스 7-Mode LUN에 대한 I/O를 계속 실행할 수 있습니다.

새 ONTAP LUN을 테스트 호스트에 매핑해야 하며 LUN을 전환할 준비가 되어 있어야 합니다.

테스트 호스트와 소스 호스트 간에 하드웨어 패리티를 유지해야 합니다.

* 복사본 기반 전환의 경우 7-Mode 전환 도구에서 스토리지 컷오버 작업을 완료한 후 다음 단계를 수행해야 합니다.
* 무복사 전이의 경우 7-Mode 전환 도구에서 데이터 및 구성 가져오기 작업을 수행한 후 다음 단계를 수행해야 합니다.


.단계
. FC 및 FCoE 구성만 해당:
+
.. HBA BIOS 설정 모드로 들어갑니다.
.. Rescan * 을 선택하여 호스트에서 ONTAP SAN 부팅 LUN을 검색합니다.
.. 7-Mode 부팅 LUN ID를 제거합니다.
.. HBA BIOS에서 ONTAP 부팅 LUN ID를 추가합니다.
.. HBA BIOS 설정 모드를 종료한 다음 호스트를 재부팅합니다.


. 호스트를 재부팅한 후 테스트 호스트에서 IP 주소와 호스트 이름을 변경합니다.
. 새 ONTAP LUN이 검색되었는지 확인합니다.
+
``sanlun lun show *’

. ONTAP LUN에 대해 DMMP 디바이스를 구성합니다.
+
'* multipath-ll*'

. 필요에 따라 테스트를 수행합니다.
. 테스트 호스트를 종료합니다.
+
' * shutdown -h -t0 now * '

. 7-Mode 전환 툴 사용자 인터페이스(UI)에서 * 테스트 완료 * 를 클릭합니다.


ONTAP LUN을 소스 호스트에 다시 매핑하려면 소스 호스트에서 컷오버 단계를 준비해야 합니다. ONTAP LUN을 테스트 호스트에 매핑된 상태로 유지하려면 테스트 호스트에 추가 단계가 필요하지 않습니다.

* 관련 정보 *

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[재고 평가 워크북에서 전이가 완료된 정보를 수집합니다]

xref:concept_preparing_for_cutover_when_transitioning_san_boot_luns.adoc[SAN 부팅 LUN을 전환할 때 컷오버 단계를 준비합니다]
