---
permalink: san-host/task_testing_data_luns_on_solaris_hosts_with_sun_volume_manager_svm_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, testing, data, solaris, sun, volume, manager, cutover, copy, based 
summary: '7MTT\(7-Mode 전환 툴) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 Solaris 호스트 ZFS 데이터 LUN을 전환하는 경우 전환된 clustered Data ONTAP LUN을 테스트하여 MPIO 디바이스를 컷오버 단계 전에 마운트할 수 있는지 확인할 수 있습니다. 테스트 중에 소스 호스트에서 소스 7-Mode LUN에 대한 I/O를 계속 실행할 수 있습니다.' 
---
= 복사 기반 전환의 컷오버 단계 전에 Sun Volume Manager를 사용하여 Solaris 호스트에서 데이터 LUN 테스트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7MTT(7-Mode 전환 툴) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 Solaris 호스트 ZFS 데이터 LUN을 전환하는 경우 전환된 clustered Data ONTAP LUN을 테스트하여 MPIO 디바이스를 컷오버 단계 전에 마운트할 수 있는지 확인할 수 있습니다. 테스트 중에 소스 호스트에서 소스 7-Mode LUN에 대한 I/O를 계속 실행할 수 있습니다.

테스트 단계 전환을 시작하기 전에 Sun Volume Manager 데이터 LUN이 있는 소스 호스트가 오프라인 상태여야 합니다.

새로운 clustered Data ONTAP LUN을 테스트 호스트에 매핑해야 하며 LUN을 전환할 준비가 되어 있어야 합니다

테스트 호스트와 소스 호스트 간에 하드웨어 패리티를 유지해야 하며 테스트 호스트에서 다음 단계를 수행해야 합니다.

Clustered Data ONTAP LUN은 테스트 중에 읽기/쓰기 모드로 전환됩니다. 테스트가 완료되고 컷오버 단계에 대비하는 동안 읽기 전용 모드로 전환됩니다.

.단계
. 운영 호스트에서 디스크 세트를 비활성화합니다.
+
' * metaset-s svm-t *'

+
``metaset-s svm-a disable *’

+
' * metaset-s svm-r * '

+
' * metaset-s svm-P * '

+
``메타셋 *’

. 기본 데이터 복사가 완료되면 7MTT 사용자 인터페이스(UI)에서 * 테스트 모드 * 를 선택합니다.
. 7MTT UI에서 * 구성 적용 * 을 클릭합니다.
. 운영 호스트에서 디스크 세트를 가져옵니다.
+
' * metaimport – s_set-name_ *'

+
[listing]
----
# metaimport -s svm
Drives in regular diskset including disk c0t60A98000383035356C2447384D39654Ad0:
  c0t60A98000383035356C2447384D39654Ad0
  c0t60A98000383035356C2447384D396548d0
More info:
  metaimport -r -v c0t60A98000383035356C2447384D39654Ad0


[22] 04:51:29 (root@sunx2-shu04) /
# metastat -s svm
svm/d2: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D396548d0s0          0     No      Yes

svm/d1: Concat/Stripe
    Size: 10452992 blocks (5.0 GB)
    Stripe 0:
        Device                                             Start Block  Dbase   Reloc
        /dev/dsk/c0t60A98000383035356C2447384D39654Ad0s0          0     No      Yes

Device Relocation Information:
Device                                           Reloc  Device ID
/dev/dsk/c0t60A98000383035356C2447384D396548d0   Yes    id1,sd@n60a98000383035356c2447384d396548
/dev/dsk/c0t60A98000383035356C2447384D39654Ad0   Yes    id1,sd@n60a98000383035356c2447384d39654a
----
. 테스트 호스트에서 새 clustered Data ONTAP LUN을 다시 검색합니다.
+
.. FC 호스트 포트(유형 fc-fabric):+' *#cfgadm –l *'를 식별합니다
.. 첫 번째 fc-fabric 포트: + " *#cfgadm –c unconfigure C1 * "의 구성을 해제합니다
.. 첫 번째 fc-fabric 포트(+' *#cfgadm –c unconfigure C2 *')를 구성합니다
.. 다른 FC-패브릭 포트에 대해서도 이 단계를 반복합니다.
.. 호스트 포트 및 연결된 장치에 대한 정보 표시: + "*#cfgadm –al *"
.. '*#devfsadm-CV *' 드라이버를 다시 로드합니다
+
'*#devfsadm-i iscsi *'



. Clustered Data ONTAP LUN이 있는지 확인합니다.
+
``sanlun lun show *’

+
[listing]
----
# sanlun lun show
controller(7mode)/                    device                                            host                  lun
vserver(Cmode)       lun-pathname     filename                                          adapter    protocol   size    mode
--------------------------------------------------------------------------------------------------------------------------
vs_5           /vol/zfs/zfs2    /dev/rdsk/c5t600A0980383030444D2B466542485935d0s2 scsi_vhci0 FCP        6g      C
vs_5           /vol/zfs/zfs1    /dev/rdsk/c5t600A0980383030444D2B466542485934d0s2 scsi_vhci0 FCP        6g      C
vs_5           /vol/ufs/ufs2    /dev/rdsk/c5t600A0980383030444D2B466542485937d0s2 scsi_vhci0 FCP        5g      C
vs_5           /vol/ufs/ufs1    /dev/rdsk/c5t600A0980383030444D2B466542485936d0s2 scsi_vhci0 FCP        5g      C
----
. 테스트할 Sun Volume Manager가 가져올 수 있는지 확인합니다.
+
' * metaimport – r – v * '

+
[listing]
----
# metaimport -r -v
Import: metaimport -s <newsetname> c5t600A0980383030444D2B466542485937d0
Device                                      offset       length replica flags
c5t600A0980383030444D2B466542485937d0           16         8192      a m     luo
c5t600A0980383030444D2B466542485936d0           16         8192      a       luo
----
. 새 이름으로 메타 세트 가져오기:
+
' * metaimport – s_set-name disk-id_ *'

+
disk-id는 metaimport--r--v 명령에서 얻어집니다.

+
[listing]
----
# metaimport -s svm c5t600A0980383030444D2B466542485937d0
Drives in regular diskset including disk c5t600A0980383030444D2B466542485937d0:
  c5t600A0980383030444D2B466542485937d0
  c5t600A0980383030444D2B466542485936d0
More info:
  metaimport -r -v c5t600A0980383030444D2B466542485937d0
----
. 메타셋 사용 가능 여부 확인:
+
``메타셋 *’

. 파일 시스템 검사를 실행합니다.
+
' * fsck-F ufs/dev/md/svm/rdsk/d1 * '

. mount 명령을 사용하여 수동으로 마운트합니다.
. 필요에 따라 테스트를 수행합니다.
. 테스트 호스트를 종료합니다.
. 7MTT UI에서 * 테스트 완료 * 를 클릭합니다.


Clustered Data ONTAP LUN을 소스 호스트에 다시 매핑하려면 소스 호스트에서 컷오버 단계를 준비해야 합니다. Clustered Data ONTAP LUN을 테스트 호스트에 매핑된 상태로 유지하려면 테스트 호스트에 추가 단계가 필요하지 않습니다.
