---
permalink: san-host/task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, cutover, phase, lun, point, dmmp, device, names 
summary: Linux 호스트에서 별칭 이름을 사용하여 마운트 지점으로 LUN을 전환하는 경우 컷오버 단계를 시작하기 전에 몇 가지 단계를 수행해야 합니다. 
---
= Linux 호스트에서 DMMP 디바이스 이름을 사용하여 마운트 지점으로 LUN을 전환할 때 컷오버 단계를 준비합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Linux 호스트에서 별칭 이름을 사용하여 마운트 지점으로 LUN을 전환하는 경우 컷오버 단계를 시작하기 전에 몇 가지 단계를 수행해야 합니다.

FC 구성의 경우 clustered Data ONTAP 컨트롤러에 대한 패브릭 연결 및 조닝(zoning)이 있어야 합니다.

iSCSI 구성의 경우, iSCSI 세션을 검색한 후 clustered Data ONTAP 컨트롤러에 로그인해야 합니다.

* 복사 기반 전환의 경우 7MTT(7-Mode Transition Tool)에서 스토리지 컷오버 작업을 시작하기 전에 다음 단계를 수행하십시오.
* 복사를 수행하지 않는 전환의 경우, 7MTT에서 내보내기 및 중지 7-Mode 시스템 작업을 시작하기 전에 다음 단계를 수행하십시오.


.단계
. 마운트 지점에 대한 입출력을 중지합니다.
. 애플리케이션 공급업체의 권장 사항에 따라 LUN에 액세스하는 애플리케이션을 종료합니다.
. DMMP 디바이스 마운트 해제:
+
"* umount_dir_name_*"

. 7-Mode LUN 플러시 DMMP 디바이스 ID:
+
"* multipath -f_device_name_ * "

+
필요한 경우 _Inventory Assessment 워크북_의 * SAN 호스트 LUN * 탭 아래에 있는 * OS Device ID * 열에서 DDMP 디바이스 이름을 확인할 수 있습니다.



* 관련 정보 *

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[재고 평가 워크북에서 전이가 완료된 정보를 수집합니다]
