---
permalink: san-host/task_testing_luns_with_mounts_using_dmmp_aliases_on_rhel_hosts_before_cutover.html 
sidebar: sidebar 
keywords: ontap, san, host, transition, mount, pints, dmmp, alias, name, rhel 
summary: '7MTT\) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 Red Hat Enterprise Linux\(RHEL\) 호스트의 복사 기반 전환을 수행하는 경우 전환 단계 전에 별칭 이름을 사용하여 전환된 clustered Data ONTAP LUN을 마운트 지점으로 테스트할 수 있습니다. 테스트 중에 소스 호스트에서 소스 7-Mode LUN에 대한 I/O를 계속 실행할 수 있습니다.' 
---
= 복제 기반 전환의 컷오버 단계 전에 RHEL 호스트에서 DMMP 별칭 이름을 사용하여 마운트 지점으로 LUN 테스트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7MTT(7-Mode 전환 툴) 2.2 이상 및 Data ONTAP 8.3.2 이상을 사용하여 RHEL(Red Hat Enterprise Linux) 호스트의 복사 기반 전환을 수행하는 경우 전환 단계 전에 별칭 이름을 사용하여 전환된 clustered Data ONTAP LUN을 마운트 지점으로 테스트할 수 있습니다. 테스트 중에 소스 호스트에서 소스 7-Mode LUN에 대한 I/O를 계속 실행할 수 있습니다.

새로운 clustered Data ONTAP LUN을 테스트 호스트에 매핑해야 하며 LUN을 전환할 준비가 되어 있어야 합니다.

테스트 호스트와 소스 호스트 간에 하드웨어 패리티를 유지해야 하며 테스트 호스트에서 다음 단계를 수행해야 합니다.

Clustered Data ONTAP LUN은 테스트 중에 읽기/쓰기 모드로 전환됩니다. 테스트가 완료되고 컷오버 단계에 대비하는 동안 읽기 전용 모드로 전환됩니다.

.단계
. 기본 데이터 복사가 완료되면 7MTT 사용자 인터페이스(UI)에서 * 테스트 모드 * 를 선택합니다.
. 7MTT UI에서 * 구성 적용 * 을 클릭합니다.
. Clustered Data ONTAP LUN에 대한 새 SCSI 디바이스 이름을 가져옵니다.
+
``sanlun lun show *’

+
다음 예에서, '/dev/sdl'은 'lun_dmmp_raw' LUN의 SCSI 디바이스 이름이고, '/dev/sdk'는 의 SCSI 디바이스 이름입니다

+
'lun_dmmp_raw_alias' LUN:

+
[listing]
----
[root@ibmx3550-229-108 /]# sanlun lun show
controller(7mode/E-Series)/
vserver (cDOT/FlashRay)     lun-pathname               filename
-----------------------------------------------------------------
vs_brb     /vol/dmmp_raw_vol/lun_dmmp_raw              /dev/sdl
vs_brb     /vol/dmmp_raw_alias_vol/lun_dmmp_raw_alias  /dev/sdk
----
. Clustered Data ONTAP LUN에 대해 DMMP 디바이스를 구성합니다.
+
' * multipath * '

. Clustered Data ONTAP LUN의 디바이스 핸들 ID를 가져옵니다.
+
'* multipath-ll*'

+
장치 핸들 ID의 예는 다음과 같습니다. "'3600a09804d532d79565d47617679764d'"

. 소스 호스트의 '/etc/multipath.conf' 파일에 별칭이 정의되어 있는지 확인합니다.
. 별칭 구성을 테스트 호스트의 '/etc/multipath.conf' 파일에 수동으로 복사하되, 7-Mode 디바이스 핸들 ID를 해당하는 clustered Data ONTAP 디바이스 핸들 ID로 교체합니다.
. 'multipath' 명령을 사용하여 clustered Data ONTAP LUN에 대한 DMMP 디바이스를 구성합니다.
. DMMP 별칭 장치에서 생성된 파일 시스템을 식별합니다.
+
' * blkid_dmmp_device_name_ * '

. DMMP 디바이스를 마운트합니다.
+
' * 마운트 * '

. 필요에 따라 테스트를 수행합니다.
. 테스트를 완료한 후 테스트 호스트를 종료합니다.
+
' * shutdown -h -t0 now * '

. 7MTT UI에서 * 테스트 완료 * 를 클릭합니다.


Clustered Data ONTAP LUN을 소스 호스트에 다시 매핑하려면 소스 호스트에서 컷오버 단계를 준비해야 합니다. Clustered Data ONTAP LUN을 테스트 호스트에 매핑된 상태로 유지하려면 테스트 호스트에 추가 단계가 필요하지 않습니다.

* 관련 정보 *

xref:task_gathering_pretransition_information_from_inventory_assessment_workbook.adoc[재고 평가 워크북에서 전이가 완료된 정보를 수집합니다]

xref:task_preparing_for_cutover_when_transitioning_luns_with_mounts_using_dmmp_aliases_on_linux_hosts.adoc[Linux 호스트에서 DMMP 디바이스 이름을 사용하여 마운트 지점으로 LUN을 전환할 때 컷오버 단계를 준비합니다]
