---
permalink: copy-based/concept_preparing_for_metrocluster_configuration_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, prepare, metrocluster, configuration 
summary: MetroCluster 구성으로 전환하기 전에 7-Mode 볼륨을 ONTAP의 MetroCluster 구성으로 전환하기 위한 요구사항과 고려 사항을 이해해야 합니다. 
---
= MetroCluster 구성 전환 준비 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MetroCluster 구성으로 전환하기 전에 7-Mode 볼륨을 ONTAP의 MetroCluster 구성으로 전환하기 위한 요구사항과 고려 사항을 이해해야 합니다.



== 필수 구성 요소

* ONTAP의 MetroCluster 구성이 이미 설정되어 있어야 합니다.
* SVM 유형은 '동기화 소스'여야 합니다.
* 7-Mode 컨트롤러가 Takeover 상태에 있거나 Giveback을 기다리고 있으면 안 됩니다.
* ONTAP의 MetroCluster 구성에 있는 노드는 스위치오버나 스위치백을 기다릴 수 없습니다.




== 고려 사항

* 타겟 클러스터가 MetroCluster 구성에 있으면 SnapLock Compliance 볼륨 전환이 지원되지 않습니다.
* 볼륨을 7-Mode 컨트롤러, HA 구성 또는 MetroCluster 구성에서 ONTAP의 MetroCluster 구성으로 독립 실행형 볼륨으로 전환할 수 있습니다.
* 7-Mode MetroCluster 구성에 다른 7-Mode 컨트롤러의 볼륨과 볼륨 SnapMirror 관계에 있는 볼륨이 있는 경우 SnapMirror 관계를 운영 및 2차 관계로 전환할 수 있습니다.
+
각 MetroCluster 사이트에 7-Mode 전환 툴을 설치하고 각 사이트의 볼륨을 전환해야 합니다.

* 7-Mode 패브릭용으로 구성된 서로 다른 서브넷의 MetroCluster 구성은 ONTAP의 MetroCluster 구성에서 구성할 수 없습니다.
* 7-Mode 패브릭 MetroCluster 구성에서 구성된 기본 포트는 ONTAP의 MetroCluster 구성에 대해 구성할 수 없습니다.
* 7-Mode 패브릭 MetroCluster 구성에서 Brocade 6510 스위치를 사용하는 경우 기존 스위치 패브릭을 ONTAP의 새로운 MetroCluster 구성과 공유할 수 있습니다.
+
전환 기간 동안에만 스위치 패브릭을 공유하는 것이 좋습니다.

+
https://["패브릭 연결 MetroCluster 설치 및 구성, ONTAP 9.8 이전 버전"]

+
https://["패브릭 연결 MetroCluster 설치 및 구성, ONTAP 9.9.1"]

* 전환 중에 생성된 cron 작업 일정은 원격 사이트로 복제되지 않으므로 전환 후 협상된 전환이 실패합니다.
+
전환 후에 원격 사이트에서 cron 작업 스케줄을 수동으로 생성해야 합니다.



* 관련 정보 *

xref:task_post_transition_task_for_a_metrocluster_configuration.adoc[MetroCluster 구성을 이전한 후 원격 사이트에서 cron 작업 스케줄을 구성합니다]

xref:concept_impact_of_takeover_and_giveback_on_transition.adoc[Takeover와 Giveback이 전환에 미치는 영향]

xref:task_transitioning_a_metrocluster_configuration_if_a_switchover_or_switchback_event_occurs.adoc[스위치오버 또는 스위치백 으로 인해 실패한 MetroCluster 구성 전환]
