---
permalink: copy-based/concept_considerations_for_local_users_and_groups_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, cifs, local, users, groups 
summary: CIFS 로컬 사용자 및 그룹을 마이그레이션할 때 전환 작업을 실행할 때 고려해야 할 사항에 대해 알고 있어야 합니다. 
---
= CIFS 로컬 사용자 및 그룹을 전환하기 위한 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CIFS 로컬 사용자 및 그룹을 마이그레이션할 때 전환 작업을 실행할 때 고려해야 할 사항에 대해 알고 있어야 합니다.

* 타겟 클러스터에서 clustered Data ONTAP 8.2가 실행 중인 경우 CIFS 데이터를 제공하고 로컬 사용자 및 그룹이 액세스하는 7-Mode 볼륨에 대해 전환을 시도해서는 안 됩니다.
+
7-Mode 전환 툴은 로컬 사용자 및 그룹을 clustered Data ONTAP 8.2로 전환하는 기능을 지원하지 않습니다.

* 로컬 사용자 및 그룹이 UILTIN CIFS 로컬 사용자 및 그룹이 아닌 SVM으로 CIFS 데이터 서비스 볼륨을 7-Mode 컨트롤러 또는 vFiler 유닛에서 전환이 지원되지 않습니다.
+
SVM은 전환을 위해 BUILTIN CIFS 로컬 사용자 및 그룹만 포함해야 합니다.

+
로컬 사용자 및 그룹을 특정 7-Mode 컨트롤러 또는 vFiler 유닛에서 특정 SVM으로 전환하는 동안 첫 번째 전환 프로젝트의 로컬 사용자 및 그룹이 전환됨 동일한 7-Mode 컨트롤러 또는 vFiler 유닛이 있는 프로젝트가 동일한 SVM으로 후속 전환되면 전환이 성공하더라도 로컬 사용자 및 그룹의 전환은 무시됩니다. 7-Mode 시스템의 로컬 사용자 이름은 SVM의 CIFS 서버 이름과 같을 수 없습니다.

* Clustered Data ONTAP 8.2.1 이상에서 지원되는 로컬 사용자 및 그룹 수에 대한 제한을 알고 있어야 합니다.
* 7-Mode 시스템에서 14자 이상이 포함된 암호가 있는 로컬 사용자 계정 또는 빈 암호가 있는 로컬 사용자 계정은 암호 " * cifsUser@1 * "를 사용하여 ONTAP 소프트웨어로 전환됩니다.
+
전환이 완료되면 비밀번호 " * cifsUser@1 * "를 사용하여 Windows 시스템에서 이러한 사용자에 액세스할 수 있습니다. 그런 다음 다음 다음 명령을 사용하여 SVM에서 해당 CIFS 로컬 사용자의 암호를 수동으로 변경해야 합니다.

+
'* cifs users-and-groups local-user set-password-vserver_svm_name_-user-name_user_name_ *'.

* 타겟 ONTAP 소프트웨어에서 7-Mode 전환 툴 IP 주소에 연결할 수 없는 경우 7-Mode 전환 툴을 사용하면 사전 점검 단계 중에 CIFS 로컬 사용자 및 그룹이 ONTAP 소프트웨어로 전환할 수 없습니다. 사전 점검 단계 중에 이 오류가 나타나면 를 사용합니다
+
'* network ping-node local-destination_ip_address_*'

+
타겟 ONTAP 소프트웨어에서 7-Mode 전환 툴 IP 주소에 연결할 수 있는지 확인하는 명령입니다. 7-Mode Transition Tool과 함께 설치된 '\etc\conf\transition-tool.conf' 파일을 편집하여 7-Mode Transition Tool IP 주소 등 도구에서 사용하는 구성 옵션을 수정할 수 있습니다.

* 로컬 사용자 및 그룹이 전환된 SVM에 데이터 LIF가 있어야 합니다.
* 로컬 그룹에 7-Mode 시스템의 단일 도메인 사용자 또는 그룹에 매핑된 여러 구성원 SID(시스템 식별자)가 있는 경우 7-Mode 전환 도구는 사전 점검 단계 중에 로컬 사용자 및 그룹이 ONTAP로 전환되는 것을 차단합니다.
+
사전 점검 단계 중에 이 오류가 표시되는 경우 7-Mode 시스템의 단일 도메인 사용자 또는 그룹에 매핑된 추가 SID를 수동으로 제거해야 합니다. 그런 다음 도메인 사용자 또는 그룹에 매핑된 단일 SID만 사용하여 사전 검사 작업을 다시 실행해야 합니다.

+
https://["문제 해결 워크플로우: CIFS: 시스템에 연결된 디바이스가 작동하지 않습니다"]



* 관련 정보 *

http://["SMB/CIFS 관리"]
