---
permalink: copy-based/concept_port_requirements_for_communicating_with_7mtt.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, port, requirements, communicating, tool 
summary: 7-Mode 전환 툴은 7-Mode 시스템과 통신하며 클러스터는 특정 포트를 통해 통신합니다. 7-Mode 시스템과 클러스터에서 이러한 포트가 열려 있는지 확인하여 7-Mode 전환 툴과의 통신을 허용해야 합니다. 
---
= 7-Mode Transition Tool과 통신하기 위한 포트 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode 전환 툴은 7-Mode 시스템과 통신하며 클러스터는 특정 포트를 통해 통신합니다. 7-Mode 시스템과 클러스터에서 이러한 포트가 열려 있는지 확인하여 7-Mode 전환 툴과의 통신을 허용해야 합니다.



== 7-Mode 시스템에서 열려 있어야 하는 포트

7-Mode 전환 툴은 포트 443에서 HTTPS를 사용하여 7-Mode 시스템과 통신합니다.

SnapMirror 복제를 위해 7-Mode 시스템과 통신하기 위해 클러스터에는 다음 포트가 필요합니다.

* 10565/TCP
* 10566/TCP
* 10567/TCP
* 10568/TCP
* 10569/TCP
* 10670/TCP




== 클러스터에서 열려 있어야 하는 포트

7-Mode 전환 툴은 포트 443에서 HTTPS를 사용하여 클러스터와 통신합니다.

7-Mode 시스템에서 SnapMirror 복제를 위해 클러스터와 통신하려면 다음 포트가 필요합니다.

* 10565/TCP
* 10566/TCP
* 10567/TCP
* 10568/TCP
* 10569/TCP
* 10670/TCP
* 11105/TCP


또한 7-Mode 전환 툴은 인터클러스터 LIF에서 7-Mode 시스템의 데이터 복사 IP 주소로 ping 작업을 수행하여 액세스 가능성을 검증합니다.



== 7-Mode 전환 도구에서 열려 있어야 하는 포트

웹 인터페이스를 사용하려면 7-Mode Transition Tool의 포트 8444가 열려 있어야 합니다.

넷그룹과 CIFS 로컬 사용자 및 그룹을 이전하려면 다음 요구 사항을 충족해야 합니다.

* 7-Mode Transition Tool의 포트 8088을 사용할 수 있어야 합니다.
+
포트 8088 대신 7-Mode Transition Tool 설치 디렉토리의 transition-tool.conf 파일에서 tool.http.port 매개변수로 지정한 포트를 변경해야 합니다.

+

NOTE: 구성 파일에서 포트를 변경한 후에는 7-Mode Transition Tool 서비스를 다시 시작해야 합니다.

* 클러스터의 각 노드에는 타겟 SVM용으로 구성된 데이터 LIF가 하나 이상 있어야 합니다.
* 모든 SVM 데이터 LIF는 'transition-tool.conf' 파일의 'tool.http.port' 매개 변수에 지정된 포트 또는 7-Mode Transition Tool 포트 8088과 통신할 수 있어야 합니다.
+

NOTE: 방화벽이 이 트래픽을 차단하지 않는지 확인해야 합니다.


