---
permalink: copy-based/concept_considerations_for_deduplication_and_compression.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, deduplication, compression 
summary: 압축을 사용할 경우 소스 볼륨과 타겟 볼륨이 64비트 애그리게이트에 속해 있어야 합니다. 소스 볼륨의 모든 압축 및 중복제거 절약 효과는 전환 중에 네트워크를 통해 유지됩니다. 전환이 완료되면 모든 압축 및 중복제거 특성과 스토리지 절약 효과가 소스 볼륨에서 타겟 볼륨으로 상속됩니다. 
---
= 중복제거 및 압축 관련 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
압축을 사용할 경우 소스 볼륨과 타겟 볼륨이 64비트 애그리게이트에 속해 있어야 합니다. 소스 볼륨의 모든 압축 및 중복제거 절약 효과는 전환 중에 네트워크를 통해 유지됩니다. 전환이 완료되면 모든 압축 및 중복제거 특성과 스토리지 절약 효과가 소스 볼륨에서 타겟 볼륨으로 상속됩니다.

다음과 같은 이유로, 중복제거되고 압축된 데이터를 전환하면 전환 중에 네트워크 대역폭을 절감할 수 있습니다.

* 공유 블록은 한 번만 전송됩니다.
* 전송 과정 내내 압축이 유지됩니다.
* 압축 및 중복제거를 통해 공간이 절약됨에 따라 압축 및 중복제거된 데이터는 전송 크기가 더 작습니다. 따라서 전송하는 데 더 빠르게 걸립니다.


전환 중에 소스 볼륨에서 기존 데이터의 압축 또는 중복제거를 시작하면 안 됩니다. 중복제거 또는 압축이 진행 중인 경우 중복제거 또는 압축 작업이 완료된 후에만 전환을 시작해야 합니다. 따라서 중복제거되지 않거나 압축되지 않은 데이터와 추가적인 임시 메타데이터 파일이 네트워크를 통해 타겟 볼륨으로 전송되지 않습니다.

중복제거 및 압축이 ONTAP 볼륨에 기록된 새 데이터에 적용되도록 하려면 전환이 끝난 후에 중복제거 및 압축 일정을 활성화해야 합니다.

Data ONTAP 8.1부터 중복 제거 기능은 부분적으로 순서가 지정된 지문 데이터베이스를 애그리게이트 복사본과 함께 볼륨에 유지합니다. 따라서 타겟 시스템에 소스 볼륨의 공간 절약 효과와 순서가 지정된 지문 데이터베이스의 복사본이 적용됩니다. 마이그레이션 후 새 볼륨에서 볼륨 효율성을 처음으로 실행할 때 타겟 볼륨의 복사본을 사용하여 애그리게이트 지문 데이터베이스가 자동으로 구성됩니다. 따라서 볼륨 효율성 작업이 완료되는 데 걸리는 시간이 1회 증가할 수 있습니다.

8.1 Data ONTAP 이전 7-Mode에서 실행 중인 소스 볼륨에서 '-scan-old-data option' 매개 변수를 사용하여 'volume Efficiency start' 명령을 실행하여 공간 절약을 최적화해야 합니다. 마이그레이션이 완료된 후에는 중복제거 일정이 클러스터의 요구사항을 충족하는지 확인하고 볼륨 효율성 정책으로 전환하는 것을 고려해야 합니다.
