---
permalink: copy-based/concept_considerations_for_using_snapmirror_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, snapmirror 
summary: 데이터 복사 일정을 작성하고 기존 7-Mode에서 7-Mode SnapMirror 또는 SnapVault로 전환하는 작업에 영향을 주지 않고 전환 작업에 대한 SnapMirror 데이터 전송을 사용자 지정할 수 있습니다. 
---
= 전환을 위해 SnapMirror를 사용할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 복사 일정을 작성하고 기존 7-Mode에서 7-Mode SnapMirror 또는 SnapVault로 전환하는 작업에 영향을 주지 않고 전환 작업에 대한 SnapMirror 데이터 전송을 사용자 지정할 수 있습니다.



== 최대 동시 SnapMirror 전송 수입니다

전환 중에 7-Mode 및 ONTAP 시스템에서 지원되는 최대 동시 SnapMirror 전송 수는 특정 스토리지 시스템 모델에 허용되는 볼륨 SnapMirror 복제 작업의 수에 따라 달라집니다.

시스템 모델의 최대 동시 볼륨 SnapMirror 전송 수에 대한 자세한 내용은 를 참조하십시오 link:https://library.netapp.com/ecm/ecm_get_file/ECMP1635994["7-Mode용 Data ONTAP 데이터 보호 온라인 백업 및 복구 가이드 를 참조하십시오"].



== 데이터 복사 스케줄

* 기본, 업데이트 또는 재동기화 등 SnapMirror 작업을 실행하는 데 사용되는 SnapMirror 동시 전송 수는 프로젝트를 생성하는 동안 구성한 일정에 따라 달라집니다.
* 서로 다른 프로젝트에서 동일한 7-Mode 컨트롤러에서 볼륨을 전환하는 경우 데이터 복사 일정이 다른 프로젝트에 겹치지 않도록 해야 합니다.
* 다음과 같은 방법으로 7-Mode Transition Tool 전환 작업의 기존 백업 및 DR(재해 복구) 작업에 영향을 주지 않도록 할 수 있습니다.
+
** 프로젝트에 대한 SnapMirror 데이터 복사본 일정을 만들어 기존 7-Mode SnapMirror 또는 SnapVault 일정과 겹치지 않게 해야 합니다.
** 기존 7-Mode SnapMirror 또는 SnapVault 일정에 장애가 발생할 수 있도록 동시 SnapMirror 전송 수를 구성해야 합니다.
+
활성 일정을 편집하고 동시 볼륨 SnapMirror 전송 최대 수를 0으로 수정하여 일부 전송을 릴리스할 수도 있습니다.



* 운영 기간 동안 7-Mode 스토리지 시스템에서 동시 SnapMirror 전송 수와 작업(사전 컷오버, 컷오버, 온디맨드 업데이트)에 대해 구성된 스로틀을 사용할 수 있어야 합니다.
+
프로젝트의 볼륨 중 하나에 대해서도 최종 증분 업데이트 작업이 실패하면 컷오버 작업이 실패합니다.

* 2차 프로젝트의 경우, 컷오버 이후 7-Mode 운영 볼륨과 ONTAP 2차 볼륨 간의 SnapMirror 관계에 대한 증분 SnapMirror 업데이트가 7-Mode에서 7-Mode SnapMirror 관계 일정을 기반으로 합니다.
+
7-Mode 기본 컨트롤러에서 이러한 업데이트를 수행할 수 있는 충분한 동시 SnapMirror 전송이 있는지 확인해야 합니다.





== 전이를 위해 여러 경로를 사용합니다

데이터 복사 IP 주소와 다중 경로 IP 주소를 사용하여 전환할 두 개의 경로를 지정할 수 있습니다. 그러나 두 경로는 모두 로드 밸런싱에만 사용할 수 있고 페일오버에는 사용할 수 없습니다.

* 관련 정보 *

xref:concept_guidelines_for_creating_a_data_copy_schedule.adoc[데이터 복사 스케줄을 생성할 때의 고려 사항]

xref:task_creating_schedule_for_snapmirror_transfers.adoc[SnapMirror 전송을 위한 데이터 복사본 일정 생성]
