---
permalink: copy-based/concept_guidelines_for_creating_a_data_copy_schedule.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, create, data, copy, schedule 
summary: 7-Mode Transition Tool은 5분마다 활성 스케줄을 확인하는 스케줄러를 실행합니다. 데이터 복사 일정을 활성화하려면 요구 사항을 알고 있어야 합니다. 데이터 복사 스케줄의 여러 매개 변수를 구성할 때 몇 가지 모범 사례를 따라 SnapMirror 전송을 효과적으로 관리할 수 있습니다. 
---
= 데이터 복사 스케줄을 생성할 때의 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode Transition Tool은 5분마다 활성 스케줄을 확인하는 스케줄러를 실행합니다. 데이터 복사 일정을 활성화하려면 요구 사항을 알고 있어야 합니다. 데이터 복사 스케줄의 여러 매개 변수를 구성할 때 몇 가지 모범 사례를 따라 SnapMirror 전송을 효과적으로 관리할 수 있습니다.



== 데이터 복사 일정을 활성화하려면 요구 사항

* 7-Mode 전환 툴 서비스가 실행 중이어야 합니다.
+
7-Mode 전환 툴 서비스를 다시 시작하면 자격 증명이 추가될 때까지 SnapMirror 작업이 수행되지 않습니다.

* SnapMirror 데이터 복사 작업을 실행하려면 적어도 하나의 데이터 복사본 일정을 사용할 수 있어야 합니다.
+
특정 시간 범위에 사용할 수 있는 일정이 없는 경우 해당 시간 동안 SnapMirror 데이터 복사 작업이 수행되지 않습니다.

* SnapMirror 관계가 중지 상태인 경우 데이터 복사 작업이 수행되지 않습니다.
* 데이터 복사 일정에 따라 증분 전송이 수행되도록 7-Mode와 클러스터의 시스템 시간을 동기화해야 합니다.
+
7-Mode 시스템 시간이 클러스터 시간보다 늦으면 지정된 업데이트 빈도보다 더 자주 업데이트가 예약됩니다. 7-Mode 시스템 시간이 클러스터 시간보다 늦으면 업데이트가 지정된 업데이트 빈도보다 지연됩니다.





== 데이터를 복사하는 동안 모범 사례를 따르는 것입니다

SnapMirror 복제 성능을 높이기 위해 소스 및 타겟 시스템에 최적의 CPU 활용률과 메모리가 있어야 합니다. 또한 마이그레이션 작업과 관련이 없는 네트워크 트래픽을 최소화하여 처리량을 극대화하고 소스 시스템과 대상 시스템 간에 지연 시간을 최소화해야 합니다.



== 데이터 전송 우선 순위

데이터 복제 작업을 예약할 때 기준 또는 재동기화 작업이 증가분 전송보다 우선합니다.

SnapMirror 전송 해제를 위해 데이터 복사 작업을 중단하는 경우 먼저 증분 전송이 중단되고 기본 또는 재동기화 작업이 중단됩니다.

증분 전송의 경우 이전 업데이트에서 경과된 시간을 기준으로 소스 볼륨 뒤에 있는 볼륨에 우선 순위가 부여됩니다.
