---
permalink: copy-based/concept_transition_terminology.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, terminology 
summary: 7-Mode 전환 툴과 관련된 전환 용어를 이해하면 전환 프로세스를 이해하는 데 도움이 됩니다. 
---
= 전환 용어
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode 전환 툴과 관련된 전환 용어를 이해하면 전환 프로세스를 이해하는 데 도움이 됩니다.

* * 수집 및 평가 *
+
데이터 및 구성을 ONTAP로 전환하기 전에 스토리지 시스템, 호스트 및 애플리케이션을 포함한 스토리지 환경에 대한 정보를 수집해야 합니다. 그런 다음 이러한 시스템의 기능과 특징을 평가하고, 전환을 위해 선택한 ONTAP 버전에서 이러한 기능이 어떻게 작동하는지를 파악해야 합니다.

* * 마이그레이션 *
+
데이터 및 구성을 7-Mode 볼륨에서 ONTAP로 전환하는 것을 의미합니다. 마이그레이션은 7-Mode 컨트롤러를 평가한 후 수행해야 합니다.

* * 프로젝트 *
+
7-Mode 전환 툴 에서는 프로젝트를 통해 볼륨 그룹의 전환을 구성 및 관리할 수 있습니다.

+
전환 프로젝트에는 독립 실행형, 운영, 2차 등 3가지 유형이 있습니다.

+
** * 독립 실행형 프로젝트 *
+
이 프로젝트의 볼륨은 다른 스토리지 시스템의 볼륨과 SnapMirror 관계에 없거나 SnapMirror 관계를 유지하지 않고 이러한 볼륨을 전환하려고 합니다.

** * 기본 프로젝트 *
+
이 프로젝트의 볼륨은 SnapMirror 관계의 소스 볼륨입니다.

** * 보조 프로젝트 *
+
이 프로젝트의 볼륨은 SnapMirror 관계의 대상 볼륨입니다.



* * 프로젝트 그룹 *
+
7-Mode 전환 툴에서 프로젝트 그룹은 관련 마이그레이션 프로젝트를 진행하는 데 사용할 수 있는 논리적 컨테이너입니다. 시스템에 항상 Default_Group 이름을 가진 기본 그룹이 하나 있습니다.

* * 전환 피어 관계 *
+
전환 피어 관계는 전환 시 SnapMirror가 7-Mode 스토리지 시스템과 클러스터 내의 SVM 간 관계를 설정하여 7-Mode 볼륨에서 ONTAP 볼륨으로 데이터를 복사하여 전환할 수 있도록 하는 인증 메커니즘입니다. 전환 피어 관계는 클러스터 관리자만 생성할 수 있으며 클러스터에서 시작됩니다.

* * 데이터 보호 관계 전환 *
+
TDP(전환 데이터 보호) 관계는 7-Mode 시스템과 ONTAP 시스템 간에 설정되는 볼륨 SnapMirror 관계입니다.

+
전환 데이터 보호는 전환 시에만 지원됩니다. ONTAP 볼륨의 데이터를 다시 7-Mode 볼륨으로 재동기화할 수 없으므로 이 관계를 장기간 유지하지 않아야 합니다.


