---
permalink: copy-based/concept_restrictions_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, restrictions 
summary: 일부 7-Mode 볼륨 및 구성의 전환에는 특정 제한이 있다는 점을 알고 있어야 합니다. 
---
= 전환 제한 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
일부 7-Mode 볼륨 및 구성의 전환에는 특정 제한이 있다는 점을 알고 있어야 합니다.

* 동일한 프로젝트의 모든 볼륨에서 베이스라인 전송이 완료될 때까지 동일한 프로젝트 내의 어떤 볼륨도 컷오버할 수 없습니다.
* 7-Mode 기본 볼륨과 2차 볼륨을 7-Mode 소스 및 대상에서 Data ONTAP 7.3.x 또는 8.0.x를 실행 중인 경우 7-Mode 기본 볼륨에서 7-Mode 보조 볼륨으로 데이터 업데이트가 없는 경우에만 7-Mode 보조 볼륨을 전환을 시작해야 합니다.
+
7-Mode 운영 볼륨에서 7-Mode 2차 볼륨으로 데이터 업데이트 일정을 수행한다고 해서 7-Mode 2차 볼륨의 일정이 ONTAP 2차 볼륨으로 전송되는 7-Mode 2차 볼륨의 일정과 충돌하지 않는지 확인해야 합니다.

* 7-Mode 시스템 또는 클러스터의 애그리게이트를 32비트에서 64비트 형식으로 업그레이드하는 동안에는 전환을 시작하지 마십시오. 그렇지 않으면 전환이 실패합니다.
* 7-Mode 전환 툴에서는 qtree SnapMirror 관계의 대상이 되는 볼륨이 전환되지 않습니다.
+
Qtree SnapMirror 관계는 볼륨을 전환하기 전에 깨져야 합니다.

* 7-Mode 전환 툴 웹 인터페이스를 사용하면 팬아웃 SnapMirror 관계(서로 다른 컨트롤러에 있는 둘 이상의 보조 볼륨과 SnapMirror 관계에 있는 운영 볼륨)를 전환할 수 없습니다.
+
팬아웃 구성에서 SnapMirror 관계를 이전하려면 7-Mode 전환 툴 CLI를 사용해야 합니다. 각 2차 볼륨에 대해 별도의 프로젝트를 생성하고 2차 프로젝트의 전환을 완료한 다음 운영 볼륨의 전환을 만들고 완료해야 합니다.

* 볼륨을 다른 vFiler 유닛 또는 다른 7-Mode 컨트롤러에서 동일한 SVM으로 동시에 전환할 수 없습니다.
+
다른 vFiler 유닛 또는 7-Mode 컨트롤러에서 볼륨 전환을 시작하려면 먼저 지정된 vFiler 유닛 또는 7-Mode 컨트롤러에서 볼륨 전환을 완료해야 합니다.

* 7-Mode 전환 툴에서는 vFiler 유닛을 단일 엔터티로 전환하지 않습니다.
+
그러나 하나 이상의 프로젝트의 일부로 선택하여 vFiler 유닛의 모든 볼륨을 전환할 수 있습니다.

* 루트 볼륨이 기본 vFiler 유닛에 속하는 qtree를 기반으로 하는 경우 7-Mode 전환 툴은 vFiler 유닛의 루트 볼륨을 전환하지 않습니다.
* 볼륨과 qtree가 다른 vFiler 유닛에서 소유된 경우 7-Mode 전환 툴은 qtree로 볼륨을 전환하지 않습니다.
+
이러한 볼륨을 전환하면 qtree에 액세스할 수 없게 됩니다.

* 전환된 볼륨은 FlexGroup 볼륨으로 변환할 수 없습니다.


사전 점검 작업은 이러한 제한 사항 중 일부에 대한 정보를 표시합니다.
