---
permalink: copy-based/reference_commands_for_managing_transition_sessions.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, cbt, command, manage 
summary: 전환 CBT 명령을 사용하여 전환 프로젝트 생성, 수정, 삭제 및 표시 등의 기능을 관리할 수 있습니다. 
---
= 전환 관리를 위한 명령입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환 CBT 명령을 사용하면 전환 프로젝트를 생성, 수정, 삭제, 표시하는 등의 기능을 관리할 수 있습니다.

다음 옵션은 모든 명령에 사용할 수 있습니다.

'-r no': 명령의 대화형 특성을 비활성화합니다. 기본적으로 이 옵션은 활성화되어 있습니다.

전환 버전 및 CBT 전환 메뉴 명령을 사용하여 세부 모드를 활성화하는 '-v' 옵션을 사용할 수도 있습니다.



== 전환 작업을 관리하는 명령입니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
전이 프로젝트를 작성합니다
 a| 
'CBT 생성 전환'



 a| 
주어진 프로젝트에 클러스터 정보를 추가합니다
 a| 
'CBT 추가 클러스터 정보 전환



 a| 
전이 프로젝트를 수정합니다
 a| 
"CBT 변경"



 a| 
ONTAP 스토리지 시스템으로 전환을 완료합니다
 a| 
'CBT 전환



 a| 
프로젝트에 대한 사전 검사를 실행합니다
 a| 
CBT의 전환 사전 점검



 a| 
ONTAP 스토리지 시스템에 구성을 적용합니다
 a| 
'CBT 사전 전환



 a| 
프로젝트의 7-Mode 볼륨과 ONTAP 볼륨 간에 SnapMirror 재동기화를 시작합니다
 a| 
전환 CBT 재동기화



 a| 
ONTAP 볼륨에 대해 SnapMirror 업데이트 작업을 트리거합니다
 a| 
CBT 업데이트 전환



 a| 
7-Mode 전환 툴의 버전을 표시합니다
 a| 
CBT 버전 전환



 a| 
7-Mode 볼륨에서 프로젝트의 ONTAP 볼륨으로 기본 데이터 복사본을 시작합니다
 a| 
'CBT 시작'



 a| 
7-Mode 볼륨에서 프로젝트의 ONTAP 볼륨으로 데이터 복사본을 일시 중지합니다
 a| 
'CBT 전환 일시 중지'



 a| 
7-Mode 볼륨에서 일시 중지된 프로젝트의 ONTAP 볼륨으로 데이터 복사본 전송을 재개합니다
 a| 
'CBT 재가동



 a| 
전환 프로젝트를 중단합니다
 a| 
'CBT 전환 중단'



 a| 
전이 프로젝트를 삭제합니다
 a| 
CBT 삭제 전환



 a| 
전이 프로젝트 목록을 표시하거나 프로젝트에 대한 정보를 표시합니다
 a| 
'CBT 쇼 전환'

|===


== 볼륨 SnapMirror 관계를 관리하는 명령입니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
7-Mode 운영 시스템에 대한 정보를 2차 프로젝트에 추가합니다
 a| 
CBT 추가-기본-7-모드-시스템 전환

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/CBT_%3A_How_to_provide_all_the_required_primary_7-Mode_details_for_a_given_secondary_project["CBT: 특정 보조 프로젝트에 필요한 모든 기본 7-Mode 세부 정보를 제공하는 방법"]



 a| 
ONTAP 보조 시스템에 대한 정보를 기본 프로젝트에 추가합니다
 a| 
'CBT 애드-세컨더리-클러스터-모드-시스템 전환

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/CBT%3A_How_to_add_the_required_secondary_cluster_details_to_the_primary_project["CBT: 기본 프로젝트에 필요한 보조 클러스터 세부 정보를 추가하는 방법"]



 a| 
보조 프로젝트에서 7-Mode 운영 시스템에 대한 정보를 제거합니다
 a| 
CBT 제거-기본-7-모드-시스템 전환



 a| 
기본 프로젝트에서 ONTAP 보조 시스템에 대한 정보를 제거합니다
 a| 
'CBT 제거-보조-클러스터-모드-시스템 전환



 a| 
2차 프로젝트에 추가된 7-Mode 운영 시스템을 나열합니다
 a| 
CBT 전환=1차-7모드-시스템



 a| 
기본 프로젝트에 추가된 ONTAP 보조 시스템을 나열합니다
 a| 
'CBT 전환' '보조 클러스터 모드 시스템

|===


== Data ONTAP 시스템의 자격 증명을 관리하는 명령입니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
전환 서버에 있는 호스트의 자격 증명(사용자 이름 및 암호)을 저장합니다
 a| 
전환 자격 증명 추가



 a| 
호스트의 사용자 이름을 검색합니다
 a| 
전환 자격 증명 가져오기



 a| 
호스트의 사용자 이름 또는 암호를 수정합니다
 a| 
전환 자격 증명 수정



 a| 
전환 서버에서 호스트의 자격 증명을 삭제합니다
 a| 
전환 자격 증명 제거

|===


== 프로젝트의 볼륨 쌍을 관리하는 명령입니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
7-Mode 볼륨과 ONTAP 볼륨(볼륨 쌍)을 프로젝트에 추가합니다
 a| 
'CBT 볼륨 추가



 a| 
프로젝트의 ONTAP 볼륨을 수정합니다
 a| 
'CBT 볼륨 수정'



 a| 
프로젝트에서 볼륨 쌍을 제거합니다
 a| 
CBT 볼륨 제거 전환



 a| 
프로젝트의 볼륨 쌍을 나열합니다
 a| 
'CBT 볼륨 쇼'

|===


== LIF 세부 정보를 관리하는 명령입니다


NOTE: FC 및 iSCSI LIF는 7-Mode 전환 툴을 통해 전환되지 않습니다.

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
프로젝트에 anSVM 데이터 LIF 추가
 a| 
'CBT 추가 전환'



 a| 
프로젝트의 anSVM 데이터 LIF 수정
 a| 
'CBT의 전환 수정'



 a| 
프로젝트에서 LIF를 제거합니다
 a| 
'CBT 리프 제거'



 a| 
프로젝트에 추가된 모든 LIF를 나열합니다
 a| 
'CBT 리프 쇼 전환'

|===


== 프로젝트 속성을 관리하는 명령입니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
특정 프로젝트 속성의 값을 설정합니다
 a| 
CBT 속성 세트 전환



 a| 
특정 프로젝트 속성 값을 지웁니다
 a| 
'CBT 속성 재설정'을 선택합니다



 a| 
특정 프로젝트 속성의 값을 가져옵니다
 a| 
'CBT 재산-GET' 전환

|===


== 전환 작업을 관리하는 명령입니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
주어진 프로젝트 및 작업에서 실행되었거나 실행 중인 작업을 나열합니다
 a| 
전환 일자리



 a| 
작업의 상태를 봅니다
 a| 
전직상태



 a| 
작업 결과를 봅니다
 a| 
전직결과

|===


== 전환 일정을 관리하는 명령입니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
대역폭과 함께 SnapMirror 전송을 관리하는 일정을 추가합니다
 a| 
"CBT 일정 추가"



 a| 
프로젝트의 SnapMirror 일정을 수정합니다
 a| 
CBT의 전환 일정이 수정된다



 a| 
프로젝트에서 SnapMirror 일정을 제거합니다
 a| 
CBT 일정 제거



 a| 
프로젝트의 SnapMirror 일정을 모두 나열합니다
 a| 
CBT의 전환 일정이 표시됩니다

|===


== 툴 로그를 수집하는 명령입니다

|===
| 원하는 작업 | 이 명령 사용... 


 a| 
7-Mode Transition Tool 로그의 로그 파일을 수집하면 7-Mode Transition Tool 설치 경로의 'ASUP' 디렉토리에 서버가 저장됩니다.
 a| 
전환 번들-툴-로그

|===
이러한 명령에 대한 자세한 내용은 7-Mode Transition Tool CLI의 man 페이지를 참조하십시오.

* 관련 정보 *

xref:task_transitioning_volumes_using_7mtt.adoc[7-Mode 볼륨에서 데이터 및 구성 마이그레이션]
