---
permalink: copy-based/reference_ignorable_errors_during_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, ignorable, errors 
summary: 전환 중에 다소 무 난한 오류가 발생할 수 있습니다. 전환을 계속하기 전에 이러한 오류를 확인해야 합니다. 
---
= 전환 중에 오류가 발생합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환 중에 다소 무 난한 오류가 발생할 수 있습니다. 전환을 계속하기 전에 이러한 오류를 확인해야 합니다.

7-Mode 전환 툴 CLI를 사용하여 복사 기반 전환 프로젝트에 ignorable error 범주를 추가하면 오류가 미치는 영향을 잘 알고 있는 것입니다. 오류를 무시하고 전환 작업을 다시 실행해야 합니다. 이때 차단 오류는 경고 메시지로 바뀌고 오류는 ""확인됨""으로 표시됩니다. 경고로 전환을 계속할 수 있습니다.

|===
| 범주 | 설명 


 a| 
'인식번호-비아시치-파일 이름-소스-볼륨'
 a| 
이 오류를 승인한다는 것은 관리 대상 확인 작업 체인(Chain of Custody verification) 작업에 대해 선택한 SnapLock 볼륨에 ASCII가 아닌 문자가 있는 파일 이름이 포함되어 있지 않음을 확인했음을 의미합니다.



 a| 
'ACKNOWLEDGE-SnapLock-CoC-volume-autosit-period'
 a| 
이러한 ignorable 오류가 프로젝트에 추가되면 7-Mode Transition Tool은 SnapLock Chain of Custody 검증 결과를 저장하도록 구성된 ONTAP SnapLock 볼륨에 autostroit Period 속성이 설정되어 있어도 전환을 계속합니다.



 a| 
NFS-Qtree-익스포트됨
 a| 
이 오류를 확인하면 7-Mode에서 작동하는 Data ONTAP와 ONTAP 간에 qtree 엑스포트 규칙을 적용하는 차이점을 이해했음을 의미합니다. 이는 또한 7-Mode 전환 툴에서 NFS 엑스포트 규칙을 적용한 후 필요한 수동 단계를 이해했음을 의미합니다. https://["7MTT 사전 점검 10111 - qtree 레벨의 내보내기가 있는 7-Mode 볼륨을 전환하는 방법"]



 a| 
'ignore-cifs-ad-domain-mismatch'
 a| 
이 오류를 인식하면 7-Mode 시스템의 CIFS AD(Active Directory) 도메인이 타겟 SVM의 CIFS AD 도메인과 다른 경우에도 7-Mode 전환 툴이 CIFS 구성을 계속 전환합니다. 7-Mode 시스템의 CIFS AD 도메인과 타겟 SVM이 신뢰할 수 있는 도메인인지 확인해야 합니다. 그렇지 않으면 CIFS 구성을 타겟 SVM으로 전환할 수 없습니다. https://["7-Mode에서 CIFS 서버의 Active Directory 도메인과 타겟 SVM이 다를 때 CIFS 구성을 전환하는 방법"]



 a| 
'ignore-ping-check-from-IC-lifs-to-7mode'
 a| 
이러한 ignorable 오류가 프로젝트에 추가되더라도 7-Mode Transition Tool은 타겟 클러스터 인터클러스터 LIF에서 7-Mode 스토리지 시스템을 ping하는 검사를 실행하지 않습니다.https://["7MTT 복사 기반 전환 - 타겟 클러스터 인터클러스터 LIF에서 7-Mode 데이터 복사 IP 주소에 연결할 수 없는 시나리오를 처리하는 방법"]



 a| 
'ignore-secondary-snapmirror-source-check
 a| 
7-Mode Transition Tool은 이 ignorable error를 프로젝트에 추가한 후, 필요한 운영 7-Mode 세부 정보가 모두 2차 프로젝트에 추가되는지 여부를 확인하지 않습니다. 이 오류 때문에 7-Mode 전환 툴에서는 2차 프로젝트 완료(컷오버) 작업 중에 운영 7-Mode 볼륨과 2차 클러스터 볼륨 간의 SnapMirror 관계를 생성하지 못할 수 있습니다.



 a| 
'ignore-configuration-limits-check
 a| 
이 옵션을 사용하여 구성 제한(사전 검사 오류)을 확인하고 전환을 계속할 수 있습니다. 이 오류를 확인하면 스토리지 컷오버 시간이 3~8시간 이상이 걸릴 것으로 예측됩니다. 여기에는 엑스포트, 중지 및 임포트 작업(자동 운영), 디스크 쉘프를 새 컨트롤러에 연결하는 데 걸리는 시간도 포함됩니다. https://["Copy-Free Transition에 대한 스토리지 컷오버 시간 고려 사항"]



 a| 
'Mount-snaplock-volumes-using-7mode-volume-name'을 선택합니다
 a| 
7-Mode Transition Tool은 이러한 ignorable error를 프로젝트에 추가한 후 SnapLock 볼륨을 마운트 경로 '/<7-mode-volume-name>'에 마운트합니다



 a| 
''SnapLock-audit-to-MCC'''
 a| 
이러한 ignorable 오류가 프로젝트에 추가되면 타겟 클러스터가 MetroCluster 구성에 있더라도 7-Mode 전환 툴이 계속됩니다.

|===