---
permalink: copy-based/task_completing_a_transition_project.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, complete, project 
summary: 개별 프로젝트를 완료하여 전이를 완료할 수 있습니다. 이 작업은 중단이 발생하기 때문에 언제 실행해야 하는지 평가해야 합니다. SnapMirror 관계에서 볼륨을 전환할 때 기본 프로젝트의 전환을 완료하기 전에 보조 프로젝트를 완료해야 합니다. 
---
= 전환 프로젝트 완료
:icons: font
:imagesdir: ../media/


[role="lead"]
개별 프로젝트를 완료하여 전이를 완료할 수 있습니다. 이 작업은 중단이 발생하기 때문에 언제 실행해야 하는지 평가해야 합니다. SnapMirror 관계에서 볼륨을 전환할 때 기본 프로젝트의 전환을 완료하기 전에 보조 프로젝트를 완료해야 합니다.

스토리지 컷오버가 몇 분 이내에 완료됩니다. 클라이언트가 데이터를 다시 마운트하는 데 필요한 시간은 다양합니다. 스토리지 컷오버 또는 운영 중단 시간의 타이밍은 다음 요소에 따라 달라집니다.

* 최종 업데이트
+
데이터의 최종 업데이트는 마지막 업데이트 이후 원본 데이터의 변경 양에 따라 달라집니다. 증분적 전송은 컷오버 중에 전송해야 하는 데이터 양을 최소화합니다.

* 클라이언트를 다시 연결하는 중입니다
+
각 클라이언트가 클러스터에 연결하기 위해 업데이트가 필요한 경우 업데이트해야 하는 클라이언트 수에 따라 컷오버 시간이 결정됩니다.



운영 중단은 마이그레이션 중인 볼륨에만 적용됩니다. 전체 소스 7-Mode 스토리지 시스템을 종료할 필요가 없습니다. 마이그레이션되지 않는 소스 시스템의 볼륨은 온라인 상태로 유지되고 액세스할 수 있습니다.

. 마이그레이션 대시보드에서 완료할 프로젝트를 선택합니다.
. 수동으로 클라이언트 액세스 연결을 끊습니다.
. Complete Transition * 을 클릭합니다.
+
.. 전환 후 7-Mode 소스 볼륨을 온라인 상태로 유지하려면 * 전환 후 소스 볼륨을 오프라인으로 전환 * 확인란의 선택을 취소합니다.
+
기본적으로 이 옵션이 선택되어 있으며 소스 볼륨이 오프라인 상태가 됩니다.

.. 체인 보호 검증을 위해 SnapLock 볼륨을 선택한 경우, 전환 후 SnapLock 볼륨을 온라인 상태로 유지하려면 체인 보호 검증 * 동안 7-Mode SnapLock 볼륨을 오프라인으로 전환하지 않는다는 사실을 이해합니다.
.. ONTAP 9.3 이상 지원되는 릴리즈를 실행 중인 클러스터 간에 SnapMirror 관계 전환을 선택한 경우, SnapMirror 관계 유형을 data_protection에서 extended_data_protection * 으로 수동으로 변환해야 한다는 점을 * 이해했습니다. 확인란을 선택합니다.
.. SnapMirror 데이터 복사 작업의 수와 스로틀 제한을 지정하려면 * 이 작업에 대한 동시 SnapMirror 전송 수 및 스로틀 제한 사용자 지정 * 확인란을 선택합니다.
.. 계속 * 을 클릭합니다.


+
컷오버 작업의 결과가 표시됩니다.



전환을 위해 선택한 7-Mode IP 주소는 7-Mode 스토리지 시스템에서 구성되지 않은 상태이며, 전환을 위해 생성된 관련 LIF가 관리 상태로 전환됩니다. 7-Mode 볼륨이 오프라인 상태입니다.

클러스터에서 vserver check lif-multidenancy run 명령을 실행하여 전환된 LIF를 사용하여 이름 서버에 연결할 수 있는지 확인하십시오.


NOTE: 새 LIF를 생성한 경우, 모든 프로젝트를 완료한 후 새로운 IP 주소 및 포트를 사용하여 전환된 볼륨의 사용자 및 애플리케이션을 드라이브에 다시 매핑해야 합니다.

ONTAP 9.3 이상의 지원되는 릴리즈를 실행 중인 클러스터 간에 SnapMirror 관계가 전환되면 SnapMirror 관계를 DP 유형에서 XDP 유형으로 변환해야 합니다.

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-dap/home.html["데이터 보호"]

* 관련 정보 *

xref:concept_guidelines_for_deciding_when_to_cutover.adoc[컷오버 수행 시기를 결정하기 위한 지침]
