---
permalink: copy-based/task_creating_a_transition_project.html 
sidebar: sidebar 
keywords: create, transition, project, ontap, copy, based, transition 
summary: '전환 프로젝트를 만들려면 7-Mode 볼륨을 선택하여 SVM(스토리지 가상 머신)에 매핑하고, 인터페이스를 매핑하고, SnapMirror 관계를 위한 데이터 복사본 일정을 만들어야 합니다.' 
---
= 전이 프로젝트 작성
:icons: font
:imagesdir: ../media/


[role="lead"]
전환 프로젝트를 만들려면 7-Mode 볼륨을 선택하여 SVM(스토리지 가상 머신)에 매핑하고, 인터페이스를 매핑하고, SnapMirror 관계를 위한 데이터 복사본 일정을 만들어야 합니다.

클러스터에서 필요한 SVM을 생성해야 합니다.

프로젝트 내의 모든 볼륨은 동일한 SVM으로 마이그레이션됩니다. 볼륨을 다른 SVM으로 마이그레이션하려면 여러 프로젝트를 생성해야 합니다.

타겟 클러스터에서 Data ONTAP 8.3.1 이전 버전이 실행되고 있고 NAS 볼륨의 읽기/쓰기 모드에서 사전 컷오버 작업을 실행하려면 NAS 볼륨 및 SAN 볼륨에 대해 별도의 프로젝트를 생성해야 합니다. 프로젝트에 SAN 볼륨이 있는 경우 사전 컷오버 읽기/쓰기 모드가 지원되지 않으므로 이 작업이 필요합니다.

프로젝트에 SnapLock Compliance 볼륨이 포함되어 있고 비 SnapLock Compliance 볼륨에 대해 읽기/쓰기 모드에서 사전 컷오버 작업을 실행하려면 SnapLock Compliance 볼륨 및 비 SnapLock Compliance 볼륨에 대해 별도의 프로젝트를 생성해야 합니다. 프로젝트에 SnapLock 규정 준수 볼륨이 있는 경우 사전 컷오버 읽기/쓰기 모드가 지원되지 않기 때문에 이 작업이 필요합니다.

.단계
. 홈페이지에서 * Copy-Based Transition * 마이그레이션 방법을 선택한 다음 * Start Planning * 을 클릭합니다.
+
새 프로젝트에 필요한 컨트롤러 및 클러스터를 추가하지 않은 경우 장치 자격 증명 입력 창에 세부 정보를 입력할 수 있습니다.

. 7-Mode 시스템에서 작동하는 필수 Data ONTAP와 ONTAP 시스템이 모두 도구에 추가되었는지 확인한 후 * 다음 * 을 클릭합니다.
+
소스 볼륨 선택 페이지가 나타납니다.

. 전환할 7-Mode 볼륨을 선택합니다.
+
.. 7-Mode 컨트롤러 창에서 볼륨을 추가할 7-Mode 컨트롤러 또는 vFiler 유닛을 선택합니다.
.. 프로젝트 그룹에 포함할 볼륨을 추가합니다.
+
|===
| 전환을 원하는 경우... | 그러면... 


 a| 
독립 실행형 볼륨
 a| 
전환할 볼륨에 대해 * Transition as 독립 실행형 * 를 선택합니다.

이 열에서 첫 번째 볼륨을 선택하면 독립 실행형 프로젝트가 생성됩니다.



 a| 
volume SnapMirror 관계
 a| 
... 모든 운영 볼륨에 대해 * Transition with SnapMirror Relationship * 을 선택합니다.
+
2개의 프로젝트, 즉 운영 볼륨과 2차 프로젝트를 위한 1차 프로젝트가 생성됩니다.

... * 선택 사항: * 프로젝트에 보조 컨트롤러가 포함되어 있지 않은 경우 추가 스토리지 시스템 자격 증명 필요 대화 상자에 컨트롤러 세부 정보를 입력합니다.


|===
+
볼륨에 LUN이 하나 이상 있으면 볼륨 유형이 SAN으로 표시됩니다.

+
볼륨 이름에 제공된 하이퍼링크를 사용하면 볼륨의 qtree 및 LUN과 그 속성을 나열하는 대화 상자가 열립니다.

+

TIP: 단일 프로젝트 내의 모든 볼륨을 동일한 정의(독립 실행형, 운영 또는 2차)로 갖는 것이 좋습니다. 예를 들어, 프로젝트에는 독립 실행형 볼륨과 SnapMirror 관계를 혼합하지 않고 모든 독립 실행형 볼륨이 포함되어야 합니다.

.. 프로젝트에 포함할 볼륨을 모두 선택한 후 * 프로젝트 생성 및 계속 * 을 클릭하고 나타나는 대화 상자에서 프로젝트 이름 및 프로젝트 그룹 세부 정보를 입력한 다음 * 저장 * 을 클릭하여 프로젝트를 만듭니다.


. SnapMirror 데이터 복사본에 사용할 7-Mode IP 주소 및 다중 경로 IP 주소를 선택합니다.
+
.. 7-Mode 데이터 복사 IP 주소를 입력합니다.
+
기본적으로 이 필드는 7-Mode 시스템의 관리 IP 주소로 미리 채워집니다. 필요한 경우 데이터 복사 권한이 있는 유효한 IPv4 주소로 이 IP 주소를 변경할 수 있습니다.

.. 데이터 전송 로드 밸런싱을 위해 여러 경로를 사용하려면 IP 구성 창에 IP 주소를 입력한 후 * 다음 * 을 클릭합니다.


. Select SVM 페이지에서 타겟 클러스터와 SVM을 선택하고 다음 단계를 따릅니다.
+
.. Clustered Data ONTAP 시스템 선택 드롭다운 목록에서 클러스터 이름을 클릭하여 타겟 클러스터를 선택합니다.
+
SVM은 Select SVM 창에 로드됩니다.

.. Select SVM 창에서 볼륨을 전환할 대상 SVM을 선택합니다.
.. 다음 * 을 클릭합니다.


+
MetroCluster에서 7-Mode 볼륨을 ONTAP 구성으로 전환하려면 SVM 하위 유형이 '동기화 소스'여야 합니다.

+
+ clustered Data ONTAP 8.2에 속하는 SVM을 선택하면 7-Mode 스토리지 시스템에서 로컬 사용자 및 그룹 또는 CIFS 공유 또는 파일이 구성되었는지 여부를 확인하는 대화 상자가 표시됩니다. 7-Mode 전환 툴은 로컬 사용자 및 그룹을 clustered Data ONTAP 8.2로 전환하는 기능을 지원하지 않습니다. 로컬 사용자 및 그룹이 있는 경우 ONTAP 8.2.1 이상 지원되는 릴리즈에 속한 SVM을 선택할 수 있습니다.

. SVM 감사 로그 대상 경로 대화 상자에서 대상 SVM에 경로를 입력하여 7-Mode 스토리지 시스템에서 감사 구성을 전환할 수 있습니다.
+
이 경로는 ONTAP 시스템에 감사 로그를 저장하는 데 사용됩니다.

. Map Volumes 페이지에서 전환할 타겟 볼륨을 선택하여 각 소스 볼륨을 필요한 애그리게이트로 매핑합니다.
+
.. Map Origin Volumes to Aggregate on Target Cluster 창에서 7-Mode 볼륨을 복사해야 하는 애그리게이트를 선택합니다.
.. 클러스터에서 타겟 볼륨의 이름을 변경하려면 * Target Volume * (타겟 볼륨 *) 필드에 다른 이름을 입력합니다.
.. 다음 * 을 클릭합니다.


+
프로젝트에 포함된 모든 볼륨과 qtree가 NFS 요청만 지원하도록 구성되어 있는 경우 감사 구성이 전환되지 않으므로 감사 경로를 제공할 필요가 없습니다. 감사 경로를 제공한 경우에도 이 입력은 무시됩니다.

. 네트워크 구성 창에서 SVM에서 생성해야 하는 LIF에 대한 정보를 제공합니다.
+

NOTE: FC 및 iSCSI LIF는 전환할 수 없습니다. SVM에서 수동으로 생성해야 합니다.

+
|===
| 원하는 작업 | 그러면... 


 a| 
기존 7-Mode IP 주소를 전환합니다
 a| 
.. 7-Mode LIF * 선택을 클릭합니다.
.. 필요한 7-Mode IP 주소를 선택하고 타겟 노드 및 타겟 포트 세부 정보를 제공합니다.
.. 저장 * 을 클릭합니다.




 a| 
새 LIF를 생성합니다
 a| 
.. 새 LIF 추가 * 를 클릭합니다.
.. 표시되는 대화 상자에서 새 LIF의 세부 정보를 입력합니다.
.. 저장 * 을 클릭합니다.


|===
+
성공적인 전환 후 네트워크 연결을 제공하려면 7-Mode IP 주소를 ONTAP의 비슷한 네트워크 토폴로지로 전환해야 합니다. 예를 들어, 7-Mode IP 주소가 물리적 포트에 구성되어 있는 경우 IP 주소를 ONTAP의 적절한 물리적 포트로 전환해야 합니다. 마찬가지로, VLAN 포트 또는 인터페이스 그룹에 구성된 IP 주소는 ONTAP의 적절한 VLAN 포트 또는 인터페이스 그룹으로 전환되어야 합니다.

. 필요한 IP 주소를 모두 추가한 후 * 다음 * 을 클릭합니다.
. 일정 구성 페이지에서 기본 및 증분 전송의 데이터 복사본 일정, 동시 볼륨 SnapMirror 전송 수 및 전환을 위한 SnapMirror 전송 임계치 제한을 구성합니다.
+
DR 및 전환 데이터 복사 작업을 효과적으로 관리하기 위한 데이터 복사 일정과 임계치 제한을 제공할 수 있습니다. 각 프로젝트에 대해 최대 7개의 일정을 사용하여 여러 일정을 만들 수 있습니다. 예를 들어 평일과 주말을 위한 사용자 지정 일정을 만들 수 있습니다.

+

NOTE: 스케줄은 소스 7-Mode 컨트롤러 시간대를 기반으로 합니다.

+
.. 일정 구성 창에서 * 일정 생성 * 을 클릭합니다.
.. 데이터 복사본 일정 만들기 대화 상자에서 새 일정의 이름을 입력합니다.
.. 되풀이 일 창에서 * 매일 * 또는 * 일 * 선택 * 을 선택하여 데이터 복사 작업을 실행할 요일을 지정합니다.
.. 시간 간격 창에서 데이터 전송의 * 시작 시간 * 및 * 기간 * 을 지정합니다.
.. 시간 간격 창에서 증분 전송의 * 업데이트 빈도 * 를 지정하거나 * 연속 업데이트 * 를 선택합니다.
+
연속 업데이트를 활성화하면 동시 SnapMirror 전송 가능 여부에 따라 최소 5분 지연으로 업데이트가 시작됩니다.

.. Transition Data Copy Operations 매개 변수(Volume SnapMirror 기반) 창에서 최대 동시 볼륨 SnapMirror 전송 수(런타임에 사용할 수 있는 SnapMirror 전송 백분율로 표시)와 스로틀 제한(프로젝트의 모든 볼륨에 대한 최대 대역폭)을 지정합니다.
+

NOTE: 필드에 제공되는 기본값은 권장 값입니다. 기본값을 변경할 때는 7-Mode SnapMirror 일정을 분석하고 제공하는 값이 이러한 일정에 영향을 미치지 않도록 해야 합니다.

.. Create * 를 클릭합니다.
+
새 스케줄이 전환 스케줄 창에 추가됩니다.

.. 필요한 모든 데이터 복사 일정을 추가한 후 * 다음 * 을 클릭합니다.


. 전환할 SnapLock 볼륨이 있는 경우 전환 후 관리 연속성 검증이 필요한 볼륨을 계획하십시오.
+
.. 보호체인 검증이 필요한 소스 SnapLock 볼륨을 선택합니다.
+
Chain of Custody 검증 프로세스는 읽기/쓰기 7-Mode SnapLock 볼륨에 대해서만 지원되며 읽기 전용 볼륨에는 지원되지 않습니다. 파일 이름이 ASCII 문자로 된 SnapLock 볼륨만 관리 대상 확인에 지원됩니다.

.. Chain of Custody 검증 작업 중에 생성된 지문 데이터를 저장하는 데 사용할 ONTAP 볼륨에 대한 세부 정보를 제공합니다.
+
ONTAP 볼륨이 지정된 SVM에 이미 존재해야 합니다.

.. 다음 * 을 클릭합니다.




* 관련 정보 *

xref:concept_guidelines_for_creating_a_data_copy_schedule.adoc[데이터 복사 스케줄을 생성할 때의 고려 사항]

xref:task_creating_schedule_for_snapmirror_transfers.adoc[SnapMirror 전송을 위한 데이터 복사본 일정 생성]

xref:concept_managing_snapmirror_transfers_and_schedule.adoc[SnapMirror 전송 및 일정 관리]

xref:task_transitioning_volumes_by_excluding_a_subset_of_configurations.adoc[CLI를 사용하여 7-Mode 구성의 전환 사용자 지정]

xref:task_managing_logical_interfaces.adoc[논리 인터페이스 관리]

xref:task_removing_volumes_from_a_project.adoc[프로젝트에서 볼륨을 제거하는 중입니다]
