---
permalink: copy-based/task_creating_schedule_for_snapmirror_transfers.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, create, data, copy, schedule, snapmirror, transfer 
summary: 데이터 복사 일정을 생성하여 프로젝트의 볼륨에 대한 전환 데이터 복사 작업을 효과적으로 관리할 수 있습니다. 또한 해당 스케줄 중에 실행될 동시 SnapMirror 전송 수를 지정하여 동시 SnapMirror 전송이 최대 제한에 도달하여 복제 작업이 실패하지 않도록 할 수 있습니다. 
---
= SnapMirror 전송을 위한 데이터 복사본 일정 생성
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 복사 일정을 생성하여 프로젝트의 볼륨에 대한 전환 데이터 복사 작업을 효과적으로 관리할 수 있습니다. 또한 해당 스케줄 중에 실행될 동시 SnapMirror 전송 수를 지정하여 동시 SnapMirror 전송이 최대 제한에 도달하여 복제 작업이 실패하지 않도록 할 수 있습니다.

* 프로젝트는 준비, 데이터 복사 또는 구성 적용(사전 컷오버) 단계에 있어야 합니다.
* 7-Mode Transition Tool 서비스가 항상 실행 중이어야 일정을 효과적으로 예약할 수 있습니다.



NOTE: 데이터 복제 일정은 SnapMirror 기본 복제, 업데이트 및 재동기화 작업에 사용됩니다.

* 각 프로젝트에 대해 하나 이상의 데이터 복사 일정을 만들어야 합니다.
* 프로젝트당 최대 7개의 일정을 만들 수 있지만 프로젝트 내에서 일정이 겹칠 수는 없습니다.
+
예를 들어 업무 시간 및 업무 외 시간, DR 시간 및 DR 이외 시간, 평일 및 주말 에 대해 사용자 지정된 일정을 생성할 수 있습니다.

+

NOTE: 프로젝트에서 동일한 7-Mode 컨트롤러 또는 클러스터를 사용하는 경우 데이터 복사 일정이 다른 프로젝트에 겹치지 않도록 해야 합니다.

* 구성된 일정은 7-Mode 컨트롤러의 시간대에 따라 적용됩니다.
* 일정 중에 사용할 동시 SnapMirror 전송 수는 사용할 동시 SnapMirror 스트림의 비율과 구성된 최대 한도를 기준으로 런타임에 결정됩니다.
* 일정에 따라 지정된 SnapMirror 전송을 사용하는 툴 때문에, 기존 7-Mode DR 일정에 영향을 주지 않는 방식으로 SnapMirror를 동시에 전송할 수 있어야 합니다.
* 툴에서 사용 중인 동시 SnapMirror 전송 수가 예약 중에 사용할 동시 SnapMirror 전송 수보다 적은 경우 툴에서 새 전송 일정을 예약하여 나머지 전송을 사용합니다.
* 일정이 끝나거나 7-Mode 스토리지 시스템에서 동시 SnapMirror 전송 수가 감소한 경우, 이 도구는 추가 전송을 중단하여 언제든지 구성된 전송 수만 사용하도록 합니다.
+

NOTE: 베이스라인이 진행 중이고 스냅샷 체크포인트가 아직 생성되지 않은 경우 이 툴은 전송을 중단하지 않고 스냅샷 체크포인트가 생성될 때까지 대기한 다음 전송을 중단합니다.



.단계
. 대시보드의 데이터 복사 일정 페이지에서 * 프로젝트 편집 * 을 클릭한 다음 * 일정 구성 * 을 선택하여 일정을 만듭니다.
. 새 스케줄의 이름을 입력합니다.
. 되풀이 일 창에서 데이터 복사 작업을 실행할 요일을 선택합니다.
+
|===
| 데이터 복사 작업을 실행하려면... | 그러면... 


 a| 
매일
 a| 
매일 * 을 선택합니다. 이 값이 기본값입니다.



 a| 
특정 일에만 적용됩니다
 a| 
.. 일 선택 * 을 선택합니다.
.. 요일을 선택합니다.


|===
. 시간 간격 창에서 데이터 복사 스케줄의 시작 시간, 기간 및 빈도를 지정합니다.
+
.. Start Time * (시작 시간 *) 드롭다운 목록에서 시간과 분을 선택하여 데이터 복사 작업을 시작할 시간을 입력합니다.
+
유효한 값은 00:00부터 23:30까지입니다.

.. 데이터 복사 작업을 실행할 기간을 입력하고 * Duration * (기간 *) 드롭다운 목록에서 시간과 분을 선택합니다.
+

NOTE: 일정 기간은 1주(167시간 30분)를 초과할 수 없습니다.

+
예를 들어, 20:30이 지정된 경우 SnapMirror 작업이 시작 시간에서 20시간 30분 동안 실행됩니다.

.. 다음 중 하나를 수행하여 베이스라인 전송이 완료된 후 (생성된 일정 기간 내에) 증가분 전송을 수행해야 하는 빈도를 선택합니다.
+
*** 업데이트 빈도 * 드롭다운 목록에서 시간과 분을 선택합니다.
*** Continuous Updates * 를 선택합니다.
+
두 번의 연속 업데이트 사이의 최소 지연은 5분입니다.





+
기본적으로 SnapMirror 업데이트는 30분마다 실행됩니다.

. Transition Data Copy Operations 매개 변수 창에서 SnapMirror 매개 변수를 입력합니다.
+
.. 다음 중 하나 또는 모두를 수행하여 데이터 복사본에 사용해야 하는 최대 동시 SnapMirror 전송 수를 지정합니다.
+
*** 일정이 활성화된 경우 데이터 복사본에 사용할 수 있는 볼륨 SnapMirror 전송의 백분율을 * 최대 동시 VSM 전송 수 * 필드에 입력하여 지정합니다.
+
사용 가능한 volume SnapMirror 전송은 런타임에 계산됩니다.

+

NOTE: 플랫폼에서 지원되는 최대 동시 SnapMirror 전송 수가 이 창에 표시됩니다.

*** 이 일정 중에 실행할 수 있는 최대 동시 볼륨 SnapMirror 전송 수를 * 초과하지 않음 * 필드에 지정합니다. 두 값을 모두 입력하면 가장 낮은 값이 동시 전송 수로 사용됩니다.




+
전환에 사용되는 동시 전송 수는 스케줄 및 구성된 동시 전송 수에 따라 런타임에 계산됩니다.

+
+ 이 플랫폼은 최대 100개의 동시 볼륨 SnapMirror 전송을 지원하며, 현재 60개를 사용할 수 있으며 다음 값을 지정했습니다.

+
** 사용 가능한 볼륨 SnapMirror 전송 옵션의 비율은 50%입니다.
+
백분율 옵션을 기준으로 한 최대 동시 전송 수는 60 = 30의 50%입니다.

** 최대 동시 볼륨 SnapMirror 전송 수 옵션은 25입니다. 이 시나리오에서는 이 툴에서 두 값 중 가장 낮은 동시 볼륨 SnapMirror 전송 수를 25로 설정합니다.
+
... 다음 중 하나를 수행하여 최대 대역폭을 MB/s(스로틀)로 지정합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
사용 가능한 모든 대역폭을 활용합니다
 a| 
최대 * 를 선택합니다. 이 값이 기본값입니다.



 a| 
스로틀 값을 지정합니다
 a| 
값을 * 초과하지 않음 * 필드에 입력합니다. 최대 허용 입력 값은 4194303입니다.

를 누릅니다

|===
+
스로틀 값은 프로젝트의 모든 활성 전송 간에 균등하게 분배됩니다.

+

NOTE: 각 전송의 스로틀은 사용 가능한 동시 볼륨 SnapMirror 전송 수에 따라 런타임에 결정됩니다.

+
활성 스케줄이 임계치 값이 200Mbps로 구성되고 동시 전송 수가 10개만 사용 가능한 경우 각 전송에는 20Mbps의 대역폭이 사용됩니다.







일정은 프로젝트가 데이터 복사 또는 구성 적용(사전 컷오버) 단계에 있을 때만 유효합니다.



== 데이터 복사 스케줄 계획 예

75개의 DR 관계와 함께 100개의 동시 SnapMirror 전송을 지원하는 7-Mode 컨트롤러를 고려해 보십시오. 비즈니스 요구 사항은 다음 시간 동안 SnapMirror 작업을 실행해야 합니다.

|===
| 일 | 시간 | 현재 SnapMirror 전송을 사용 중입니다 


 a| 
월요일부터 금요일까지
 a| 
오전 9:00 오후 5시까지
 a| 
50 % 사용 가능한 전송



 a| 
월요일부터 금요일까지
 a| 
오후 11시 30분 오전 2시 30분까지
 a| 
재해 복구에 75개 전송 사용



 a| 
월요일부터 금요일까지
 a| 
오전 2시 30분 오전 9:00까지 및

오후 5시 오후 11시 30분까지
 a| 
사용 가능한 전송 중 25%



 a| 
토요일부터 월요일까지
 a| 
오전 2시 30분 (토요일) - 오전 9:00 (월요일)
 a| 
10 % 사용 가능한 전송

|===
다음 데이터 복사본 일정을 생성하여 전환 데이터 복사 작업을 관리할 수 있습니다.

|===
| 스케줄 | 옵션을 선택합니다 | 값 


 a| 
peak_hours(피크 시간
 a| 
일 범위
 a| 
월요일부터 금요일까지



 a| 
시작 시간
 a| 
09:30



 a| 
기간
 a| 
8:00



 a| 
동시 전송 최대 수의 백분율입니다
 a| 
50



 a| 
최대 동시 전송 수입니다
 a| 



 a| 
스로틀(Mbps)
 a| 
100



 a| 
업데이트 빈도
 a| 
0:00



 a| 
dr_active입니다
 a| 
일 범위
 a| 
월요일부터 금요일까지



 a| 
시작 시간
 a| 
23:30



 a| 
기간
 a| 
3:00



 a| 
동시 전송 최대 수의 백분율입니다
 a| 



 a| 
최대 동시 전송 수입니다
 a| 
25



 a| 
스로틀(Mbps)
 a| 
200



 a| 
업데이트 빈도
 a| 
0:30



 a| 
non_peak_non_DR1
 a| 
일 범위
 a| 
월요일부터 금요일까지



 a| 
시작 시간
 a| 
17:00



 a| 
기간
 a| 
6:30



 a| 
동시 전송 최대 수의 백분율입니다
 a| 
75를



 a| 
최대 동시 전송 수입니다
 a| 



 a| 
스로틀(Mbps)
 a| 
300



 a| 
업데이트 빈도
 a| 
1:00



 a| 
non_peak_non_DR2
 a| 
일 범위
 a| 
월요일부터 금요일까지



 a| 
시작 시간
 a| 
오전 2시 30분



 a| 
기간
 a| 
6:30



 a| 
동시 전송 최대 수의 백분율입니다
 a| 
75를



 a| 
최대 동시 전송 수입니다
 a| 



 a| 
스로틀(Mbps)
 a| 
300



 a| 
업데이트 빈도
 a| 
1:00



 a| 
week_ends
 a| 
일 범위
 a| 
토요일



 a| 
시작 시간
 a| 
오전 2시 30분



 a| 
기간
 a| 
53:30



 a| 
동시 전송 최대 수의 백분율입니다
 a| 
90



 a| 
최대 동시 전송 수입니다
 a| 



 a| 
스로틀(Mbps)
 a| 
500입니다



 a| 
업데이트 빈도
 a| 
2:00

|===