---
permalink: copy-based/task_starting_baseline_data_copy.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, baseline, copy 
summary: 프로젝트를 생성하고 사전 점검 작업을 완료한 후에는 7-Mode 볼륨에서 ONTAP로 데이터 복사본을 초기화해야 합니다. 개별 프로젝트에 대한 기본 데이터 복사 작업을 시작할 수 있습니다. 데이터 복사 중에 불필요한 시스템 프로세스와 네트워크 작업을 중지해야 합니다. 
---
= 기본 데이터 복사를 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
프로젝트를 생성하고 사전 점검 작업을 완료한 후에는 7-Mode 볼륨에서 ONTAP로 데이터 복사본을 초기화해야 합니다. 개별 프로젝트에 대한 기본 데이터 복사 작업을 시작할 수 있습니다. 데이터 복사 중에 불필요한 시스템 프로세스와 네트워크 작업을 중지해야 합니다.

데이터 복사 일정을 하나 이상 만들어야 합니다.

테스트 마이그레이션을 수행하여 기본 전송을 완료하는 데 걸리는 시간을 예측하고 사용자 환경에서 volume SnapMirror 전송이 수행되어 달성된 성능을 평가할 수 있습니다. 다음은 성능에 영향을 미칠 수 있는 몇 가지 요소입니다.

* 전환 데이터 복사 스케줄 옵션이 선택되었습니다
+
이 일정은 SnapMirror 동시 전송의 최대 수와 전송에 사용할 최대 대역폭을 제어합니다.

* 7-Mode 소스 컨트롤러에서 지원되는 최대 동시 볼륨 SnapMirror 전송 수입니다
* 7-Mode 소스 컨트롤러와 ONTAP 대상 컨트롤러 간의 네트워크 대역폭
+
마이그레이션 작업과 관련이 없는 네트워크 트래픽을 최소화하여 처리량을 극대화하고 소스 시스템과 대상 시스템 간의 응답 시간을 최소화해야 합니다.

* 소스 및 타겟 컨트롤러의 성능 기능
+
소스 및 대상 시스템은 최적의 CPU 사용률 및 메모리를 사용할 수 있어야 합니다.

* 데이터 복사 중에 발생하는 7-Mode 볼륨 SnapMirror 전송 수입니다


.단계
. 대시보드에서 기본 데이터 복사본을 시작할 프로젝트를 선택합니다.
. 시작 기준선 * 을 클릭합니다.
+
사전 검사는 백그라운드에서 다시 한 번 실행되며, 오류가 발견되지 않으면 데이터 복사 일정에 따라 기본 전송이 시작됩니다. 작업 진행률 대화 상자에는 기본 데이터 복사 중에 실행된 사전 확인 작업의 상태에 대한 정보가 표시됩니다.

. 기본 전송의 상태 및 진행률을 보려면 * Volumes * (볼륨 *) 탭을 클릭합니다.
+
각 볼륨의 SnapMirror 세부 정보를 보려면 * 전환 세부 정보 보기 * 를 클릭합니다. 동시 SnapMirror 전송 수는 현재 활성 상태인 스케줄에 제공된 입력을 기반으로 합니다. 대시보드의 데이터 복사 일정 탭에서 활성 일정을 추적할 수 있습니다.

+
기본 데이터 복사 작업이 완료되면 프로젝트를 생성하는 동안 제공된 일정에 따라 증분 SnapMirror 업데이트가 시작됩니다.



* 관련 정보 *

xref:task_creating_schedule_for_snapmirror_transfers.adoc[SnapMirror 전송을 위한 데이터 복사본 일정 생성]
