---
permalink: copy-based/task_preparing_cluster_for_transition.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, prepare, cluster 
summary: 전환하기 전에 클러스터가 HTTPS 허용, LIF 설정, 전환을 위한 네트워크 연결 확인 등의 요구사항을 충족하는지 확인해야 합니다. 
---
= 클러스터를 전환 준비 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환하기 전에 클러스터가 HTTPS 허용, LIF 설정, 전환을 위한 네트워크 연결 확인 등의 요구사항을 충족하는지 확인해야 합니다.

* 클러스터와 SVM이 이미 설정되어 있어야 합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ssg/home.html["소프트웨어 설정"]

+
타겟 SVM이 SVM 재해 복구 관계에 있을 수 없습니다.

* 클러스터가 정상 상태여야 하며 테이크오버 모드 상태인 노드는 없어야 합니다.
* 전환된 볼륨을 포함할 타겟 애그리게이트에는 SFO 정책이 있어야 합니다.
* 애그리게이트는 최대 볼륨 제한에 도달하지 않은 노드에 있어야 합니다.
* 7-Mode 시스템의 32비트 애그리게이트에서 Data ONTAP 8.2.x 클러스터의 64비트 애그리게이트로 볼륨을 이전하려면 대상 애그리게이트에 5%의 공간을 추가로 제공해야 합니다.
+
전환된 볼륨을 64비트 형식으로 업그레이드하려면 추가 공간이 필요합니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"]

* 볼륨 SnapMirror 관계를 전환할 때 SVM 피어 관계를 설정할 경우 다음 조건을 충족해야 합니다.
+
** 2차 클러스터에는 1차 SVM과 동일한 이름의 SVM이 있으면 안 됩니다.
** 운영 클러스터에는 2차 SVM과 동일한 이름의 SVM이 있으면 안 됩니다.
** 소스 7-Mode 시스템의 이름은 이미 피어링된 로컬 SVM 또는 SVM과 충돌해서는 안 됩니다.




전환 중에 클러스터를 다른 ONTAP 버전으로 업그레이드해서는 안 됩니다.


NOTE: 필요한 경우 클러스터를 동일한 ONTAP 버전의 패치 릴리즈로 업그레이드할 수 있습니다.

.단계
. 관리 호스트에서 클러스터 관리 LIF를 사용하여 클러스터에 연결할 수 있는지 확인합니다.
+
' * ssh_username@cluster_mgmt_ip_ *'

. 클러스터에서 SSLv3 또는 FIPS 사용:
+
|===
| 을(를) 활성화하려면... | 입력... 


 a| 
SSLv3
 a| 
'* 시스템 서비스 웹 수정 - SSLv3 사용 가능 참 * '



 a| 
FIPS 140-2 규정 준수
 a| 
'* 시스템 서비스 웹 수정 - SSL-FIPS 지원 true*'

|===
+
FIPS 140-2 규정 준수를 활성화하면 SSLv3이 비활성화됩니다. ONTAP은 FIPS 140-2 규정 준수를 활성화한 경우 SSLv3을 활성화하지 못하도록 합니다. FIPS 140-2를 사용하도록 설정한 후 이를 사용하지 않도록 설정하는 경우 SSLv3은 비활성화 상태로 유지됩니다.

+

IMPORTANT: 모범 사례는 SSLv3의 보안 취약점 때문에 FIPS를 사용하는 것입니다.

. 클러스터 관리 LIF에서 HTTPS가 허용되는지 확인합니다.
+
.. 클러스터 관리 LIF의 방화벽 정책을 확인합니다.
+
'* 네트워크 인터페이스 show -vserver_svm_name_-lif_cluster_mgmt_lif_-fields firewall firewall -policy *

+
[listing]
----
cluster1::> network interface show -vserver cluster1 -lif cluster_mgmt -fields firewall-policy
vserver lif          firewall-policy
------- ------------ ---------------
cluster1  cluster_mgmt mgmt
----
.. 클러스터 관리 LIF와 연결된 방화벽 정책에서 HTTPS 액세스를 허용하는지 확인합니다.
+
'* 시스템 서비스 방화벽 정책 show-policy mgmt * '

+
[listing]
----
cluster1::> system services firewall policy show -policy mgmt
Policy           Service    Action IP-List
---------------- ---------- ------ --------------------
mgmt
                 dns        allow  0.0.0.0/0, ::/0
                 http       allow  0.0.0.0/0, ::/0
                 https      allow  0.0.0.0/0, ::/0
                 ndmp       allow  0.0.0.0/0, ::/0
                 ntp        allow  0.0.0.0/0, ::/0
                 rsh        deny   0.0.0.0/0, ::/0
                 snmp       allow  0.0.0.0/0, ::/0
                 ssh        allow  0.0.0.0/0, ::/0
                 telnet     deny   0.0.0.0/0, ::/0
9 entries were displayed.
----


+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["시스템 관리"]

. 클러스터와 7-Mode 시스템 간의 통신을 위해 클러스터의 각 노드에 대한 인터클러스터 LIF를 생성합니다.
+
.. '* 네트워크 인터페이스 create-vserver_svm_name_-lif_lif_-role s인터클러스터 -home-node_home_node_-home-port_home_port_-address_ip_address_-netmask_netmask_*'
+
[listing]
----
cluster1::> network interface create -vserver cluster1-01 -lif intercluster_lif -role intercluster -home-node cluster1-01 -home-port e0c -address 192.0.2.130 -netmask 255.255.255.0
----
.. 정적 배관을 작성합니다.
+
|===
| 전환 대상: | 이 명령 실행... 


 a| 
ONTAP 9.5 또는 clustered Data ONTAP 8.3.x
 a| 
네트워크 경로를 생성합니다

[listing]
----
cluster1::> network route create -vserver vs0 -destination 0.0.0.0/0 -gateway 10.61.208.1
----


 a| 
Clustered Data ONTAP 8.2.x의 경우
 a| 
네트워크 라우팅 - 그룹 라우트가 생성됩니다

[listing]
----
cluster1::> network routing-groups route create -vserver cluster1-01 -routing-group i192.0.0.0/18 -destination 0.0.0.0/0 - gateway 192.0.2.129
----
|===
.. 인터클러스터 LIF를 사용하여 7-Mode 시스템에 ping을 수행할 수 있는지 확인합니다.
+
'* network ping-lif_인터클러스터_lif_-vserver_svm_name_-destination_remote_inetaddress_*'

+
[listing]
----
cluster1::> network ping -lif intercluster_lif -vserver cluster1 -destination system7mode
system7mode is alive
----
+
다중 경로의 경우 각 노드에 두 개의 인터클러스터 LIF가 있어야 합니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-nmg/home.html["네트워크 및 LIF 관리"]




