---
permalink: copy-based/task_starting_data_copy_for_a_transition_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, start, data, copy, project 
summary: 기본 전송을 위해 7-Mode 볼륨에서 ONTAP 볼륨으로 데이터 복사본을 시작할 수 있습니다. 프로젝트에 구성된 데이터 복사본 일정이 활성화되면 기본 전송이 시작됩니다. 기본 전송이 완료되면 ONTAP 볼륨은 데이터 복사 일정에 따라 정기적으로 업데이트됩니다. 
---
= 전이 프로젝트의 데이터 복사를 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본 전송을 위해 7-Mode 볼륨에서 ONTAP 볼륨으로 데이터 복사본을 시작할 수 있습니다. 프로젝트에 구성된 데이터 복사본 일정이 활성화되면 기본 전송이 시작됩니다. 기본 전송이 완료되면 ONTAP 볼륨은 데이터 복사 일정에 따라 정기적으로 업데이트됩니다.

* 프로젝트에 대한 사전 검사를 실행하고 모든 오류를 해결해야 합니다.
* 데이터 전송을 위해 소스와 대상 시스템 간에 지연 시간이 짧은 전용 고대역폭 네트워크를 구성해야 합니다.
+

NOTE: SnapMirror 다중 경로를 사용하여 두 경로 간에 데이터 전송 로드의 균형을 조정할 수 있습니다.

* 세션에 대해 데이터 복제 스케줄을 구성해야 합니다.


기존 SVM으로 전환하는 경우 이 작업 중에 볼륨이 생성됩니다. 새 SVM으로 전환하는 경우 이 작업 중에 SVM과 해당 볼륨이 생성됩니다.

SnapMirror 관계는 7-Mode와 ONTAP 볼륨 간에 생성됩니다.

.단계
. 데이터 복사 시작:
+
' * transition start -p_project_name_ * '

+
시작 작업이 실패하고 데이터 복사가 시작되지 않으면 문제를 해결하고 "transition start" 명령을 다시 실행해야 합니다.

+
[listing]
----
7-Mode Transition Tool>transition start -p project_finance

[1/17 ] Project status checks                                      [      Ok       ]
[2/17 ] Validating 7-Mode system information                       [      Ok       ]
[3/17 ] Validating 7-Mode volumes information                      [      Ok       ]
[4/17 ] Validating Cluster-Mode system information                 [      Ok       ]
[5/17 ] Validating Cluster-Mode volume information                 [      Ok       ]
[6/17 ] Validating LIF information                                 [ Notifications ]
[7/17 ] WAFL prechecks                                             [      Ok       ]
[8/17 ] UNIX users and groups prechecks                            [   Warnings    ]
[9/17 ] SnapMirror prechecks                                       [ Notifications ]
[10/17] NFS prechecks                                              [   Warnings    ]
[11/17] Networking prechecks                                       [ Notifications ]
[12/17] CIFS prechecks                                             [   Warnings    ]
[13/17] Name services prechecks                                    [   Warnings    ]
[14/17] SAN prechecks                                              [      Ok       ]
[15/17] Creating Cluster-Mode volumes                              [      Ok       ]
[16/17] Establishing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]
[17/17] Initializing SnapMirror relationships between the 7-Mode and Cluster-Mode volumes                                                            [      Ok       ]

Operation summary:
------------------
The 'start' operation is completed with warnings and notifications.

 0  Errors - No action required
22  Warnings - Need your attention!
16  Notifications - Please review
102  Informational messages

Do you want to see a detailed report {yes, no} [yes]:

22 Warnings:
------------
20362: Checking whether 7-Mode UNIX groups' names are in use in the Vserver 'vs2'.  [    Warning    ]
  > The following 7-Mode UNIX groups' names are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }

20372: Checking whether 7-Mode UNIX groups' ids are in use in the Vserver 'vs2'.    [    Warning    ]
  > The following 7-Mode UNIX groups' ids are already in use in the Vserver 'vs2'.
  > AFFECTED-OBJECTS: { daemon }
----
+
프로젝트가 복사-기준선 상태로 이동합니다. 초기 계획 전송이 완료되면 프로젝트가 복사본 업데이트 상태로 이동합니다.


