---
permalink: copy-based/task_creating_a_transition_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, create, project 
summary: 전환 프로젝트를 생성하여 7-Mode 오브젝트를 식별하고 이러한 객체가 ONTAP 오브젝트로 매핑되는 방법을 파악할 수 있습니다. 7-Mode 전환 툴은 프로젝트를 생성하는 동안 전환 개체에 대한 정보를 수집하고 저장합니다. 이 프로젝트 정보를 사용하여 단계별로 전환을 수행할 수 있습니다. 
---
= 전이 프로젝트 작성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환 프로젝트를 생성하여 7-Mode 오브젝트를 식별하고 이러한 객체가 ONTAP 오브젝트로 매핑되는 방법을 파악할 수 있습니다. 7-Mode 전환 툴은 프로젝트를 생성하는 동안 전환 개체에 대한 정보를 수집하고 저장합니다. 이 프로젝트 정보를 사용하여 단계별로 전환을 수행할 수 있습니다.

다음 정보를 수집해야 합니다.

* 프로젝트 형식: 가능한 값은 독립 실행형, 기본 또는 보조 값입니다
* MultiStore 라이센스가 있는 경우 7-Mode 스토리지 시스템 또는 기본 vFiler 유닛의 FQDN 또는 IP 주소입니다
* 7-Mode 스토리지 시스템의 관리 사용자 이름 및 암호입니다
* 7-Mode 볼륨 목록입니다
* 클러스터 관리 LIF의 FQDN 또는 IP 주소입니다
* SVM 이름


.단계
. 시작 * 메뉴에서 * 모든 프로그램 * > * NetApp 7-Mode 전환 툴 * > * NetApp 7-Mode 전환 툴(CLI) 3.0 * 을 클릭하여 7-Mode 전환 툴 명령 프롬프트를 엽니다.
. 전환 프로젝트의 일부인 시스템의 사용자 이름과 암호를 추가합니다.
+
' * 전이 자격 증명 add -h_host_name_-u_user_name_ * '

+
'_host_name_'은(는) 7-Mode 시스템 또는 클러스터의 FQDN 또는 IP 주소입니다.

+
'_user_name_'은(는) 시스템의 관리 사용자 이름입니다.

+

NOTE: 전환 프로젝트에 추가할 각 스토리지 시스템에 대해 이 단계를 반복해야 합니다.

+
[listing]
----
7-Mode Transition Tool>transition credentials add -h system1.example.com -u root
Enter password for 'root@system1.example.com':
----
. 전이 프로젝트 작성:
+
'* 전이 CBT create-p_project_name_-t_project_type_-n_7-Mode_system_-c_data-copy-ipaddress_[-f_vFiler_name_] [-h_cluster_-v_vserver_name_ * '

+
'_PROJECT_NAME_'은(는) 전이 프로젝트의 이름입니다.

+
'_PROJECT_TYPE_'은(는) 프로젝트 유형입니다. 유효한 값은 독립 실행형, 2차 또는 1차 값입니다.

+
'_7-Mode_system_'은 7-Mode 시스템의 FQDN 또는 IP 주소입니다.

+
'_cluster_'는 클러스터 관리 LIF의 IP 주소 또는 클러스터의 FQDN입니다.

+

NOTE: 7-Mode 시스템 및 클러스터의 호스트 이름은 프로젝트를 생성하는 동안 입력한 호스트 이름과 같아야 합니다.

+
'_data-copy-ipaddress_'는 데이터가 복사되는 IP 주소입니다.

+
'_vfiler_name_'은(는) 기본 vFiler 장치가 아닌 단위의 이름입니다.

+
'_vserver_name_'은 SVM의 이름입니다.

+

NOTE: 새 SVM의 경우 '-g' 옵션을 사용하여 SVM의 루트 볼륨의 애그리게이트 이름을 제공해야 합니다.

+
[listing]
----
7-Mode Transition Tool>transition cbt create -p sample_project -t standalone -n system1.example.com -n 10.238.55.33 -h cluster1.example.com -v vs2
----
+
전환 프로젝트가 준비 상태로 전환됩니다.

. 7-Mode 볼륨과 ONTAP 볼륨을 프로젝트에 추가합니다.
+
'* 전이 CBT 볼륨 에어에어 ADD-p_PROJECT_NAME_-v_7-Mode_VOLUME_-c_vserver_volume_-g_aggr_name_-t * '

+
'_7-Mode_volume_'은 7-Mode 볼륨 이름입니다.

+
'_vserver_volume_'은 SVM의 ONTAP 볼륨입니다.

+

NOTE: 기본 전송이 완료된 ONTAP 볼륨을 추가할 수도 있습니다. 준비 단계에서 이러한 볼륨을 추가할 경우 데이터 복사 단계에서는 증분 전송만 수행됩니다.

+
'_aggr_name_'은(는) 시작 작업 중에 ONTAP 볼륨 '_vserver_volume_'이(가) 생성되는 집계입니다.

+
'_-t_'는 SnapMirror 관계에 있는 볼륨을 독립 실행형 볼륨으로 전환해야 하는 경우에 사용됩니다.

+

NOTE: 볼륨이 독립 실행형 볼륨으로 전환되면 전환 중에 SnapMirror 관계가 유지되지 않습니다.

+
SnapMirror 관계에 있는 SnapLock 규정 준수 볼륨의 경우 7-Mode 전환 툴을 통해 SnapLock 규정 준수 볼륨의 SnapMirror 관계 전환을 자동화할 수 없습니다. SnapMirror 관계에 있는 모든 SnapLock 규정 준수 볼륨은 독립형, 운영 또는 2차 프로젝트에 볼륨을 포함하여(t 플래그를 지정하여) 독립 실행형 볼륨으로 전환되어야 합니다. 그런 다음 전환 후 이러한 볼륨 간에 SnapMirror 재동기화 작업을 수동으로 수행해야 합니다.

+
을 참조하십시오 xref:concept_considerations_for_transitioning_of_snaplock_compliance_volumes.adoc[SnapLock 규정 준수 볼륨의 전환을 위한 고려 사항]

+
[listing]
----
7-Mode Transition Tool>transition cbt volumepair add -p sample_project -v vol1 -c vol1 -g aggr1
----
. 프로젝트에 전환할 IP 주소를 추가합니다.
+
'* 전이 CBT lif add -p_project_name_-i_ip-address_[-m_netmask_] [-g_default-gateway_] [-p_home_port_] [-n_home_node_] *

+
전환 프로젝트에는 스토리지 컷오버 중에 7-Mode 시스템에서 구성되지 않거나 제거된 기존 IP 주소와 7-Mode 또는 ONTAP에 아직 구성되지 않은 새 IP 주소를 추가할 수도 있습니다.

+

NOTE: FC 및 iSCSI LIF는 7-Mode 전환 툴을 통해 전환되지 않습니다.

+
[listing]
----
7-Mode Transition Tool>transition cbt lif add -p sample_project -i 192.0.2.250 -m 255.255.255.128 -g 192.40.0.1 -p e0a -n cluster1-01
----
+
새 IP 주소는 적용 구성(precutover) 작업 중 가동 상태의 ONTAP 시스템에서 구성됩니다.

. 기본 프로젝트와 보조 프로젝트에 정보를 추가하려면 다음 단계를 따릅니다.
+
|===
| 에 대한 정보를 추가하려면... | 입력... 


 a| 
1차 7-Mode 시스템을 2차 프로젝트에 활용
 a| 
'* 전이 CBT add-primary-7-mode-system-p_project_name_-h_source-host_-f_management-ipaddress_-d_data-copy-ipaddress_[-m_multipathing-ipaddress_] *

자세한 내용은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/CBT_%3A_How_to_provide_all_the_required_primary_7-Mode_details_for_a_given_secondary_project["CBT: 특정 보조 프로젝트에 필요한 모든 기본 7-Mode 세부 정보를 제공하는 방법"].



 a| 
1차 프로젝트에 2차 클러스터 또는 SVM
 a| 
'* 전환 CBT add-secondary-cluster-mode-system-p_project_name_-h_c-mode-host-name_-v_vserver-name_ * '

자세한 내용은 를 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/CBT%3A_How_to_add_the_required_secondary_cluster_details_to_the_primary_project["CBT: 기본 프로젝트에 필요한 보조 클러스터 세부 정보를 추가하는 방법"]

|===
+
'_PROJECT_NAME_'은(는) 전이 프로젝트의 이름입니다.

+
보조 7-Mode 시스템의 '스냅샷 미러 상태' 명령 출력에 표시되는 운영 7-Mode 스토리지 시스템의 호스트 이름 또는 IP 주소입니다.

+
7-Mode 기본 시스템 정보를 제공할 때의 고려 사항은 man 페이지를 참조하십시오.

+
'_management-ipaddress_'는 소스 호스트의 관리 IP 주소입니다.

+
'_data-copy-ipaddress_'는 데이터가 복사되는 IP 주소입니다.

+
'_multipathing-ipaddress_'는 데이터 복사에 사용되는 추가 IP 주소입니다.

+
'_c-mode-host-name_'은 프로젝트의 보조 볼륨이 전환된 클러스터의 FQDN 또는 IP 주소입니다.

+
'_vserver-name_'은 보조 볼륨을 호스팅하는 SVM의 이름입니다.

. 데이터 복사 스케줄 생성:
+
'* 전이 CBT 스케줄 add -p_project_name_-n_schedule_name_-d_days -range_-b_start -time_-e_duration_-u_update -frequency_-t_available-transfers-percentage_-c_max-cap-concurrent-transfers_-x_project-SnapMirror-throttle_*'

+
다음 명령을 실행하면 사용 가능한 동시 SnapMirror 전송 수의 100%를 사용하는 스케줄을 추가하는 방법이 표시됩니다. 그러나 언제든지 25개의 동시 SnapMirror 전송을 초과할 수 없습니다.

+
' * transition schedule add -p sample_project -n dr_active -d 1-5 -b 23:30-e 03:00-c 25-x 200-u 00:30 * '

. 생성된 전환 프로젝트에 대한 자세한 정보를 봅니다.
+
'* 전이 CBT show-p_project-name_ *


