---
permalink: copy-based/task_aborting_a_subproject.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, abort, project 
summary: 예를 들어, 컨트롤러 또는 클러스터의 성능에 영향을 미치는 경우 실행 중인 프로젝트를 중단할 수 있습니다. 대시보드에서 실행 중인 프로젝트를 중단할 수 있습니다. 
---
= 프로젝트를 중단합니다
:icons: font
:imagesdir: ../media/


[role="lead"]
예를 들어, 컨트롤러 또는 클러스터의 성능에 영향을 미치는 경우 실행 중인 프로젝트를 중단할 수 있습니다. 대시보드에서 실행 중인 프로젝트를 중단할 수 있습니다.

SnapMirror 관계가 있는 전환 볼륨을 포함하는 프로젝트를 중단하기 전에 다음 사항을 고려해야 합니다.

* 두 프로젝트가 모두 시작된 경우 한 프로젝트를 중단하면 연결된 프로젝트가 중단됩니다.
+
예를 들어, 기본 프로젝트를 중단하면 보조 프로젝트도 중단됩니다.

* 현재 프로젝트에서 중단 작업이 실패하면 관련 프로젝트가 중단되지 않습니다.
* 활성 프로젝트가 하나만 중단되면 연결된 프로젝트의 시작 작업이 실패합니다.
* 운영 프로젝트를 중단할 경우 7-Mode 운영 볼륨에서 ONTAP 2차 볼륨으로 복제 작업이 중단되지 않습니다.
+
7-Mode 운영 볼륨에서 해당 ONTAP 운영 볼륨까지의 복사 작업만 중단됩니다.




NOTE: 7-Mode 프로젝트가 중단된 경우 유일한 옵션은 프로젝트를 삭제하는 것입니다. 프로젝트를 중단한 후에는 다시 시작하거나 다시 시작할 수 없습니다.

.단계
. 대시보드에서 중단하려는 프로젝트를 선택합니다.
. Abort * 를 클릭합니다.
. 클러스터에서 전환 과정에서 생성한 ONTAP 볼륨을 삭제합니다.
. 7-Mode 시스템에서 ONTAP 볼륨에 대한 SnapMirror 관계를 해제합니다.
. 볼륨 SnapMirror 관계를 중단하는 경우 다음을 수행해야 합니다.
+
.. 7-Mode 운영 볼륨과 ONTAP 2차 볼륨 간의 SnapMirror 관계를 끊은 후 삭제하십시오.
.. 운영 7-Mode 시스템에서 ONTAP 2차 볼륨과의 SnapMirror 관계를 해제합니다.




http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]

https://library.netapp.com/ecm/ecm_download_file/ECMP1511537["Data ONTAP 8. 2 명령: 7-Mode의 경우 수동 페이지 참조, 볼륨 1"]
