---
permalink: copy-based/task_generating_fc_zone_plan.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, generate, fc, zone, plan 
summary: FC 스위치의 경우 전환 평가 보고서의 일부로 FC 존 계획을 생성하여 마이그레이션 후 이니시에이터 호스트와 타겟을 그룹화하는 영역을 구성해야 합니다. 
---
= FC 존 계획을 생성하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
FC 스위치의 경우 전환 평가 보고서의 일부로 FC 존 계획을 생성하여 마이그레이션 후 이니시에이터 호스트와 타겟을 그룹화하는 영역을 구성해야 합니다.

* 7-Mode 시스템, 호스트 및 클러스터가 동일한 스위치에 연결되어 있어야 합니다.
+
xref:concept_supported_configurations_for_generating_an_fc_zone_plan.adoc[FC 존 계획 생성을 위한 지원 구성]

* 클러스터에 필요한 타겟 SVM 및 FC LIF를 생성해야 합니다.
* 타겟 SVM에 생성된 FC LIF에는 WWPN이 있으며 7-Mode WWPN과 다릅니다. 따라서 FCP에 대한 SAN으로 전환하는 동안 FC 조닝을 수행합니다.


.단계
. 수집 및 평가 섹션에서 * 시스템 추가 * 를 클릭합니다.
. 시스템 추가 창에서 다음 작업 중 하나를 수행합니다.
+
** 단일 시스템 추가:
+
... 시스템의 FQDN 또는 IP 주소를 입력합니다.
... 지정된 시스템의 사용자 이름과 암호를 입력합니다.
... 시스템 유형을 선택합니다.
+
**** Data ONTAP 스토리지 시스템
**** 호스트: Microsoft Windows, Red Hat Linux Enterprise 및 VMware ESXi
**** FC 스위치: Cisco 및 Brocade




** 찾아보기 * 를 클릭한 다음 여러 시스템의 자격 증명이 포함된 텍스트 파일을 선택하여 여러 시스템을 추가합니다.


. 추가 * 를 클릭합니다.
+
시스템의 평가 상태가 준비인 경우 해당 시스템에 대한 전환 평가를 수행할 수 있습니다.

. FC 존 계획을 사용하여 전환 평가 보고서를 생성합니다.
+
.. 전환 평가를 위해 필요한 FC 스위치를 포함한 시스템을 선택합니다.
.. 전환 평가 보고서 작성 * 을 클릭합니다.
.. 쌍 시스템과 FC 존 플래너 시작 대화 상자에서 7-Mode 시스템(단일 컨트롤러 또는 HA 쌍), 클러스터에 연결된 스위치 및 클러스터의 SVM을 선택합니다.
.. 페어링된 시스템의 경우 * FC 구역 설정 * 을 클릭합니다.
.. 전환 평가 보고서 생성 대화 상자에서 타겟 클러스터의 Data ONTAP 버전을 선택합니다.
.. 보고서의 파일 이름에 대한 접두사를 지정합니다.
.. 보고서 생성 * 을 클릭합니다.




FC zone plan은 .zip 파일로 생성된다. 이 계획에는 7-Mode 시스템의 igroup 구성에 따라 작성된 영역이 포함됩니다. 각 존은 단일 이니시에이터 WWPN과 여러 SVM 타겟 WWPN을 포함합니다.

FC 존 계획을 사용하여 클러스터에서 데이터 액세스를 제공하기 위한 이니시에이터 호스트 및 타겟을 그룹화하도록 영역을 구성해야 합니다.
