---
permalink: copy-based/task_generating_an_assessment_report_by_importing_inventory_report_xml.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, generate, assessment, report, inventory, xml 
summary: Inventory Collect Tool에서 생성한 Inventory XML 보고서를 가져와 호스트 및 컨트롤러의 기능과 특징을 평가할 수 있습니다. 그런 다음 평가 보고서를 생성하여 이러한 호스트 및 컨트롤러가 전환을 위해 선택한 ONTAP 버전에서 작동하는 방식을 식별할 수 있습니다. 
---
= 재고 보고서 XML을 가져와 평가 보고서 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Inventory Collect Tool에서 생성한 Inventory XML 보고서를 가져와 호스트 및 컨트롤러의 기능과 특징을 평가할 수 있습니다. 그런 다음 평가 보고서를 생성하여 이러한 호스트 및 컨트롤러가 전환을 위해 선택한 ONTAP 버전에서 작동하는 방식을 식별할 수 있습니다.

* 재고 수집 도구를 실행하고 재고 보고서 XML 파일을 생성해야 합니다.
+

NOTE: 복제 기반 전환을 위해 호스트 및 컨트롤러를 평가하려면 인벤토리 수집 도구 3.3을 사용하여 인벤토리를 수집해야 합니다.

* 전환 평가를 위해 7-Mode 시스템 및 호스트를 준비해야 합니다.


재고 보고서를 가져오고 전환 평가를 수행하는 동안 평가할 시스템에 연결할 수 없습니다.

.단계
. 7-Mode 전환 툴 에 로그인한 다음 홈 페이지에서 * 수집 및 평가 * 를 클릭합니다.
. 재고 보고서 XML 가져오기 * 를 클릭합니다.
. 찾아보기 * 를 클릭한 다음 인벤토리 수집 도구에서 생성된 XML 보고서를 선택합니다.
. 가져오기 * 를 클릭합니다.
+
시스템의 평가 상태가 Imported;Ready로 표시됩니다.

. 전환 평가를 수행할 시스템을 선택합니다.
. 전환 평가 보고서 작성 * 을 클릭합니다.
. 전환 평가 보고서 생성 대화 상자에서 타겟 클러스터의 Data ONTAP 버전을 선택합니다.
. 보고서의 파일 이름에 대한 접두사를 지정합니다.
. 보고서 생성 * 을 클릭합니다.
+
AssessmentWorkbook 및 AssessmentExecutiveSummary 보고서는 XML 형식으로 생성됩니다.

. Microsoft Excel의 AssessmentWorkbook 보고서와 Microsoft Office 2007 이상 버전을 사용하여 Microsoft Word의 AssessmentExecutiveSummary 보고서를 볼 수 있습니다.
+
Microsoft Excel에서 AssessmentWorkbook 보고서를 보려면 Excel에서 매크로를 사용하도록 설정해야 할 수 있습니다.



* 관련 정보 *

xref:task_collecting_tool_logs.adoc[전환 로그 파일을 다운로드하는 중입니다]
