---
permalink: copy-based/task_running_precheck_on_a_session.html 
sidebar: sidebar 
keywords: ontap, copy, based, transition, run, prechecks 
summary: 전환 세션을 생성한 후 세션을 검증하여 전환 사전 확인 명령을 사용하여 7-Mode 환경을 전환할 수 있는지 확인할 수 있습니다. 7-Mode 스토리지 시스템과 SVM 간의 호환성을 검증하여 기능 및 보안 설정과 같은 요소를 확인할 수 있습니다. 
---
= 사전 점검 실행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환 세션을 생성한 후 세션을 검증하여 'transition precheck' 명령을 사용하여 7-Mode 환경을 전환할 수 있는지 확인할 수 있습니다. 7-Mode 스토리지 시스템과 SVM 간의 호환성을 검증하여 기능 및 보안 설정과 같은 요소를 확인할 수 있습니다.

전환 세션이 준비 상태여야 합니다.

Transition CBT precheck 명령은 상세한 오류 메시지 보고서를 생성한다. 보고서에서 식별된 문제점에는 전환 프로세스에 대한 문제의 영향에 따라 심각도 수준이 다릅니다. 일부 오류는 전환을 방해할 수 있으므로 오류 및 경고에 대한 수정 조치를 수행해야 합니다. 또한 전환을 진행하기 전에 다른 심각도 수준의 메시지가 미치는 영향을 검토해야 합니다.

.단계
. 전환을 위한 호환성 확인:
+
'* 전이 CBT 사전 점검 - p_project_name_ * '

+
[listing]
----
7-Mode Transition Tool>transition cbt precheck -p project_finance

[1/14 ] Project status checks                                                  [    Errors     ]

Operation summary:
------------------
The 'precheck' operation on the project 'project_finance' has failed.

 1  Errors - Failed!

Do you want to see a detailed report {yes, no} [yes]:

1 Errors:
---------
90202: Checking whether any of the 7-Mode volumes are in 'offline' state.                              [     Error     ]
  > Following volumes are in 'offline' state.
  > CORRECTIVE-ACTION: Bring offline volumes online by using the following command: 'vol online
  > <volume_name>'.
  > AFFECTED-OBJECTS: { vol2 }

Next suggested steps:
---------------------
1. Review the 'precheck' operation results, fix all blocking errors and run the 'precheck' operation again.
2. Use the 'transition job-results -j 6e33e0a7-bb36-49df-91f3-2e52cbfa3074' command to see the results of this
operation.

Ran precheck for project 'project_finance'.
----


7-Mode 볼륨에서 데이터 복사본을 시작하기 전에 전환에 문제를 일으킬 수 있는 모든 오류를 해결해야 합니다.
