---
settings:
  name: ONTAP 7-Mode Transition
  platform: ''
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 7-Mode 전환
    url: "/index.html"
  - title: 릴리즈 노트
    url: "/releasenotes.html"
  - section: command-map
  - section: install-admin
  - section: copy-based
  - section: copy-free
  - section: inventory-collect
  - section: snapmirror
  - section: san-host
  - title: 법적 고지
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: 새로운 소식
      summary: 최신 버전의 7-Mode 전환 툴의 새로운 기능을 살펴보십시오
      url: releasenotes.html
    - title: 7-Mode 전환 툴을 설치합니다
      summary: Microsoft Windows 또는 Linux에 도구를 설치하는 방법에 대해 알아봅니다
      url: "/install-admin/concept_transition_to_clustered_ontap_using_7mtt.html"
    - title: 전환에 필요한 데이터를 수집합니다
      summary: 전환에 필요한 정보를 수집하는 방법을 알아보십시오
      url: "/inventory-collect/concept_collecting_host_and_storage_inventory_information_for_transition_assessment.html"
  - title: 7-Mode 관리자용 명령 맵
    links:
    - title: 7-Mode 명령이 ONTAP 명령에 매핑되는 방법
      summary: 7-Mode 명령에 해당하는 ONTAP을 찾으십시오
      url: "/command-map/reference_how_7_mode_commands_map_to_clustered_ontap_commands.html"
    - title: 7-Mode 옵션이 ONTAP 명령에 매핑되는 방법
      summary: 7-Mode 옵션이 ONTAP 명령 매개 변수에 매핑되는 방법에 대해 알아보십시오
      url: "/command-map/reference_how_7_mode_options_map_to_clustered_ontap_commands.html"
    - title: 7-Mode 구성 파일이 ONTAP 명령에 매핑되는 방법
      summary: 7-Mode 구성 파일이 ONTAP 구성 명령에 매핑되는 방법에 대해 설명합니다
      url: "/command-map/reference_how_7_mode_configuration_files_map_to_clustered_ontap_commands.html"
  - title: 전환할 방법을 찾고 있습니다
    links:
    - title: 복사 기반 전환
      summary: 이 툴을 사용하여 7-Mode에서 ONTAP로 복사 기반 전환을 수행합니다
      url: "/copy-based/concept_copy_based_transition_workflow.html"
    - title: 복사 없는 전환
      summary: 이 툴을 사용하여 7-Mode에서 ONTAP으로 복사 없이 전환할 수 있습니다
      url: "/copy-free/task_copy_free_transition_workflow.html"
    - title: SnapMirror를 사용하여 데이터를 전환합니다
      summary: SnapMirror 명령을 사용하여 7-Mode에서 ONTAP로 데이터를 전환하는 방법을 알아보십시오
      url: "/snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html"
  - title: SAN 호스트 전환 및 수정
    links:
    - title: VMware ESXi
      summary: VMware ESXi 호스트의 전환 전 및 전환 후 요구 사항을 이해합니다
      url: "/san-host/concept_vmware_esxi_host_remediation.html"
    - title: Red Hat Enterprise Linux
      summary: Red Hat Enterprise Linux 호스트에 대한 전환 전/후 요구 사항을 이해합니다
      url: "/san-host/concept_linux_host_remediation.html"
    - title: Windows
      summary: Microsoft Windows 호스트의 전환 전 및 전환 후 단계를 이해합니다
      url: "/san-host/concept_windows_host_remediation.html"
product-family:
  name: ONTAP
  repo: ontap-family
