---
permalink: install-admin/concept_system_requirements_for_7mtt_on_windows.html 
sidebar: sidebar 
keywords: ontap, 7, mode, install, system, requirements, windows, transition, tool 
summary: 7-Mode 전환 툴을 설치하고 실행하려면 Windows 호스트가 필요한 구성을 충족하는지 확인해야 합니다. 
---
= Windows 시스템에 7-Mode Transition Tool을 설치하기 위한 시스템 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode 전환 툴을 설치하고 실행하려면 Windows 호스트가 필요한 구성을 충족하는지 확인해야 합니다.

최신 7-Mode 전환 툴을 참조하십시오 link:http://docs.netapp.com/us-en/ontap-7mode-transition/releasenotes.html["릴리즈 노트"] 지원되는 호스트 및 알려진 문제에 대한 최신 정보를 확인하십시오.



== 하드웨어 요구 사항

* 듀얼 코어 x64 프로세서, 1.0GHz 이상
* 8GB RAM
* 40GB의 사용 가능한 디스크 공간




== 소프트웨어 요구 사항

* 64비트 Windows 시스템에서 다음 운영 체제 버전 중 하나를 실행해야 합니다.
+
** Windows 7 Enterprise
** Windows 7 Enterprise SP1
** Windows Server 2008 Standard를 참조하십시오
** Windows Server 2008 R2 Standard를 참조하십시오
** Windows Server 2008 R2 Enterprise SP1
** Windows Server 2012 Standard를 참조하십시오
** Windows Server 2012 R2 Standard를 참조하십시오
** Windows 8.1 Enterprise
** Windows Server 2012 R2 Datacenter Edition을 참조하십시오
** 7-Mode 전환 툴 버전 3.3.2P1의 경우 다음 운영 체제 버전 중 하나를 사용할 수도 있습니다.
+
*** Windows 10 Enterprise
*** Windows Server 2016 Standard
*** Windows Server 2016 데이터 센터
*** Windows Server 2019 Standard
*** Windows Server 2019 데이터 센터


** 7-Mode Transition Tool 버전 3.3.3의 경우 다음 운영 체제 버전 중 하나를 사용할 수도 있습니다.
+
*** Windows 10 Professional을 참조하십시오
+

NOTE: 필요한 소프트웨어 요구사항 및 하드웨어 요구사항을 충족하는 Windows 가상 머신을 사용하여 7-Mode 전환 툴을 설치할 수 있습니다.





* 64비트 Oracle Java Runtime Environment(JRE) 1.8 업데이트 331
+

NOTE: Windows 호스트에 JRE가 없거나 32비트 JRE가 설치되어 있는 경우 7-Mode 전환 도구 설치 프로그램이 64비트 JRE 1.8 업데이트 331을 자동으로 설치합니다. 이전 버전의 64비트 JRE가 설치되어 있는 경우 설치 프로그램이 JRE를 JRE 1.8 업데이트 331로 자동 업데이트합니다.

+
JRE가 자동으로 업데이트되면 이전 버전의 JRE가 필요한 다른 응용 프로그램에 영향을 줄 수 있습니다.

+

NOTE: JRE 버전 1.8 업데이트 46 이상(JRE 1.8 업데이트 331 포함)의 경우 7-Mode 전환 도구가 7-Mode 시스템 및 ONTAP 시스템에서 작동하는 Data ONTAP와 통신하려면 7-Mode 시스템에서 작동하는 Data ONTAP와 ONTAP 시스템의 SSL 키 길이가 1024개 이상이어야 합니다.

+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/7MTT%3A_How_to_resolve_TLS_or_SSL_communication_issue["7MTT: TLS 또는 SSL 통신 문제를 해결하는 방법"]





== 서버 구성 요구 사항

웹 인터페이스에 액세스하려면 도구가 설치된 Windows 시스템을 다음과 같이 구성해야 합니다.

* 7-Mode Transition Tool 서버의 포트 8443을 사용할 수 있어야 합니다.
+
포트 8443을 사용할 수 없거나 다른 포트를 사용하려면 '$install_DIR\etc\conf\transition-tool.conf' 파일에서 'tool.https.port' 매개 변수에 지정된 포트를 변경해야 합니다.

+
웹 인터페이스에 액세스하는 데 HTTPS를 사용하는 것이 가장 좋습니다. 그러나 웹 인터페이스에 액세스하기 위해 HTTP를 사용하려면 포트 8088을 사용할 수 있어야 합니다. 포트 8088 대신 transition-tool.conf 파일에서 tool.http.port 매개변수로 지정한 포트를 변경해야 합니다.

+

NOTE: 구성 파일에서 포트를 변경한 후에는 7-Mode Transition Tool 서비스를 다시 시작해야 합니다.

* 이 도구에 액세스하는 데 사용되는 포트의 트래픽을 허용하도록 방화벽을 끄거나 구성해야 합니다.


넷그룹과 CIFS 로컬 사용자 및 그룹을 이전하려면 다음 요구 사항을 충족해야 합니다.

* 7-Mode Transition Tool의 포트 8088을 사용할 수 있어야 합니다.
+
포트 8088 대신 transition-tool.conf 파일에서 tool.http.port 매개변수로 지정한 포트를 변경한 다음 7-Mode Transition Tool 서비스를 다시 시작해야 합니다.

* 클러스터의 각 노드에는 타겟 SVM용으로 구성된 데이터 LIF가 하나 이상 있어야 합니다.
* 모든 SVM 데이터 LIF는 'transition-tool.conf' 파일의 'tool.http.port' 매개 변수에 지정된 포트 또는 7-Mode Transition Tool 포트 8088과 통신할 수 있어야 합니다.
+

NOTE: 방화벽이 이 트래픽을 차단하지 않도록 해야 합니다.





== 클라이언트(웹 인터페이스) 요구 사항

웹 인터페이스에 액세스하는 시스템에는 다음이 있어야 합니다.

* 다음 웹 브라우저 중 하나:
+
** Microsoft Internet Explorer 9, 10 또는 11
** Google Chrome 27 이상
** Mozilla Firefox 20 이상 모든 브라우저는 TLS를 지원해야 합니다.


+

NOTE: Microsoft Internet Explorer를 웹 브라우저로 사용하는 경우 SSLv2를 비활성화해야 합니다.

* 1280×1024 이상의 화면 해상도


새 버전의 도구를 설치할 때마다 시스템에서 Ctrl+F5를 눌러 브라우저 캐시를 지워야 합니다.

* 관련 정보 *

https://mysupport.netapp.com/NOW/products/interoperability["NetApp 상호 운용성"]
