---
permalink: inventory-collect/task_generating_fc_zone_plan.html 
sidebar: sidebar 
keywords: ontap, 7, mode, generate, fc, zone, plan, transition 
summary: Data ONTAP 시스템, 호스트 및 FC 스위치에 대한 정보를 수집한 후 마이그레이션 후 클러스터의 스위치를 구성하는 데 사용되는 FC 존 계획을 생성할 수 있습니다. 
---
= FC 존 계획을 생성하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
Data ONTAP 시스템, 호스트 및 FC 스위치에 대한 정보를 수집한 후 마이그레이션 후 클러스터의 스위치를 구성하는 데 사용되는 FC 존 계획을 생성할 수 있습니다.

* 7-Mode 시스템, 호스트 및 클러스터가 스위치에 연결되어 있어야 합니다.
* 클러스터, SVM, FCP LIF 및 스위치에 대한 정보를 수집해야 합니다.
+
클러스터는 7-Mode 시스템과 동일한 스위치에 연결하거나 동일한 패브릭의 새 스위치에 연결할 수 있습니다.

+
xref:concept_supported_configurations_for_generating_an_fc_zone_plan.adoc[FC 존 계획 생성을 위한 지원 구성]



.단계
. CLI에서 ICT 디렉토리로 이동합니다.
. CLI에서 FC 존 계획을 생성합니다.
+
'* ICT--cmd generate-fc-zones--source-filers_7-mode-ip17mode-ip2_--dest-svm_cluster-name:vserver-name_--fc-switches_switch-name:vsan-id1, vsan-id2_7mode_cDOT_switch_inventory.xml *'

+
Cisco 스위치에 대한 VSAN ID를 입력해야 합니다.

+
[listing]
----
...bin\ict>ict --cmd generate-fc-zones --source-filers system1,system2 --dest-svm vs1:fc_zone1
 --fc-switches brocade-1,brocade-2 7mode_cdot_switch_inventory.xml
----
+
FC 존 계획에는 7-Mode 시스템의 igroup 구성에 따라 생성된 구역이 포함되어 있습니다. 각 존은 단일 이니시에이터 WWPN과 여러 SVM 타겟 WWPN을 포함합니다.



복제 기반 전환 시에는 FC 존 계획을 사용하여 사전 컷오버 읽기/쓰기 모드 중에 존을 구성하여 테스트 호스트를 사용하거나, 컷오버 단계 이후에 클러스터의 이니시에이터 호스트에 대한 데이터 액세스를 제공할 수 있습니다.

복제가 필요 없는 전환 시에는 FC 존 계획을 사용하여 적용 구성 단계에서 클러스터에서 데이터 액세스를 제공하기 위한 이니시에이터 호스트 및 타겟을 그룹화하도록 영역을 구성해야 합니다.
