---
permalink: copy-free/concept_aggregate_space_considerations_during_transition.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, aggregate, space, requirements 
summary: 전환하기 전에 7-Mode 애그리게이트에 충분한 가용 공간이 있는지 확인해야 합니다. 7-Mode 전환 툴은 물리적 공간, 논리적 공간, 스냅샷 복사본이 차지하는 공간 및 공간 보장 설정을 기반으로 애그리게이트에서 다양한 공간 점검을 수행합니다. 또한 Flash Pool 애그리게이트와 관련된 공간 고려 사항을 알고 있어야 합니다. 
---
= 전환을 위한 애그리게이트 공간 요구사항
:icons: font
:imagesdir: ../media/


[role="lead"]
전환하기 전에 7-Mode 애그리게이트에 충분한 가용 공간이 있는지 확인해야 합니다. 7-Mode 전환 툴은 물리적 공간, 논리적 공간, 스냅샷 복사본이 차지하는 공간 및 공간 보장 설정을 기반으로 애그리게이트에서 다양한 공간 점검을 수행합니다. 또한 Flash Pool 애그리게이트와 관련된 공간 고려 사항을 알고 있어야 합니다.



== 애그리케이트 내의 물리적 공간

7-Mode 애그리게이트에서 사용 가능한 공간이 물리적 공간의 5% 미만이면 전환이 차단됩니다. 모범 사례는 전환 전에 7-Mode 애그리게이트에서 20% 이상의 여유 공간을 확보하는 것입니다.

Aggregate에 추가 공간이 필요한 이유는 다음과 같습니다.

* 내보내기 단계 동안 각 7-Mode 애그리게이트의 애그리게이트 레벨 스냅샷 복사본 생성
* 운영 전 테스트 단계에서 전환된 애그리게이트에서의 워크로드를 새로운 데이터로 테스트합니다


추가 공간이 없는 경우, 전환하기 전에 7-Mode 시스템에 디스크를 추가할 수 있습니다. 디스크 추가가 불가능하거나 사전 운영 단계 중에 전환된 볼륨에 제한된 양의 데이터만 쓸 수 있는 경우 7-Mode Transition Tool을 통해 이 오류를 확인하고 전환을 계속 진행할 수 있습니다. 그러나 전환 중에도 애그리게이트 공간을 계속 모니터링하고 사전 운영 테스트 단계에서 애그리게이트가 자라지 않도록 해야 합니다.



== 애그리케이트 내의 논리적 공간

7-Mode 애그리게이트의 논리적 공간이 97% 이상 차면 7-Mode 전환 툴이 사전 점검 중에 차단 오류를 발생시킵니다. 계획 단계 중에 이 오류를 무시하고 전환을 계속할 수 있습니다. 하지만 Aggregate에서 볼륨의 크기를 줄이거나 애그리게이트에 디스크를 추가하여 내보내기 및 중지 작업을 수행하기 전에 사용된 논리적 공간이 97% 미만인지 확인해야 합니다. 내보내기 및 중지 단계에서는 이 오류를 무시할 수 없습니다.



== 스냅샷 오버플로

7-Mode 애그리게이트의 스냅샷 복사본이 스냅샷 복사본 예약을 위해 할당된 공간보다 더 많은 공간을 차지하는 경우 엑스포트 및 중지 작업에서 애그리게이트 레벨의 스냅샷 복사본 생성이 실패할 수 있습니다. 7-Mode Transition Tool에서 이 상태를 사전 확인하는 동안 차단 오류가 발생합니다. 이러한 상황에서는 계획 단계 중에 기존의 모든 애그리게이트 레벨 스냅샷 복사본을 삭제해야 합니다.

기존 스냅샷 복사본을 삭제하지 않을 경우 계획 단계에서 이 오류를 무시하고 전환을 계속할 수 있습니다. 하지만 엑스포트 및 중지 작업 전에 스냅샷 복사본의 사용된 용량 비율이 100% 미만인지 확인해야 합니다.



== 공간 보장 설정입니다

7-Mode Transition Tool은 7-Mode 컨트롤러에 공간 보장 설정이 다음과 같은 볼륨이 있는지 사전 확인 중에 차단 오류를 발생시킵니다.

* 볼륨 보장 볼륨이 비활성화되어 있습니다
* 파일 보장 볼륨
* * 볼륨 - 볼륨 보증 비활성화 *
+
경우에 따라 Aggregate의 공간 부족으로 인해 볼륨 보증 볼륨에 대해 공간 보장이 사용되지 않을 수 있습니다.

+
7-Mode 애그리게이트에 충분한 여유 공간을 생성한 후 다음 7-Mode 명령을 사용하여 이러한 7-Mode 볼륨에 대해 공간 보장을 활성화해야 합니다.

+
``vol options_volume_name_보증 볼륨 *’

+
7-Mode에서 수정 조치를 수행하지 않으려는 경우 이 오류를 무시할 수 있습니다. 전환이 완료된 후 다음 명령을 사용하여 보장이 사용되지 않는 볼륨을 검사하고 수동으로 보장을 사용하도록 설정합니다.

+
'* 볼륨 수정 - vserver-volume-space-보증 볼륨 *'

* * 파일 보장 볼륨 *
+
ONTAP에서는 파일 보증이 지원되지 않습니다.

+
파일 보장 볼륨이 있는 경우 다음 작업 중 하나를 수행해야 합니다.

+
** 7-Mode 볼륨에 공간 예약 LUN 또는 파일이 포함된 경우 7-Mode 명령: + ``vol options_volume_name_보증 볼륨 *’’을 사용하여 볼륨의 공간 보장 유형을 볼륨으로 변경하십시오
+
이 명령을 실행하기 전에 7-Mode 애그리게이트에 충분한 여유 공간이 있는지 확인해야 합니다.

** 7-Mode 볼륨에 공간 예약 LUN 또는 파일이 없는 경우 다음 7-Mode 명령을 사용하여 볼륨 공간 보장을 NONE으로 변경하십시오. 7-Mode에서 수정 조치를 수행하지 않으려면 이 오류를 무시하고 전환을 계속할 수 있습니다.


+
전환 중에 이러한 볼륨에 공간 예약 LUN 또는 파일이 포함된 경우 공간 보장이 자동으로 "볼륨"으로 변환되지만 공간 보장은 처음에 비활성화됩니다. Aggregate에 여유 공간을 충분히 생성한 후 다음 명령을 사용하여 수동으로 보장을 활성화해야 합니다.

+
'* 볼륨 수정 - vserver-volume-space-보증 볼륨 * '

+
+ 볼륨에 공간 예약 LUN 또는 파일이 없는 경우 전환 중에 공간 보장이 자동으로 없음으로 변환됩니다.





== Flash Pool 애그리게이트를 위한 추가 고려사항

Flash Pool 애그리게이트의 SSD 여유 공간이 SSD 총 디스크 공간의 5% 미만인 경우 전환이 지원되지 않습니다. 전환을 계속하려면 SSD 캐시를 해제하거나 SSD를 더 추가해야 합니다.

* 관련 정보 *

xref:reference_ignorable_errors_during_transition.adoc[전환 중에 오류가 발생합니다]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-psmg/home.html["디스크 및 애그리게이트 관리"]
