---
permalink: copy-free/concept_how_you_can_use_assessment_executive_summary_for_transition_assessment.html 
sidebar: sidebar 
keywords: assessment, ontap, transition, copy, free, executive, summary 
summary: '전환 요약: 현재 환경에 있는 7-Mode 컨트롤러, 호스트 및 FC 스위치에 대한 요약을 제공합니다. 사용되는 현재 기능에 대한 평가 보고서를 제공하고 스토리지 환경 내의 각 볼륨에 대한 전환 방법을 권장합니다. 요약을 사용하여 전환을 계획할 수 있습니다.' 
---
= 전환 평가를 위한 평가 핵심 요약 활용 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환 요약: 현재 환경에 있는 7-Mode 컨트롤러, 호스트 및 FC 스위치에 대한 요약을 제공합니다. 사용되는 현재 기능에 대한 평가 보고서를 제공하고 스토리지 환경 내의 각 볼륨에 대한 전환 방법을 권장합니다. 요약을 사용하여 전환을 계획할 수 있습니다.

핵심 요약에는 다음과 같은 주요 섹션이 있습니다.



== 타겟 클러스터

이 섹션에는 평가 중에 선택한 타겟 클러스터의 ONTAP 버전이 나와 있습니다.



== 데이터 수집 요약

정보를 수집한 7-Mode 컨트롤러, 호스트 및 스위치 목록을 볼 수 있습니다. 7-Mode 컨트롤러의 ONTAP 버전 및 모델 세부 정보를 볼 수 있습니다. 호스트의 OS 유형, 버전 및 모델도 볼 수 있습니다.



== 전환 가능성 및 권장 전환 방법

이 섹션에서는 각 컨트롤러에서 실행되는 사전 점검과 컨트롤러 및 볼륨 레벨에서 전환을 실행할 수 있는 가능성에 대한 요약을 제공합니다. '최고치' 또는 '불일치' 상태에 있는 vFiler 유닛 또는 오프라인 또는 제한된 볼륨에 속한 볼륨은 평가를 위해 포함되지 않습니다. 보고서에는 각 컨트롤러에 대해 사전 점검에서 보고된 오류 및 경고 수가 표시됩니다. 전환 전에 이러한 오류 및 경고를 검토하고 문제를 해결해야 합니다. 이러한 사전 점검에 대한 자세한 내용은 평가 워크북의 구성 사전 점검 요약 탭에서 확인할 수 있습니다.

* 무료 전환 실현 가능성 *: 이 섹션에는 컨트롤러 레벨에서 사전 점검을 수행하여 복사 없는 전환을 위한 오류 및 경고를 발생시킨 수가 나와 있습니다. HA 2노드의 한 컨트롤러에 대해 사전 검사가 실패하면 무복사 전환을 사용하여 HA 쌍을 전환할 수 없습니다. HA 쌍을 전환하기 전에 모든 오류와 경고를 해결해야 합니다. 이러한 사전 점검에 대한 자세한 내용은 평가 워크북의 CFT 사전 점검 요약 탭에서 확인할 수 있습니다.

볼륨 및 컨트롤러 구성과 사전 점검 요약을 기준으로, 경영진 요약은 각 평가 볼륨에 가장 적합한 전환 방법에 대한 권장사항을 제공합니다. 예를 들어, 7-Mode 기존 볼륨 또는 FlexCache 볼륨은 ONTAP에서 지원되지 않으므로 전환할 수 없습니다.

대부분의 구성에서 7-Mode Transition Tool은 전환을 위한 권장 툴입니다. 하지만 7-Mode 전환 툴을 사용하여 전환할 수 없는 워크로드도 일부 있으며, 애플리케이션 기반 또는 호스트 기반 마이그레이션 방법을 사용해야 합니다.

http://["NetApp 기술 보고서 4052: clustered Data ONTAP으로 성공적으로 전환(Data ONTAP 8.2.x 및 8.3)"]



== 스토리지 인벤토리

이 섹션에서는 다음 정보를 제공합니다.

* 스토리지 오브젝트: 볼륨, qtree, LUN, vFiler 유닛, 볼륨, 볼륨, 볼륨, 각 컨트롤러에서 SnapMirror 관계, 공유 및 엑스포트 지원
* 스토리지 활용: 7-Mode 컨트롤러에서 사용하는 공간, 사용 가능한 공간 및 공간에 대한 정보를 제공합니다.
* 라이센스: 각 컨트롤러에서 활성화된 기능 라이센스 목록을 제공합니다.
* 프로토콜 구성: CIFS, NFS, SAN 프로토콜 및 버전과 같이 컨트롤러에 구성된 프로토콜에 대한 세부 정보를 제공합니다.
* SnapMirror 상호 연결: SnapMirror 관계의 소스 또는 대상인 컨트롤러 또는 볼륨에 대한 정보를 제공합니다.
+
이 정보를 사용하여 보고서에 나열된 컨트롤러와 SnapMirror 관계에 있는 컨트롤러를 식별할 수 있지만 평가에는 포함되지 않습니다.

* SnapVault 상호 연결: 컨트롤러의 지정된 컨트롤러, 볼륨 또는 qtree와 SnapVault 관계의 소스 또는 대상이 되는 컨트롤러, 볼륨 또는 qtree에 대한 정보를 제공합니다.




== 데이터 수집 오류입니다

이 섹션에서는 7-Mode Transition Tool에서 수집하지 못한 컨트롤러 및 호스트 정보와 장애 이유에 대해 자세히 설명합니다. 데이터 수집 오류에 대한 자세한 내용은 평가 워크북의 데이터 수집 오류 탭에서 확인할 수 있습니다. 이러한 오류를 해결하고 시스템을 다시 평가할 수 있습니다.
