---
permalink: copy-free/concept_supported_and_unsupported_data_protection_relationships.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, data, protection, supported, unsupported, configurations 
summary: SnapMirror 관계의 일부인 볼륨을 전환할 수 있습니다. 그러나 일부 데이터 보호 및 재해 복구 구성은 전환이 지원되지 않으므로 이러한 구성을 전환하기 위해 몇 가지 수동 단계를 수행해야 합니다. 
---
= 데이터 보호 전환: 지원 구성 및 지원되지 않는 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror 관계의 일부인 볼륨을 전환할 수 있습니다. 그러나 일부 데이터 보호 및 재해 복구 구성은 전환이 지원되지 않으므로 이러한 구성을 전환하기 위해 몇 가지 수동 단계를 수행해야 합니다.



== 지원되는 구성

7-Mode 전환 툴을 사용하여 볼륨 SnapMirror 관계를 전환할 수 있습니다. 운영 HA 쌍 및 2차 HA 쌍의 복사를 수행하지 않는 전환을 수행할 수 있습니다. 그런 다음 전환 후 볼륨 SnapMirror 관계를 수동으로 설정해야 합니다.

xref:task_transitioning_a_snapmirror_relationship.adoc[SnapMirror 관계 전환]



== 지원되지 않는 구성입니다

* SnapVault 관계
+
SnapVault 관계의 소스인 볼륨은 마이그레이션할 수 있지만 SnapVault 관계는 전환되지 않습니다. SnapVault 관계의 대상인 볼륨은 SnapVault 백업이 중지된 후에만 마이그레이션할 수 있습니다.

+
http://www.netapp.com/us/media/tr-4052.pdf["NetApp 기술 보고서 4052: clustered Data ONTAP으로 성공적으로 전환(Data ONTAP 8.2.x 및 8.3)"]

* Qtree SnapMirror 관계
+
Qtree SnapMirror 관계의 소스인 qtree가 있는 볼륨은 전환될 수 있지만 qtree SnapMirror 관계는 전환되지 않습니다. Qtree SnapMirror 관계의 타겟인 qtree가 있는 볼륨은 qtree SnapMirror 관계가 깨진 후에만 마이그레이션할 수 있습니다.

* 재해 복구 vFiler 유닛
+
재해 복구 vFiler 유닛의 소스인 볼륨을 마이그레이션할 수 있지만 재해 복구 vFiler 유닛은 전환되지 않습니다. 재해 복구 관계가 삭제된 후에만 재해 복구 vFiler 유닛의 대상인 볼륨을 마이그레이션할 수 있습니다.

* NDMP 구성
+
전환이 완료되면 ONTAP에서 전환된 볼륨에 대한 백업 정책을 수동으로 설정해야 합니다.

+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ptbrg/home.html["테이프 백업을 사용한 데이터 보호"]

* 동기 SnapMirror 관계
+
이 기능은 ONTAP에서 지원되지 않지만, 관계의 일부인 볼륨을 전환할 수 있습니다.



* 관련 정보 *

xref:task_customizing_configurations_for_transition.adoc[7-Mode 구성의 전환 사용자 지정]
