---
permalink: copy-free/concept_supported_and_unsupported_name_services_configurations.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, name, services, required, manual, steps 
summary: 7-Mode 전환 툴을 통해 전환된 네임 서비스 구성을 알고 있어야 합니다. 일부 네임 서비스 구성은 ONTAP에서 지원되지 않거나 수동으로 전환해야 하기 때문에 ONTAP로 전환되지 않습니다. 
---
= 이름 서비스 전환: 지원되는 구성과 지원되지 않는 구성 및 필요한 수동 단계
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode 전환 툴을 통해 전환된 네임 서비스 구성을 알고 있어야 합니다. 일부 네임 서비스 구성은 ONTAP에서 지원되지 않거나 수동으로 전환해야 하기 때문에 ONTAP로 전환되지 않습니다.

이러한 구성이 전환에 미치는 영향을 평가하기 위해 모든 사전 점검 오류 및 경고 메시지를 확인해야 합니다.



== 전환되었습니다

크게, 7-Mode 전환 툴을 통해 다음과 같은 네임 서비스 구성을 전환합니다.

* DNS 설정('/etc/resolv.conf')
* LDAP 구성
* NIS 구성
* 이름 서비스 스위치 구성('/etc/nsswitch.conf' 및 '/etc/resolv.conf')
* 호스트 구성('/etc/hosts')
* Unix 사용자 및 그룹('/etc/passwd' 및 '/etc/group')
* netgroup 구성("/etc/netgroup")


이러한 이름 서비스 구성에 대한 자세한 내용은 사전 점검 결과를 참조하십시오.



== ONTAP에서 지원되지 않는 구성입니다

* NIS 슬레이브
* NIS 브로드캐스트
* NIS 그룹 캐싱
* 다이나믹 DNS
* DNS 캐시
* 섀도 데이터베이스
* 파일 또는 DNS 이외의 호스트 데이터베이스 소스
+
ONTAP는 호스트 조회에 대해 파일 및 DNS만 지원하며 다른 데이터베이스 원본은 지원되지 않습니다. 전환 중에는 '/etc/nsswitch.conf'의 호스트 조회 순서가 무시됩니다.





== 수동으로 구성해야 하는 구성입니다

SVM에서 다음 LDAP 옵션을 수동으로 구성해야 합니다.

* "ldap.usermap.attribute.unixaccount`
* "LDAP.PASSWORD"
* "ldap.usermap.base`
* ldap.ssl.enable을 선택합니다


* 관련 정보 *

xref:task_customizing_configurations_for_transition.adoc[7-Mode 구성의 전환 사용자 지정]

https://docs.netapp.com/ontap-9/topic/com.netapp.doc.cdot-famg-nfs/home.html["NFS 관리"]

https://docs.netapp.com/us-en/ontap/networking/index.html["네트워크 및 LIF 관리"]
