---
permalink: copy-free/concept_restrictions_during_preproduction_testing.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, preproduction, testing, restrictions 
summary: 일부 작업은 차단되며 일부 작업은 사전 프로덕션 테스트 중에 권장되지 않습니다. 이러한 제한은 전환을 커밋하지 않으려는 경우 7-Mode로의 롤백을 허용하기 위해 적용됩니다. 
---
= 사전 프로덕션 테스트 중 제한 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
일부 작업은 차단되며 일부 작업은 사전 프로덕션 테스트 중에 권장되지 않습니다. 이러한 제한은 전환을 커밋하지 않으려는 경우 7-Mode로의 롤백을 허용하기 위해 적용됩니다.



== 차단된 작업입니다

|===
| 작동 | 설명 


 a| 
애그리게이트 스냅샷 복사본을 자동으로 삭제(자동 삭제)합니다
 a| 
롤백의 경우 내보내기 작업 중에 생성된 7-Mode 애그리게이트 레벨의 스냅샷 복사본이 필요하기 때문에 이 스냅샷 복사본은 Aggregate의 사용된 공간이 확장되어도 자동으로 삭제되지 않습니다.


IMPORTANT: Aggregate의 여유 물리적 공간을 모니터링하고 테스트 중에 Aggregate의 공간이 부족하지 않은지 확인해야 합니다.



 a| 
볼륨을 다른 애그리게이트로 이동
 a| 
* 볼륨을 전환된 Aggregate로 이동할 수 없습니다.
* 전환된 애그리게이트로부터 클러스터의 애그리게이트로 볼륨을 이동할 수 있습니다.




 a| 
볼륨 간에 LUN 복사 또는 이동
 a| 
* LUN을 전환된 볼륨으로 복사하거나 이동할 수 없습니다.
* 전환된 볼륨에서 클러스터의 다른 볼륨으로 LUN을 복사하거나 이동할 수 있습니다.




 a| 
애그리게이트 생성
 a| 
이 작업은 타겟 클러스터 HA 쌍에서 제한됩니다. 클러스터의 다른 노드에서 애그리게이트를 생성할 수 있습니다.



 a| 
애그리게이트 제거
 a| 
내보내기 작업 중에 생성된 7-Mode 애그리게이트 레벨 스냅샷 복사본이 롤백 시 필요하기 때문에 전환된 애그리게이트를 폐기할 수 없습니다.



 a| 
전환된 애그리게이트를 루트 애그리게이트로 설정
 a| 
전환된 애그리게이트는 루트 애그리게이트로 선택할 수 없습니다. 또한 전환된 애그리게이트의 HA 정책을 CFO로 수정할 수 없습니다.



 a| 
파일 복사 작업을 수행하는 중입니다
 a| 
* 파일(필요 시 단일 파일 복사)을 전환된 볼륨으로 이동하거나 복사할 수 없습니다.
* 전환된 볼륨에서 클러스터의 다른 볼륨으로 파일을 이동하거나 복사할 수 있습니다.




 a| 
기존 애그리게이트 미러링
 a| 
이 작업은 클러스터의 모든 애그리게이트에서 차단됩니다.



 a| 
타겟 클러스터 노드에서 Data ONTAP 버전 업그레이드 또는 되돌리기
 a| 
타겟 클러스터 노드를 업그레이드하거나 되돌리기 전에 프로젝트를 커밋해야 합니다.



 a| 
디스크를 추가하는 중입니다
 a| 
관리 권한 수준에서는 'Storage aggregate add-disks' 명령을 실행할 수 없습니다. 그러나 고급 권한 수준에서 이 명령을 실행할 수 있습니다.


IMPORTANT: 전환된 애그리게이트에서의 공간을 늘리기 위해 7-Mode 디스크 쉘프의 스페어 디스크만 추가해야 합니다. '-disklist' 매개 변수를 사용하여 스페어 디스크를 추가해야 합니다('-diskcount' 매개 변수는 사용할 수 없습니다).



 a| 
전환된 볼륨을 SVM 루트 볼륨으로 지정
 a| 
전환된 볼륨에서 'volume make-vsroot' 명령을 실행할 수 없습니다.

|===


== 권장되지 않는 작업입니다

|===
| 작동 | 롤백 전 수정 조치 


 a| 
Aggregate 재배치

전환된 애그리게이트의 소유권이 HA 파트너로 변경됩니다.
 a| 
7-Mode 전환 툴은 프로젝트에 저장된 타겟 노드 매핑 정보를 기반으로 애그리게이트를 7-Mode 컨트롤러에 매핑하므로 롤백 전에 애그리게이트 소유권을 스왑합니다.



 a| 
전환된 애그리게이트에서의 볼륨 생성
 a| 
이러한 볼륨을 삭제하거나 다른 애그리게이트로 이동해야 합니다.



 a| 
애그리게이트 또는 볼륨의 이름을 바꿉니다
 a| 
애그리게이트 또는 볼륨의 이름을 원래 이름으로 바꿉니다.



 a| 
RAID 유형 변경
 a| 
7-Mode로 롤백하려는 경우 RAID 유형은 7-Mode RAID 유형과 일치해야 합니다.

|===
* 관련 정보 *

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]
