---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_parallel.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, primary, secondary, system, snapmirror, relationship, parallel 
summary: 7-Mode SnapMirror 관계의 볼륨이 포함된 운영 HA 쌍과 2차 HA 쌍을 병렬로 전환할 수 있습니다. 그런 다음 clustered Data ONTAP에서 전환 후 볼륨 SnapMirror 관계를 수동으로 설정해야 합니다. 전환 후에도 베이스라인을 다시 설정하지 않고 SnapMirror 관계가 유지됩니다. 
---
= SnapMirror 관계의 운영 및 2차 시스템을 병렬로 전환
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode SnapMirror 관계의 볼륨이 포함된 운영 HA 쌍과 2차 HA 쌍을 병렬로 전환할 수 있습니다. 그런 다음 clustered Data ONTAP에서 전환 후 볼륨 SnapMirror 관계를 수동으로 설정해야 합니다. 전환 후에도 베이스라인을 다시 설정하지 않고 SnapMirror 관계가 유지됩니다.

SnapMirror 관계를 전환하기 위해 소스 및 타겟 클러스터를 준비해야 합니다.

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[볼륨 SnapMirror 관계를 전환하기 위한 클러스터 준비]

동일한 컷오버 윈도우에서 2차 HA 쌍과 1차 HA 쌍 모두를 전환해야 합니다.

.단계
. 7-Mode 전환 툴에서 7-Mode 볼륨 SnapMirror 관계의 운영 볼륨과 2차 볼륨이 포함된 2개의 HA 쌍에서 복사본 없이 전환을 수행하십시오.
+
2차 볼륨이 포함된 7-Mode HA 쌍을 전환하기 전에 7-Mode SnapMirror 관계를 위한 수동 개입이 필요하지 않습니다. 따라서 7-Mode 보조 볼륨이 읽기 전용 볼륨으로 ONTAP에 전환되도록 합니다.

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[복사 없는 전환을 사용하여 7-Mode 애그리게이트를 전환할 수 있습니다]

. 전환된 운영 볼륨과 2차 볼륨이 포함된 SVM 간에 인터클러스터 SVM 피어 관계를 생성합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["시스템 관리"]

. 전환된 운영 볼륨과 2차 볼륨 사이에 볼륨 SnapMirror 관계를 생성합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html["볼륨 재해 복구 빠른 준비"]

. 대상 볼륨에서 SnapMirror 관계의 소스 볼륨과 타겟 볼륨을 다시 동기화합니다.
+
'* SnapMirror 재동기화 * '

+

IMPORTANT: 소스 볼륨과 타겟 볼륨 사이에 공통 스냅샷 복사본이 하나 이상 있어야 합니다.

+
* 문제 해결: * 공통 스냅샷 복사본이 8.1 이전 버전의 Data ONTAP 릴리즈에서 생성된 경우 SnapMirror 재동기화가 실패합니다. 고급 권한 수준에서 '-fs-version' 매개 변수를 'volume snapshot show' 명령과 함께 사용하여 스냅샷 복사본이 생성된 릴리즈를 볼 수 있습니다. 이 문제가 발생하면 SnapMirror 관계를 끊은 다음 재동기화를 수행하십시오.

. SnapMirror 데이터 전송 상태를 모니터링합니다.
+
``SnapMirror 쇼 *’

+

IMPORTANT: 재동기화가 성공적으로 완료될 때까지 소스 볼륨과 타겟 볼륨에서 볼륨 이동 또는 SnapMirror 중단 등의 작업을 수행하면 안 됩니다. 재동기화가 중단되지 않고 성공적으로 완료되지 않았는지 확인합니다. 그렇지 않으면 볼륨이 정합성이 보장되지 않는 상태가 될 수 있습니다.

. 보조 프로젝트의 전이를 커밋한 다음 기본 프로젝트를 커밋합니다.
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[복사 없는 전환 프로젝트 커밋]



* 관련 정보 *

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]

https://docs.netapp.com/us-en/ontap/["시스템 관리자"]
