---
permalink: copy-free/task_performing_a_transition_rollback.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, roll, back, project 
summary: 전환된 Aggregate가 커밋되기 전에 무복제 전환 단계 중 아무 단계에서나 7-Mode로 되돌리려는 경우 전환을 롤백할 수 있습니다. 롤백은 수동 작업입니다. 7-Mode 전환 툴을 사용하여 롤백을 위해 수행해야 하는 수동 단계를 생성할 수 있습니다. 
---
= 복사 없는 전환 프로젝트를 롤백하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환된 Aggregate가 커밋되기 전에 무복제 전환 단계 중 아무 단계에서나 7-Mode로 되돌리려는 경우 전환을 롤백할 수 있습니다. 롤백은 수동 작업입니다. 7-Mode 전환 툴을 사용하여 롤백을 위해 수행해야 하는 수동 단계를 생성할 수 있습니다.

* 클러스터에서 실행 중인 볼륨 또는 애그리게이트 전환 작업이 없는지 확인해야 합니다.
+
job show-jobtype transition 명령을 사용할 수 있습니다.

* 7-Mode 애그리게이트는 커밋할 수 없습니다.
+

NOTE: 7-Mode Aggregate가 하나만 커밋된 경우에는 롤백을 수행할 수 없습니다.

* 타겟 클러스터 노드가 Takeover 모드에 있지 않아야 합니다.


.단계
. 롤백 사전 검사 * 를 클릭하여 프로젝트가 롤백에 적합한지 확인합니다.
+
사전 점검에서 문제를 보고하는 경우 문제를 수동으로 해결하고 사전 점검 작업을 다시 실행해야 합니다. 예를 들어, 사전 운영 테스트 중에 새 볼륨 또는 LUN을 생성한 경우 수동으로 삭제해야 합니다.

. 롤백 단계 생성 * 을 클릭하여 성공적인 롤백을 위해 수행해야 하는 수동 단계 목록을 생성합니다.
. 수동 단계를 파일에 저장하려면 * CSV로 저장 * 을 클릭합니다.
+
파일에서 롤백 명령을 복사하여 실행할 수 있습니다.

. 롤백할 전환 단계에 따라 필요한 수동 단계를 수행합니다.
+
** * 가져오기 또는 사전 프로덕션 테스트 단계 *
+
... 클러스터에서 롤백 명령을 실행하고 * 확인 * 을 클릭합니다.
... 7-Mode 디스크 쉘프를 7-Mode 컨트롤러에 연결하고, 케이블을 수동으로 확인하고, * Confirm * 을 클릭합니다.
... 7-Mode 컨트롤러에서 롤백 명령을 실행하고 * 확인 * 을 클릭합니다.
... Operations History 탭에서 SVM에 적용된 구성을 확인합니다.
... 툴에서 적용한 모든 구성을 SVM에서 수동으로 제거합니다.


** * 케이블 연결 단계 *
+
... 7-Mode 디스크 쉘프를 7-Mode 컨트롤러에 연결하고, 케이블을 수동으로 확인하고, * Confirm * 을 클릭합니다.
+
7-Mode 케이블 연결이 프로젝트 시작 시점에 있었던 것과 일치하는지 확인해야 합니다.

+

NOTE: Config Advisor를 사용하여 케이블 연결을 확인해야 합니다.

... 7-Mode 컨트롤러에서 롤백 명령을 실행하고 * 확인 * 을 클릭합니다.
... 툴에서 적용한 모든 구성을 SVM에서 수동으로 제거합니다.
+
Operations History 탭에서 SVM에 적용된 구성을 확인할 수 있습니다.



** * 내보내기 단계 *
+
... 7-Mode 컨트롤러에서 롤백 명령을 실행하고 * 확인 * 을 클릭합니다.
... 툴에서 적용한 모든 구성을 SVM에서 수동으로 제거합니다.
+
Operations History 탭에서 SVM에 적용된 구성을 확인할 수 있습니다.



** * SVM 프로비저닝 단계 *
+
툴에서 적용한 모든 구성을 SVM에서 수동으로 제거합니다.

+
Operations History 탭에서 SVM에 적용된 구성을 확인할 수 있습니다.



+
xref:task_running_manual_steps_for_rolling_back_transition.adoc[전환을 롤백하는 수동 단계]

. 모든 수동 단계를 완료한 후 7-Mode 전환 도구에서 * 7-Mode * 확인 을 클릭하여 7-Mode 컨트롤러가 데이터 제공 준비가 되었는지 확인합니다.

