---
permalink: copy-free/task_applying_svm_configurations.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, apply, svm, configurations 
summary: 'SVM 프로비저닝 단계 전에 일부 구성을 수동으로 적용해야 합니다. 그런 다음 7-Mode 컨트롤러(/etc 디렉토리에 있는 파일\) 또는 vFiler 유닛 레벨에서 정의된 모든 구성을 툴을 사용하여 매핑된 SVM에 적용할 수 있습니다.' 
---
= SVM 구성 적용
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM 프로비저닝 단계 전에 일부 구성을 수동으로 적용해야 합니다. 그런 다음 7-Mode 컨트롤러(이하 '/etc' 디렉토리에 있는 파일) 또는 vFiler 유닛 레벨에서 정의된 모든 구성을 이 툴을 사용하여 매핑된 SVM에 적용할 수 있습니다.

모든 구성을 타겟 SVM으로 이전하지 않으려면 SVM에서 제외할 구성의 속성을 설정해야 합니다.

xref:task_customizing_configurations_for_transition.adoc[7-Mode 구성의 전환 사용자 지정]

* NFS 엑스포트, CIFS 공유, LUN 매핑 등의 구성은 SVM 프로비저닝 단계의 SVM에 적용되지 않습니다.
* SVM 프로비저닝 단계에서 SVM의 툴을 통해 다음 구성이 적용됩니다.
+
** * 이름 서비스 *
+
*** DNS 구성
*** LDAP 구성
*** NIS 구성
*** 네임 서비스 스위치 구성
*** 호스트 구성
*** Unix 사용자 및 그룹
*** 넷그룹 구성


** * 네트워킹 *
+
*** 전환을 위해 선택한 기존 7-Mode IP 주소는 관리 중단 상태로 생성됩니다.
+
가져오기 단계에서는 이러한 IP 주소가 관리 설정 상태로 구성됩니다.

*** 새 IP 주소는 관리 작동 상태로 생성됩니다.


** * NFS *
+
NFS 옵션

** CIFS *
+
*** CIFS 기본 DC 구성입니다
*** 사용자 매핑 구성
*** Widelink 구성
*** CIFS 옵션
*** 구성을 감사합니다


** * SAN *
+
FC 및 iSCSI 서비스

+
[IMPORTANT]
====
이 작업이 성공적으로 완료된 후에는 다시 실행할 수 없습니다.

따라서 이 작업 후 7-Mode 컨트롤러 레벨 구성을 변경하는 경우 내보내기 단계 전에 구성을 타겟 SVM으로 수동으로 전환해야 합니다. 예를 들어, 7-Mode 컨트롤러에 새 vFiler 유닛을 추가하고 이 작업 후에 SVM에 매핑할 경우 해당 vFiler 유닛의 구성을 매핑된 SVM으로 수동으로 전환해야 합니다. 또 다른 예로는 SVM 프로비저닝 단계 후 7-Mode 컨트롤러에 UNIX 사용자를 추가하는 경우 매핑된 SVM에서 이러한 UNIX 사용자를 수동으로 생성해야 합니다.

====




.단계
. SVM 구성 적용 * 을 클릭하여 7-Mode 구성을 타겟 SVM에 적용합니다.
+
이 작업에 대한 중요한 고려 사항을 나열하는 확인 메시지가 표시됩니다.

. 계속하려면 * 예 * 를 클릭하십시오.
. 작업이 완료된 후 다음 단계를 수행하십시오.
+
.. 작업 결과를 파일로 저장하려면 * CSV로 저장 * 을 클릭합니다.
.. 프로젝트 로그 수집 * 을 클릭하여 모든 전환 로그 파일의 백업을 만듭니다.
+
각 전환 작업 후에 로그 파일을 저장하는 것이 가장 좋습니다.

.. 닫기 * 를 클릭하여 작업 결과 창을 닫습니다.


+
작업을 완료하는 데 시간이 오래 걸리는 경우 * 백그라운드에서 실행 * 을 클릭하여 작업 결과 창을 종료할 수 있습니다. 작업이 백그라운드에서 실행 중일 때는 프로젝트를 편집하거나 다른 작업을 수행하지 않아야 합니다. 그런 다음 작업 내역 탭에서 작업 결과를 볼 수 있습니다.

. 수동으로 타겟 SVM에 적용되는 구성을 확인 및 테스트하고 필요한 변경을 수행합니다.
. 외부 이름 서버에 대한 연결을 수동으로 확인합니다.

