---
permalink: copy-free/task_generating_an_assessment_report_by_adding_systems_to_7mtt.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, assessment, report, add, transition, tool 
summary: 7-Mode 전환 툴에 시스템을 추가하여 컨트롤러, 호스트, FC 스위치의 인벤토리 정보를 수집할 수 있습니다. 그런 다음 평가 보고서를 생성하여 해당 시스템의 기능을 평가하고, 전환을 위해 선택한 ONTAP 버전에서 어떻게 작동하는지를 확인할 수 있습니다. 
---
= 7-Mode 전환 툴에 시스템을 추가하여 평가 보고서 생성
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode 전환 툴에 시스템을 추가하여 컨트롤러, 호스트, FC 스위치의 인벤토리 정보를 수집할 수 있습니다. 그런 다음 평가 보고서를 생성하여 해당 시스템의 기능을 평가하고, 전환을 위해 선택한 ONTAP 버전에서 어떻게 작동하는지를 확인할 수 있습니다.

* 스토리지 시스템 및 호스트의 사용자 이름은 readme 파일에 나열된 명령을 실행할 수 있는 충분한 권한이 있어야 합니다.
+
readme 파일은 '_7-Mode_Transition_Tool_Installed_location\bin\ICT'에 있습니다.

* 전환 평가를 위해 7-Mode 시스템, 호스트 및 FC 스위치를 준비해야 합니다.
* Windows 시스템을 평가하려면 도메인 사용자 계정이 있어야 합니다.
* 평가를 위해 여러 시스템을 추가하는 경우 ASCII 또는 UTF-8 형식으로 인코딩된 텍스트 파일을 만들어야 하며 시스템 세부 정보를 한 줄에 하나씩 포함해야 합니다.
+
각 시스템 세부 정보는 다음 형식이어야 합니다.

+
((ONTAP|Windows|VMware|Linux|Cisco|Brocade):/[(_USER|DOMAIN_USER_)[_:PASSWORD_]@](_HOST_NAME|IP_)

* 7-Mode Transition Tool이 설치 및 실행되는 시스템에서 컨트롤러 또는 호스트에 액세스할 수 있어야 합니다.
* 통합 문서에 이러한 기능에 대한 인벤토리 정보가 포함될 수 있도록 모든 기능을 구성하거나 해당 라이센스를 활성화해야 합니다.
* 스토리지 시스템의 사용자 이름에 인벤토리 정보를 수집할 수 있는 충분한 관리 권한이 있어야 합니다.
* CIFS 공유 이름, 사용자 이름 및 그룹 이름과 같은 모든 호스트 이름 및 스토리지 시스템 구성은 UTF-8 형식이어야 합니다.


7-Mode Transition Tool 서비스 또는 이 도구가 설치된 시스템이 다시 시작되면 도구에 추가된 시스템 세부 정보가 손실되고 시스템이 다시 도구에 추가되어야 합니다.

.단계
. 전환 평가를 위해 최신 상호 운용성 매트릭스(IMT) 데이터를 사용하려는 경우:
+
.. 상호 운용성 매트릭스에서 IMT 데이터를 다운로드한 다음 저장합니다.
+
... 보고서 메뉴에서 * 일일 내보내기 완료 * 를 클릭합니다.
... 일일 내보내기 완료 대화 상자의 검색 필드에 FAS 를 입력합니다.
... ONTAP SAN 호스트 Excel 파일을 다운로드한 다음 저장합니다.https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"]


.. CLI에서 transition IMT import 명령을 사용하여 IMT 데이터를 가져옴
.. transition IMT show 명령을 사용하여 가져오기가 성공했는지 확인합니다.
+
* 문제 해결: * IMT 데이터 가져오기 작업이 실패할 경우 'transition IMT restore' 명령을 사용하여 이전 데이터로 되돌릴 수 있습니다.



. 7-Mode 전환 툴에 로그인한 다음 홈 페이지에서 * 수집 및 평가 * 를 클릭합니다.
. 시스템 추가 * 를 클릭합니다.
. 시스템 추가 창에서 다음 작업 중 하나를 수행합니다.
+
** 단일 시스템 추가:
+
... 시스템의 FQDN(정규화된 도메인 이름) 또는 IP 주소를 입력합니다.
... 지정된 시스템의 사용자 이름과 암호를 입력합니다.
... 시스템 유형을 선택합니다.
+
**** Data ONTAP 스토리지 시스템
**** 호스트: Microsoft Windows, Red Hat Linux Enterprise 및 VMware ESXi
**** FC 스위치: Cisco 및 Brocade




** 찾아보기 * 를 클릭한 다음 여러 시스템의 자격 증명이 포함된 텍스트 파일을 선택하여 여러 시스템을 추가합니다.


. 추가 * 를 클릭합니다.
+
시스템의 평가 상태가 준비인 경우 해당 시스템에 대한 전환 평가를 수행할 수 있습니다.

. 전환 평가 보고서 생성:
+
.. 전환 평가를 위한 시스템을 선택하십시오.
.. 전환 평가 보고서 작성 * 을 클릭합니다.
.. 전환 평가 보고서 생성 대화 상자에서 타겟 클러스터의 Data ONTAP 버전을 선택합니다.
.. 보고서의 파일 이름에 대한 접두사를 지정합니다.
.. 보고서 생성 * 을 클릭합니다.


+
평가 워크북("AssessmentWorkbook"이 추가된 보고서 이름)과 평가 핵심 요약("AssessmentExecutiveSummary"가 추가된 보고서 이름) 보고서가 XML 형식으로 생성됩니다.

+
+ "...etc/webapp/transition-gui/TMC" 폴더에서 평가 보고서를 생성하는 데 사용되는 평가 워크북, 평가 요약 및 재고 XML 파일에 액세스할 수 있습니다.

. Microsoft Excel에서 평가 워크북을 보고 Microsoft Office 2007 이상 버전을 사용하여 Microsoft Word의 평가 요약 정보를 확인합니다.
+
평가 워크북에서 CFT(Transition 타당성), 구성 사전 점검 요약, 구성 사전 점검 세부 정보, CFT 사전 점검 요약 탭에서 복사를 위한 전환 평가 세부 정보를 참조하십시오.

+
평가 핵심 요약에서 컨트롤러 레벨 평가에 대한 자세한 내용은 Copy-Free Transition 타당성 섹션을 참조하십시오.

+
평가 통합 문서를 보려면 Excel에서 매크로를 사용하도록 설정해야 할 수 있습니다.

+
평가 워크북의 데이터 수집 요약에서 시스템의 액세스 상태가 '실패'인 경우 해당 시스템의 인벤토리 정보가 유효하지 않습니다. 평가 내용 요약에서 이 시스템의 일부 필드 값은 평가되지 않음 으로 표시됩니다.


