---
permalink: copy-free/task_exporting_7_mode_system_and_hardware_information.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, exporte, storage, configurations, halt 
summary: 전환에 대한 컷오버 기간은 엑스포트 단계에서 시작합니다. 이 단계에서는 7-Mode 시스템에서 시스템 정보, 디스크 쉘프 세부 정보 및 스토리지 구성을 수집한 다음 7-Mode 스토리지 시스템을 중단합니다. 
---
= 스토리지 구성 내보내기 및 7-Mode 시스템 중지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전환에 대한 컷오버 기간은 엑스포트 단계에서 시작합니다. 이 단계에서는 7-Mode 시스템에서 시스템 정보, 디스크 쉘프 세부 정보 및 스토리지 구성을 수집한 다음 7-Mode 스토리지 시스템을 중단합니다.

* 서비스 프로세서(SP) 또는 원격 LAN 모듈(RLM)은 7-Mode 시스템에서 IPv4 주소로 구성해야 합니다.
* 모든 클라이언트는 NFS 엑스포트 마운트 해제, CIFS 공유 연결 해제, SAN 호스트 종료 등을 통해 7-Mode 시스템에서 분리되어 있어야 하지만, 해당 NAS 및 SAN 서비스는 7-Mode 시스템에서 실행 중이어야 합니다.
+

IMPORTANT: 프로토콜 서비스는 7-Mode 스토리지 시스템에서 프로토콜 구성을 수집하는 데 필요하기 때문에 어떤 프로토콜 서비스도 중지해서는 안 됩니다.

* 이 작업 중에 7-Mode 볼륨에 쓴 데이터는 모두 손실됩니다.
* 이 작업 중에는 7-Mode 시스템에서 관리 작업을 수행할 수 없습니다.
* 도구는 내보내기 단계에서 다음 작업을 수행합니다.
+
** 모든 볼륨 및 스토리지 구성을 수집합니다
** 전환 중인 각 애그리게이트의 스냅샷 복사본을 생성합니다
+
전환 단계 중 어느 단계에서든 7-Mode로 복원하려는 경우 이 스냅샷 복사본이 복원 작업에 사용됩니다.

** 7-Mode 컨트롤러를 유지보수 모드로 부팅합니다
** 7-Mode 컨트롤러에서 디스크 소유권을 제거합니다
** 타겟 클러스터 노드에서 디스크 자동 할당을 해제합니다




.단계
. 내보내기 및 중지 * 를 클릭합니다.
+
이 작업에 대한 중요한 고려 사항을 나열하는 메시지가 표시됩니다.

. 클라이언트 액세스가 끊겼는지 확인 * 확인란을 클릭합니다.
. 내보내기 및 중지 작업을 계속하려면 * 예 * 를 클릭합니다.
+
작업 결과가 표시됩니다.

. 작업이 완료될 때까지 기다린 후 다음 단계를 수행하여 작업 결과를 저장하고 도구 로그를 수집합니다.
+
.. 작업 결과를 파일로 저장하려면 * CSV로 저장 * 을 클릭합니다.
.. 모든 전환 로그 파일의 백업을 만들려면 * Collect Tool Logs * 를 클릭합니다.
+
각 전환 작업 후에 로그 파일을 저장하는 것이 가장 좋습니다.

.. 닫기 * 를 클릭하여 작업 결과 창을 닫습니다.


+
작업을 완료하는 데 시간이 오래 걸리는 경우 * 백그라운드에서 실행 * 을 클릭하여 작업 결과 창을 종료할 수 있습니다. 작업이 백그라운드에서 실행 중일 때는 프로젝트를 편집하거나 다른 작업을 수행하지 않아야 합니다. 그런 다음 작업 내역 탭에서 작업 결과를 볼 수 있습니다.


