---
permalink: copy-free/task_testing_workloads_and_applications.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, test, workload, application 
summary: 사전 운영 환경에서 모든 워크로드와 애플리케이션을 수동으로 테스트해야 합니다. 그런 다음 프로젝트를 커밋하기 전에 롤백이 필요한지 여부를 평가하기 위해 잠시 동안 생산을 시작할 수 있습니다. 
---
= 워크로드 및 애플리케이션 테스트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사전 운영 환경에서 모든 워크로드와 애플리케이션을 수동으로 테스트해야 합니다. 그런 다음 프로젝트를 커밋하기 전에 롤백이 필요한지 여부를 평가하기 위해 잠시 동안 생산을 시작할 수 있습니다.

전환된 애그리게이트에는 5% 이상의 사용 가능한 물리적 공간이 있어야 합니다.


NOTE: 모범 사례는 전환된 애그리게이트에서의 사용 가능한 공간이 20% 이상 확보되는 것입니다.

일부 작업은 사전 프로덕션 테스트 중에 제한됩니다.

xref:concept_restrictions_during_preproduction_testing.adoc[사전 프로덕션 테스트 중 제한 사항]

.단계
. 클라이언트를 전환된 볼륨에 연결합니다.
. SAN 워크로드가 있는 경우 SAN 호스트에서 전환 후 호스트 수정 작업을 수행합니다.
+
http://["SAN 호스트 전환 및 수정"]

. 전환된 데이터와 구성을 사용하는 모든 워크로드와 애플리케이션을 테스트합니다.
. 7-Mode Transition Tool 대시보드의 애그리게이트 탭에서 전환된 애그리게이트의 사용 가능한 물리적 공간이 부족하지 않은지 확인하여 전환된 애그리게이트가 공간이 부족하지 않은지 확인합니다.
+
* 문제 해결: * 전환된 애그리게이트에서의 공간이 부족할 경우 디스크를 추가할 수 있습니다.

+
.. 고급 권한 수준(+' * set-privilege advanced * ')에 로그인합니다
.. 7-Mode 디스크 쉘프에서 스페어 디스크를 선택하고 디스크를 추가하여 전환된 애그리게이트에서의 공간을 늘립니다. + " * storage aggregate add-disks-aggregate_agr_name_-disklist_disk1_ * '
+
7-Mode 스페어 디스크를 사용할 수 없는 경우 클러스터 노드의 디스크 쉘프에서 스페어 디스크를 사용할 수 있지만, 그렇게 하면 롤백 프로세스가 복잡해집니다.





운영 데이터 서비스를 시작할 수 있습니다.

[IMPORTANT]
====
운영 환경에서 잠시 동안 데이터를 제공할 수 있으므로 운영 환경에서 워크로드가 올바르게 작동하고 7-Mode로 롤백할 필요가 없습니다. 이 단계를 연장해서는 안 되며 다음과 같은 이유로 무복사 전이 프로젝트 커밋을 지연해서는 안 됩니다.

* 전환된 애그리게이트에서의 공간이 부족될 가능성은 새 데이터가 볼륨에 쓰일 때 증가합니다.
* 이 단계 동안 볼륨에 기록된 새 데이터는 롤백 중에 사용할 수 없습니다.


====
* 관련 정보 *

xref:concept_reverting_a_copy_free_transition_project.adoc[7-Mode로 전환 롤백 수행]

http://["ONTAP 9 명령"]
