---
permalink: copy-free/task_rehosting_volumes_from_different_svms_to_a_single_svm.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, rehost, volumes, svm 
summary: '볼륨 재호스트를 사용하면 데이터 복사 없이 전환된 볼륨을 한 SVM에서 다른 SVM으로 마이그레이션할 수 있습니다. 재호스트 작업을 통해 FC LUN이 있는 모든 볼륨을 단일 SVM에 통합할 수 있으므로 7-Mode 단일 시스템 이미지\(SSI\) 의미가 보존됩니다. 또한 전환된 NAS 볼륨을 다시 호스팅할 수 있습니다.' 
---
= 전환된 볼륨을 다른 SVM으로 재호스팅
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
볼륨 재호스트를 사용하면 데이터 복사 없이 전환된 볼륨을 한 SVM에서 다른 SVM으로 마이그레이션할 수 있습니다. 재호스트 작업을 통해 FC LUN이 있는 모든 볼륨을 단일 SVM에 통합할 수 있으므로 7-Mode SSI(단일 시스템 이미지) 의미가 보존됩니다. 또한 전환된 NAS 볼륨을 다시 호스팅할 수 있습니다.

* 재호스팅할 볼륨이 온라인 상태여야 합니다.
* 볼륨 이동 또는 LUN 이동 같은 볼륨 관리 작업이 실행되고 있지 않아야 합니다.
* 재호스팅 중인 볼륨에 대한 데이터 액세스를 중지해야 합니다.
+
재호스팅은 중단을 야기하는 작업입니다.



다음 볼륨 정책, 정책 규칙 및 구성은 소스 볼륨에서 손실되며 재호스트 작업 후 재호스트된 볼륨에서 수동으로 재구성해야 합니다.

* 볼륨 및 qtree 엑스포트 정책
* 안티바이러스 정책
* 볼륨 효율성 정책
* QoS(서비스 품질) 정책
* 스냅샷 정책
* 할당량 규칙
* CIFS 공유
* 포트셋 관련 igroup


.단계
* * FC 및 iSCSI 볼륨 재호스팅 *
+
.. 고급 권한 수준(+' * set-privilege advanced * ')으로 전환합니다
.. 대상 SVM에서 볼륨 재호스팅:
+
|===
| 원하는 작업 | 다음 명령을 실행합니다... 


 a| 
재호스팅 후 LUN 매핑을 해제합니다
 a| 
'* 볼륨 재호스팅 -vserver_source_svm_-volume_vol_name_-destination-vserver_destination_svm_-force –unmap -LUNs true *



 a| 
재호스팅 후 LUN을 동일한 igroup에 다시 매핑합니다
 a| 
'* volume rehost-vserver_source_svm_-volume_vol_name_-destination-vserver_destination_svm_-auto-remap-LUNs true *

|===


* * NFS 볼륨 재호스팅 *
+
.. NFS 엑스포트 정책에 대한 정보를 기록합니다.
.. 상위 볼륨에서 볼륨을 마운트 해제합니다: + " * 볼륨 마운트 해제 * "
.. 고급 권한 수준(* set-Privilege advanced*)으로 전환합니다
.. 대상 SVM에서 볼륨을 재호스트합니다. + ` * volume rehost -vserver_source_svm_-volume_vol_name_-destination-vserver_destination_svm_ * '
+
대상 SVM의 기본 엑스포트 정책이 재호스팅 볼륨에 적용됩니다.

.. '* vserver export-policy create*' 엑스포트 정책을 생성합니다
.. 재호스트된 볼륨의 내보내기 정책을 사용자 정의 내보내기 정책(+' * volume modify * ')로 업데이트합니다
.. 대상 SVM의 적절한 접합 경로 아래에 + " * 볼륨 마운트 * "를 사용하여 볼륨을 마운트합니다
.. 대상 SVM에서 NFS 서비스가 실행 중인지 확인합니다. + " * vserver NFS status * "
.. 재호스트된 볼륨에 대한 NFS 액세스를 재개합니다.
+
볼륨 액세스 경로(LIF 및 접합 경로)가 변경되었으므로, NFS 클라이언트 자격 증명과 LIF 구성을 업데이트하여 대상 SVM LIF를 반영해야 합니다.



+
https://["NFS 관리"]

* * CIFS 볼륨 재호스팅 *
+
.. CIFS 공유에 대한 정보를 기록합니다.
.. 상위 볼륨에서 볼륨을 마운트 해제합니다: + " * 볼륨 마운트 해제 * "
.. 고급 권한 수준(+' * set-privilege advanced * ')으로 전환합니다
.. 대상 SVM에서 볼륨을 재호스트합니다. + ` * volume rehost -vserver_source_svm_-volume_vol_name_-destination-vserver_destination_svm_ * '
.. 대상 SVM의 적절한 접합 경로 아래에 + " * 볼륨 마운트 * "를 사용하여 볼륨을 마운트합니다
.. 재호스트된 볼륨에 대한 CIFS 공유를 생성합니다: + " * vserver CIFS share create * "
.. 소스 SVM과 타겟 SVM 간에 DNS 도메인이 다를 경우 새 사용자와 그룹을 생성합니다.
.. 새로 대상 SVM LIF와 재호스팅 볼륨의 접합 경로로 CIFS 클라이언트를 업데이트합니다.


+
http://["SMB/CIFS 관리"]

* * SnapMirror 관계에서 볼륨 재호스팅 *
+
.. SnapMirror 관계 유형: + " * SnapMirror show * "를 기록합니다
.. 대상 클러스터에서 SnapMirror 관계 + " * SnapMirror delete * "를 삭제합니다
+

IMPORTANT: SnapMirror 관계를 중단해서는 안 됩니다. 그렇지 않으면 대상 볼륨의 데이터 보호 기능이 손실되고 재호스팅 작업 후 관계를 다시 설정할 수 없습니다.

.. 소스 클러스터에서 SnapMirror 관계 정보 + " * SnapMirror 릴리즈 * "를 해제합니다
+
relationship-info-only 매개 변수를 true로 설정하여 스냅샷 복사본이 삭제되지 않고 소스 관계 정보만 제거됩니다.

.. 고급 권한 수준(+' * set-privilege advanced * ')으로 전환합니다
.. 대상 SVM에서 볼륨을 재호스트합니다. + ` * volume rehost -vserver_source_svm_-volume_vol_name_-destination-vserver_destination_svm_ * '
.. 소스 및 대상 SVM 간에 SVM 피어 관계를 생성합니다. + " * vserver peer create * "
.. 소스 볼륨과 타겟 볼륨 간의 SnapMirror 관계 생성: + " * SnapMirror create * "
+
재호스트된 볼륨은 SnapMirror 관계의 소스 또는 대상이 될 수 있습니다.

.. 데이터 보호 관계를 + " * SnapMirror 재동기화 * "로 재동기화합니다


+
http://["데이터 보호"]



다음 단계를 수행하여 재호스트된 볼륨의 자동 볼륨 워크로드를 수동으로 생성해야 합니다.

. SVM을 위한 사용자 정의 정책 그룹을 생성합니다.
+
'* QoS policy-group create-vserver_destination-vserver_-policy-group_policy-group-name_*'

. 재호스트된 볼륨에 QoS 정책 그룹을 할당합니다.
+
'* volume modify -vserver_destination -vserver_-volume_re호스팅 -volume_-qos-policy-_group policy -group -name_*'



재호스트된 볼륨에서 정책 및 관련 규칙을 수동으로 재구성해야 합니다.


NOTE: 재호스팅 작업이 실패하면 소스 볼륨에서 볼륨 정책 및 관련 규칙을 다시 구성해야 할 수 있습니다.

* 관련 정보 *

http://["ONTAP 9 명령"]
