---
permalink: copy-free/task_importing_7_mode_data_to_clustered_ontap.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, import, data 
summary: 케이블 연결을 확인하고 문제를 해결한 후 가져오기 작업을 실행할 수 있습니다. 이 단계에서는 디스크 소유권이 매핑된 클러스터 노드에 할당되고 7-Mode 애그리게이트, 볼륨 및 LUN은 ONTAP 형식으로 변환됩니다. 모든 볼륨 레벨 및 LUN 레벨 구성도 적용됩니다. 
---
= 7-Mode 데이터를 ONTAP로 가져오는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
케이블 연결을 확인하고 문제를 해결한 후 가져오기 작업을 실행할 수 있습니다. 이 단계에서는 디스크 소유권이 매핑된 클러스터 노드에 할당되고 7-Mode 애그리게이트, 볼륨 및 LUN은 ONTAP 형식으로 변환됩니다. 모든 볼륨 레벨 및 LUN 레벨 구성도 적용됩니다.

이 단계에서 도구는 다음 작업을 수행합니다.

* 7-Mode 디스크는 매핑된 타겟 클러스터 노드에 할당됩니다.
* 모든 7-Mode 애그리게이트, 볼륨 및 LUN은 ONTAP 형식으로 변환됩니다.
* 전환을 위해 선택한 7-Mode IP 주소는 관리 설정 상태의 SVM에서 구성됩니다.
* 다음 설정이 적용됩니다.
+
** NFS 엑스포트 규칙
** CIFS 공유
** CIFS ACL 구성
** CIFS 홈 디렉토리 구성
** CIFS 심볼 링크
** 할당량 구성
** Snapshot 복제본 스케줄
** LUN 매핑 및 igroup




.단계
. 가져오기 * 를 클릭합니다.
+
* 문제 해결: * 애그리게이트에 디스크가 없으면 애그리게이트의 성능이 저하되어 가져오기 작업이 실패합니다. 누락된 디스크 수가 허용되는 한도 내에 있는 경우 7-Mode Transition Tool CLI에서 다음 명령을 실행하여 저하된 애그리게이트를 계속 전환할 수 있습니다.

+
' * transition CFT aggregate degraded-transition-p_project-name_-n_7-mode-host-name_-a_7-mode-aggregate-name_-I ACKNOWLEDGE *

+
그런 다음 케이블링 확인 작업을 다시 실행하고 전환을 계속할 수 있습니다. 애그리게이트가 전환된 후 타겟 클러스터 노드에 RAID 그룹을 재구성할 충분한 스페어 디스크가 있는지 확인해야 합니다.

+
이 작업에 대한 중요한 고려 사항을 나열하는 경고 메시지가 표시됩니다.

. 계속하려면 * 예 * 를 클릭하십시오.
+
작업 결과가 표시됩니다.

. 작업이 완료될 때까지 기다린 후 다음을 수행합니다.
+
.. 작업 결과를 파일로 저장하려면 * CSV로 저장 * 을 클릭합니다.
.. 모든 전환 로그 파일을 백업하려면 * Collect Tool Logs * 를 클릭합니다.
+
각 전환 작업 후에 로그 파일을 저장하는 것이 가장 좋습니다.

.. 닫기 * 를 클릭하여 작업 결과 창을 닫습니다.


+
작업을 완료하는 데 시간이 오래 걸리는 경우 * 백그라운드에서 실행 * 을 클릭하여 작업 결과 창을 종료할 수 있습니다. 작업이 백그라운드에서 실행 중일 때는 프로젝트를 편집하거나 다른 작업을 수행하지 않아야 합니다. 그런 다음 작업 내역 탭에서 작업 결과를 볼 수 있습니다.


