---
permalink: copy-free/task_expanding_an_aggregate_to_64_bit_format_without_adding_storage.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, expanding, aggregate, 64, bit 
summary: 시스템에 32비트 애그리게이트가 포함된 경우, Data ONTAP 8.3 이상 버전으로 전환하기 전에 7-Mode 시스템에서 64비트 형식으로 확장해야 합니다. Data ONTAP 버전은 32비트 형식을 지원하지 않습니다. 
---
= 64비트 형식으로 애그리게이트 확장
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
시스템에 32비트 애그리게이트가 포함된 경우, Data ONTAP 8.3 이상 버전으로 전환하기 전에 7-Mode 시스템에서 64비트 형식으로 확장해야만 합니다. Data ONTAP 버전은 32비트 형식을 지원하지 않기 때문입니다.

* Aggregate가 32비트 소스 볼륨과 SnapMirror 관계의 타겟 볼륨을 포함하는 경우, 소스 볼륨을 포함하는 애그리게이트를 확장하기 전에 소스 볼륨을 포함하는 애그리게이트를 확장해야 합니다.


SnapMirror 관계에 있는 볼륨의 경우 미러링이 그대로 유지되는 동안 대상 볼륨이 소스 볼륨의 형식을 상속합니다. 확장하는 Aggregate에 소스 볼륨이 32비트 볼륨이고 애그리게이트를 확장하기 전에 미러를 분리할 대상 볼륨이 포함되어 있는 경우 대상 볼륨은 64비트 형식으로 확장됩니다. 하지만 미러를 다시 설정하고 소스 볼륨이 여전히 32비트인 경우 대상 볼륨은 32비트 형식으로 돌아갑니다. 따라서 Aggregate의 모든 32비트 볼륨을 64비트 형식으로 확장하려면 SnapMirror 관계를 다시 설정하기 전에 소스 볼륨이 포함된 Aggregate를 확장해야 합니다.

.단계
. 고급 권한 모드 시작:
+
``한자 세트 어드밴스드 *’’

. 확장 시작:
+
'* aggr 64비트 업그레이드 start_aggr_name_*'

. 적절한 작업을 수행합니다.
+
|===
| 명령을 실행할 경우... | 그러면... 


 a| 
이(가) 성공적으로 시작됩니다
 a| 
다음 단계를 진행합니다.



 a| 
하나 이상의 볼륨에 충분한 공간이 없어 확장할 수 없음을 나타냅니다
 a| 
'grow-all' 옵션을 추가하여 명령을 재시도하십시오.



 a| 
다른 이유로 확장을 완료할 수 없음을 나타냅니다
 a| 
오류 메시지에 설명된 문제에 따라 적절한 조치를 수행합니다.

|===
. 확장 상태를 표시합니다.
+
'* aggr 64비트-업그레이드 상태_aggr_name_*'

+
현재 확장 상태가 표시됩니다. 진행 중인 업그레이드가 없다는 메시지가 나타나면 확장이 완료된 것입니다.

. Aggregate의 모든 볼륨이 64비트 형식인지 확인합니다.
+
'* aggr 64bit-upgrade status_aggr_name_-all *'

. 관리 권한 모드로 돌아갑니다: `* priv set admin * '


애그리게이트는 64비트 형식으로 확장됩니다. 하지만 모든 볼륨이 확장되더라도 일부 32비트 Snapshot 복사본이 남아 있을 수 있습니다. 소스 볼륨에 32비트 스냅샷 복사본이 있으면 Data ONTAP 8.3 이상으로 업그레이드하거나 전환할 수 없습니다.
