---
permalink: copy-free/task_transitioning_primary_and_secondary_systems_of_a_snapmirror_relationship_in_staggered_way.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, ha, pairs, snapmirror, relationship, staggered, configuration 
summary: 2차 HA 쌍을 먼저 전환하고 7-Mode 운영 볼륨과 ONTAP 2차 볼륨 사이에 지그재그형 SnapMirror 관계를 설정한 다음, 나중에 운영 HA 쌍으로 전환할 수 있습니다. 
---
= 시차 구성에서 SnapMirror 관계에서 HA 쌍을 전환
:icons: font
:imagesdir: ../media/


[role="lead"]
2차 HA 쌍을 먼저 전환하고 7-Mode 운영 볼륨과 ONTAP 2차 볼륨 사이에 지그재그형 SnapMirror 관계를 설정한 다음, 나중에 운영 HA 쌍으로 전환할 수 있습니다.

SnapMirror 관계를 전환하기 위해 소스 및 타겟 클러스터를 준비해야 합니다.

xref:task_preparing_cluster_for_transitioning_volume_snapmirror_relationships.adoc[볼륨 SnapMirror 관계를 전환하기 위한 클러스터 준비]

.단계
. 7-Mode 전환 툴에서 7-Mode 볼륨 SnapMirror 관계의 2차 볼륨이 포함된 HA 쌍 또는
+
2차 볼륨이 포함된 7-Mode HA 쌍을 전환하기 전에 7-Mode SnapMirror 관계를 위한 수동 개입이 필요하지 않습니다. 따라서 7-Mode 보조 볼륨이 읽기 전용 볼륨으로 ONTAP에 전환되도록 합니다.

+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[복사 없는 전환을 사용하여 7-Mode 애그리게이트를 전환할 수 있습니다]

. 2차 HA 쌍의 사전 커밋 테스트 단계에서 7-Mode 운영 볼륨과 ONTAP 2차 볼륨 간의 재해 복구 관계를 생성합니다.
+
.. 2차 대상 클러스터에서 'vserver peer transition create' 명령을 사용하여 7-Mode 운영 볼륨과 ONTAP 2차 볼륨 간의 SVM 피어 관계를 생성합니다.
.. 'job schedule cron create' 명령을 사용하여 7-Mode SnapMirror 관계에 구성된 일정과 일치하는 작업 일정을 생성합니다.
.. 'napmirror create' 명령을 사용하여 7-Mode 운영 볼륨과 ONTAP 보조 볼륨 사이에 TDP 유형의 SnapMirror 관계를 생성합니다.
.. 'napmirror resync' 명령을 사용하여 ONTAP 보조 볼륨을 재동기화합니다.
+
재동기화가 성공적으로 수행되려면 7-Mode 운영 볼륨과 ONTAP 2차 볼륨 사이에 공통 7-Mode 스냅샷 복사본이 있어야 합니다.



. 전환된 Aggregate 및 볼륨에 대해 필요한 테스트를 수행합니다.
. 7-Mode 전환 툴 에서 2차 HA 2노드에 대한 프로젝트 전환을 커밋합니다.
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[복사 없는 전환 프로젝트 커밋]

. 7-Mode 볼륨 SnapMirror 관계의 기본 볼륨이 포함된 HA 쌍에서 복사를 수행하지 않는 전환을 수행합니다.
+
xref:task_performing_copy_free_transition_of_7_mode_aggregates.adoc[복사 없는 전환을 사용하여 7-Mode 애그리게이트를 전환할 수 있습니다]

. 기본 HA 쌍의 사전 커밋 테스트 단계에서 전환된 2차 볼륨과 1차 볼륨 사이에 SnapMirror 관계를 생성합니다.
+
.. 대상 클러스터에서 전환된 운영 볼륨과 2차 볼륨이 포함된 SVM 간에 인터클러스터 SVM 피어 관계를 생성합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["시스템 관리"]

.. '스냅샷 삭제' 명령을 사용하여 7-Mode 기본 볼륨과 단계에서 생성한 ONTAP 보조 볼륨 간의 TDP SnapMirror 관계를 삭제합니다 <<SUBSTEP_D528769DF8EC49058D1958565914CF47,substep_D528769DF8EC49058D1958565914CF47>>.
.. 단계에서 생성한 cron 작업 일정을 삭제합니다 <<SUBSTEP_EB470706425C45759EAAE8F0A87BA547,하위 단계_EB470706425C45759EAAE8F0A87BA547입니다>>: + ` * job schedule cron delete * '
.. 전환된 운영 볼륨과 2차 볼륨 사이에 볼륨 SnapMirror 관계를 생성합니다.
+
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-sm-ic-cg/home.html["볼륨 재해 복구 빠른 준비"]

.. 대상 볼륨에서 SnapMirror 관계의 소스 볼륨과 타겟 볼륨을 + " * SnapMirror 재동기화 * "로 재동기화합니다
+

IMPORTANT: 소스 볼륨과 타겟 볼륨 사이에 공통 스냅샷 복사본이 하나 이상 있어야 합니다.

+
* 문제 해결: * 공통 스냅샷 복사본이 8.1 이전 버전의 Data ONTAP 릴리즈에서 생성된 경우 SnapMirror 재동기화가 실패합니다. 고급 권한 수준에서 '-fs-version' 매개 변수를 'volume snapshot show' 명령과 함께 사용하여 스냅샷 복사본이 생성되는 릴리즈를 볼 수 있습니다. 이 문제가 발생하면 SnapMirror 관계를 끊은 다음 재동기화를 수행합니다.

.. SnapMirror 데이터 전송 상태 모니터링: + " * SnapMirror show * "
+

IMPORTANT: 재동기화가 성공적으로 완료될 때까지 소스 볼륨과 타겟 볼륨에서 볼륨 이동 또는 SnapMirror 중단 등의 작업을 수행하면 안 됩니다. 재동기화가 중단되지 않고 성공적으로 완료되지 않았는지 확인합니다. 그렇지 않으면 볼륨이 정합성이 보장되지 않는 상태가 될 수 있습니다.



. 기본 프로젝트의 전이를 커밋합니다.
+
xref:task_committing_7_mode_aggregates_to_clustered_ontap_format.adoc[복사 없는 전환 프로젝트 커밋]



* 관련 정보 *

http://docs.netapp.com/us-en/ontap-7mode-transition/snapmirror/index.html["SnapMirror를 사용하여 7-Mode 데이터 전환"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["ONTAP 9 명령"]
