---
permalink: copy-free/task_finding_and_removing_32_bit_data_from_source_volumes_and_snapshot_copies.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, find, remove, volumes, snapshot, copy 
summary: 모든 애그리게이트를 64비트 형식으로 확장했더라도 일부 32비트 또는 혼합 형식의 FlexVol 볼륨 또는 스냅샷 복사본을 그대로 유지할 수 있습니다. Data ONTAP 8.3 이상을 실행하는 클러스터에서 데이터에 액세스하려면 먼저 이러한 볼륨 및 스냅샷 복사본을 제거해야 합니다. 
---
= 32비트 볼륨 및 스냅샷 복사본 찾기 및 제거
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 애그리게이트를 64비트 형식으로 확장했더라도 일부 32비트 또는 혼합 형식의 FlexVol 볼륨 또는 스냅샷 복사본을 그대로 유지할 수 있습니다. Data ONTAP 8.3 이상을 실행하는 클러스터에서 데이터에 액세스하려면 먼저 이러한 볼륨 및 스냅샷 복사본을 제거해야 합니다.

* 시스템의 모든 32비트 애그리게이트를 64비트 형식으로 확장해야 합니다.


32비트 볼륨과 스냅샷 복사본이 포함된 각 애그리게이트에 대해 이 작업의 단계를 반복해야 합니다.

.단계
. 고급 모드 진입:
+
``한자 세트 어드밴스드 *’’

. 애그리게이트에 있는 모든 볼륨의 형식을 표시합니다.
+
'* aggr 64bit-upgrade status_aggr_name_-all *'

+
Aggregate의 각 볼륨은 그 형식과 함께 표시됩니다.

. 각 32비트 또는 혼합 형식 볼륨에 대해 볼륨이 64비트 형식으로 확장되지 않은 이유를 확인한 다음 적절한 조치를 취하십시오.
+
볼륨이 확장되지 않은 이유를 확인할 수 없는 경우 애그리게이트 확장을 다시 시도하십시오.

+
|===
| 볼륨이 다음과 같은 경우 | 그러면... 


 a| 
SnapMirror 관계의 대상입니다
 a| 
소스 볼륨을 포함하는 애그리게이트를 64비트 형식으로 확장합니다.



 a| 
읽기 전용 볼륨임(SnapMirror 대상은 아님)
 a| 
볼륨을 쓰기 가능한 상태로 만들고 확장을 재시도하거나 볼륨을 제거합니다.



 a| 
볼륨 또는 애그리게이트의 사용 가능한 공간이 부족하여 확장할 수 없습니다
 a| 
볼륨 또는 애그리게이트의 여유 공간을 늘리고 확장을 재시도하십시오.

|===
+
Aggregate의 모든 32비트 및 혼합 형식 볼륨은 이제 64비트입니다. 이전 단계를 반복하여 확인할 수 있습니다.

. 시스템에 있는 모든 스냅샷 복사본의 형식을 표시합니다.
+
' * snap list-fs-block-format * '

. snap delete 명령을 사용하여 32비트 스냅샷 복사본을 제거합니다.
+

IMPORTANT: 이렇게 하면 스냅샷 복사본의 데이터가 삭제됩니다. 삭제하기 전에 스냅샷 복사본을 유지하지 않아도 됩니다. 또는 32비트 스냅샷 복사본이 없어질 때까지 기다릴 수 있습니다. 이 시간이 소요되는 시간은 스냅샷 복사본 일정에 따라 다릅니다.

+
스냅샷 복사본이 FlexClone 볼륨의 기본 스냅샷 복사본인 경우 스냅샷 복사본을 제거하기 전에 FlexClone 볼륨을 상위 볼륨에서 분할해야 합니다.

+
모든 32비트 스냅샷 복사본이 제거됩니다. 이전 단계를 반복하여 확인할 수 있습니다.

. 관리 권한 수준으로 돌아가기:
+
``priv set admin *’


