---
permalink: copy-free/task_running_prechecks.html 
sidebar: sidebar 
keywords: ontap, transition, copy, free, runn, prechecks 
summary: 전환을 시작하기 전에 사전 점검을 실행하여 문제를 식별할 수 있습니다. 사전 점검을 통해 7-Mode 소스, ONTAP 타겟 및 구성이 전환에 유효한지 확인합니다. 사전 점검을 원하는 횟수만큼 실행할 수 있습니다. 
---
= 사전 점검 실행
:icons: font
:imagesdir: ../media/


[role="lead"]
전환을 시작하기 전에 사전 점검을 실행하여 문제를 식별할 수 있습니다. 사전 점검을 통해 7-Mode 소스, ONTAP 타겟 및 구성이 전환에 유효한지 확인합니다. 사전 점검을 원하는 횟수만큼 실행할 수 있습니다.

사전 점검은 200가지가 넘는 다양한 점검을 실행합니다. 예를 들어, 이 도구는 볼륨이 온라인 상태이고 시스템 간에 네트워크 액세스가 존재하는 경우와 같은 항목을 검사합니다.

. 대시보드에서 사전 점검을 실행할 프로젝트를 선택합니다.
. 사전 검사 실행 * 을 클릭합니다.
+
사전 점검을 완료한 후 결과 요약이 대화 상자에 표시됩니다.

+

NOTE: 사전 점검을 실행하는 데 일반적으로 몇 분이 걸리지만 사전 점검 단계의 기간은 해결할 수 있는 오류 또는 경고의 수와 유형에 따라 달라집니다.



.단계
. 결과를 필터링하려면 * 유형 필터 적용 * 아래에서 옵션을 선택합니다.
+
** 보안과 관련된 모든 메시지를 보려면 * 오류 *, * 경고 *, * 정보 * 및 * 보안 전용 * 을 선택합니다.
** 보안과 관련된 모든 오류 메시지를 보려면 * 오류 * 및 * 보안 전용 * 을 선택합니다.
** 보안과 관련된 모든 경고 메시지를 보려면** 경고** 및* 보안 전용*을 선택하십시오.
** 보안과 관련된 모든 정보 메시지를 보려면 * 정보 * 및 * 보안 전용 * 을 선택합니다.


. 원시 결과를 CSV(쉼표로 구분된 값) 형식으로 저장하고 결과를 내보내려면 * CSV로 저장 * 을 클릭합니다.
+
전환 중에 수행된 전환 작업과 작업 유형, 상태, 시작 시간, 종료 시간 및 결과를 대시보드 창의 Operation History 탭에서 볼 수 있습니다.



데이터 복사를 시작하기 전에 사전 점검에서 감지한 모든 오류를 해결해야 합니다. 또한 마이그레이션 프로세스를 진행하기 전에 모든 경고를 해결하는 것이 좋습니다. 해결 방법은 경고 메시지의 원본 문제를 해결하거나, 해결 방법을 구현하거나, 문제의 결과를 수락하는 것입니다.
