---
permalink: snapmirror/concept_planning_for_transition.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, plan, clustered, volumes, snapmirror 
summary: 7-Mode 볼륨에서 clustered ONTAP 볼륨으로 데이터를 복사하기 전에, 언제 SnapMirror를 사용하여 전환을 수행해야 하는지 이해하고, 전환을 위해 지원되는 7-Mode 버전 및 지원되는 볼륨에 대한 정보를 검토해야 합니다. 또한 특정한 전환 고려 사항을 알고 있어야 합니다. 
---
= 전환 계획 수립
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode 볼륨에서 clustered ONTAP 볼륨으로 데이터를 복사하기 전에, 언제 SnapMirror를 사용하여 전환을 수행해야 하는지 이해하고, 전환을 위해 지원되는 7-Mode 버전 및 지원되는 볼륨에 대한 정보를 검토해야 합니다. 또한 특정한 전환 고려 사항을 알고 있어야 합니다.

전환 문제가 있는 경우 전환 대상 릴리스에 대한 _릴리스 정보_를 검토해야 합니다.

https://library.netapp.com/ecmdocs/ECMLP2492508/html/frameset.html["ONTAP 9 릴리즈 노트"]

7-Mode와 clustered ONTAP 볼륨 간의 SnapMirror 관계는 다음 릴리즈에서 지원됩니다.

* ONTAP 9.8 이상 릴리스
* ONTAP 9.7P2 이상 9.7 릴리스
* ONTAP 9.6P7 이상 9.6 릴리스
* ONTAP 9.0에서 ONTAP 9.5까지


다음과 같은 경우에 SnapMirror를 사용하여 데이터를 전환할 수 있습니다.

* 7-Mode 전환 툴은 전환 요구사항을 지원하지 않습니다. 예를 들어 7-Mode 전환 툴을 사용하려면 사용자 환경에서 사용할 수 없는 Windows 또는 Linux 호스트가 필요합니다.
+
* 권장 사항: * 7-Mode 전환 툴을 사용하여 7-Mode 볼륨을 전환해야 하는 이유는 이 툴이 전환 가능성을 검증하고 데이터와 함께 모든 프로토콜, 네트워크 및 서비스 구성을 마이그레이션하기 위한 사전 점검을 제공하기 때문입니다.

+
7-Mode 전환 툴을 설치 및 사용하여 사전 점검을 수행한 다음 SnapMirror 명령을 사용하여 7-Mode 볼륨에서 clustered ONTAP 볼륨으로 데이터 마이그레이션을 수행할 수 있습니다.

* 클러스터 및 SVM(스토리지 가상 머신)이 이미 구성되어 있으며 데이터만 7-Mode 볼륨에서 clustered ONTAP 볼륨으로 전환해야 합니다.

