---
permalink: snapmirror/task_transitioning_a_stand_alone_volume.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, stand, alone, volume, snapmirror 
summary: 독립형 볼륨을 전환하려면 SnapMirror 관계 생성, 기본 전송 수행, 증분 업데이트 수행, 데이터 복사 작업 모니터링, SnapMirror 관계 파기 및 7-Mode 볼륨에서 clustered Data ONTAP 볼륨으로 클라이언트 액세스 이동 등이 포함됩니다. 
---
= 독립 실행형 볼륨 전환
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
독립형 볼륨을 전환하려면 SnapMirror 관계 생성, 기본 전송 수행, 증분 업데이트 수행, 데이터 복사 작업 모니터링, SnapMirror 관계 파기 및 7-Mode 볼륨에서 clustered Data ONTAP 볼륨으로 클라이언트 액세스 이동 등이 포함됩니다.

* 클러스터와 SVM이 이미 설정되어 있어야 합니다.
* 전환 준비에 대한 정보를 검토해야 합니다.
+
xref:task_preparing_for_transition.adoc[전환 준비 중]



.단계
. 7-Mode 볼륨에서 clustered Data ONTAP 볼륨으로 데이터 복사:
+
.. 7-Mode 시스템과 SVM 간 SnapMirror 관계의 TCP 윈도우 크기를 구성하려면 'window-size-for-TDP-mirror' 옵션을 사용하여 비동기식 미러 유형의 SnapMirror 정책을 생성하십시오.
+
그런 다음 7-Mode 시스템과 SVM 사이의 TDP SnapMirror 관계에 이 정책을 적용해야 합니다.

+
전환 복사 작업이 더 빨리 완료되도록 SnapMirror 전송 처리량을 높이기 위해 256KB ~ 7MB 범위의 TCP 윈도우 크기를 구성할 수 있습니다. TCP 윈도우 크기의 기본값은 2MB입니다.

+
[listing]
----
cluster1::> snapmirror policy create -vserver vs1 –policy tdp_policy -window-size-for-tdp-mirror 5MB -type async-mirror
----
.. TDP로 관계 유형과 함께 'napmirror create' 명령을 사용하여 7-Mode 시스템과 SVM 간에 SnapMirror 관계를 생성합니다.
+
TCP 윈도우 크기를 구성하기 위한 SnapMirror 정책을 만든 경우 이 SnapMirror 관계에 정책을 적용해야 합니다.

+
[listing]
----
cluster1::> snapmirror create -source-path system7mode:dataVol20 -destination-path vs1:dst_vol -type TDP -policy tdp_policy
Operation succeeded: snapmirror create the relationship with destination vs1:dst_vol.
----
.. 기본 전송을 시작하려면 'napmirror initialize' 명령을 사용합니다.
+
[listing]
----
cluster1::> snapmirror initialize -destination-path vs1:dst_vol
Operation is queued: snapmirror initialize of destination vs1:dst_vol.
----
.. 상태를 모니터링하려면 'napmirror show' 명령을 사용합니다.
+
[listing]
----
cluster1::>snapmirror show -destination-path vs1:dst_vol

                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           **Mirror State: Snapmirrored**
                    Relationship Status: Idle
                File Restore File Count: -
                 File Restore File List: -
                      Transfer Snapshot: -
                      Snapshot Progress: -
                         Total Progress: -
              Network Compression Ratio: -
                    Snapshot Checkpoint: -
                        Newest Snapshot: vs1(4080431166)_dst_vol.1
              Newest Snapshot Timestamp: 10/16 02:49:03
                      Exported Snapshot: vs1(4080431166)_dst_vol.1
            Exported Snapshot Timestamp: 10/16 02:49:03
                                Healthy: true
                       Unhealthy Reason: -
               Constituent Relationship: false
                Destination Volume Node: cluster1-01
                        Relationship ID: 97b205a1-54ff-11e4-9f30-005056a68289
                   Current Operation ID: -
                          Transfer Type: -
                         Transfer Error: -
                       Current Throttle: -
              Current Transfer Priority: -
                     Last Transfer Type: initialize
                    Last Transfer Error: -
                     Last Transfer Size: 152KB
Last Transfer Network Compression Ratio: 1:1
                 Last Transfer Duration: 0:0:6
                     Last Transfer From: system7mode:dataVol20
            Last Transfer End Timestamp: 10/16 02:43:53
                  Progress Last Updated: -
                Relationship Capability: 8.2 and above
                               Lag Time: -
           Number of Successful Updates: 0
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 155648
         Total Transfer Time in Seconds: 6
----
.. Clustered Data ONTAP 볼륨을 수동으로 업데이트할지 또는 SnapMirror 일정을 설정할지 여부에 따라 적절한 작업을 수행합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
전송을 수동으로 업데이트합니다
 a| 
... 'napmirror update' 명령어를 사용한다.
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
----
... 'napmirror show' 명령을 사용하여 데이터 복사 상태를 모니터링합니다.
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----
... 3단계로 이동합니다.




 a| 
예약된 업데이트 전송을 수행합니다
 a| 
... job schedule cron create 명령을 사용하여 업데이트 전송을 위한 스케줄을 생성합니다.
+
[listing]
----
cluster1::> job schedule cron create -name 15_minute_sched -minute 15
----
... SnapMirror 관계에 스케줄을 적용하려면 'napmirror modify' 명령을 사용합니다.
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule 15_minute_sched
----
... 'napmirror show' 명령을 사용하여 데이터 복사 상태를 모니터링합니다.
+
[listing]
----
cluster1::> snapmirror show -destination-path vs1:dst_vol
                            Source Path: system7mode:dataVol20
                       Destination Path: vs1:dst_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: 15_minute_sched
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----


|===


. 증분 전송 일정이 있는 경우 컷오버를 수행할 준비가 되면 다음 단계를 수행합니다.
+
.. 'napmirror quiesce' 명령을 사용하여 향후 업데이트 전송을 모두 비활성화합니다.
+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs1:dst_vol
----
.. 'napmirror modify' 명령을 사용하여 SnapMirror 스케줄을 삭제합니다.
+
[listing]
----
cluster1::> snapmirror modify -destination-path vs1:dst_vol -schedule ""
----
.. 이전에 SnapMirror 전송을 중단한 경우 'napMirror resume' 명령을 사용하여 SnapMirror 전송을 활성화합니다.
+
[listing]
----
cluster1::> snapmirror resume -destination-path vs1:dst_vol
----


. 7-Mode 볼륨과 clustered Data ONTAP 볼륨 간의 전송이 완료될 때까지 기다린 다음 7-Mode 볼륨에서 클라이언트 액세스를 분리하여 컷오버를 시작합니다.
. 'napmirror update' 명령을 사용하여 clustered Data ONTAP 볼륨에 대한 최종 데이터 업데이트를 수행합니다.
+
[listing]
----
cluster1::> snapmirror update -destination-path vs1:dst_vol
Operation is queued: snapmirror update of destination vs1:dst_vol.
----
. 'napmirror show' 명령을 사용하여 마지막 전송이 성공했는지 확인합니다.
. 'napmirror break' 명령을 사용하여 7-Mode 볼륨과 clustered Data ONTAP 볼륨 간의 SnapMirror 관계를 중단하십시오.
+
[listing]
----
cluster1::> snapmirror break -destination-path vs1:dst_vol
[Job 60] Job succeeded: SnapMirror Break Succeeded
----
. 볼륨에 LUN이 구성되어 있는 경우 고급 권한 수준에서 'lun transition 7-mode show' 명령을 사용하여 LUN이 전환되었는지 확인하십시오.
+
또한 clustered Data ONTAP 볼륨에서 'lun show' 명령을 사용하여 성공적으로 전환된 모든 LUN을 볼 수도 있습니다.

. 'napmirror delete' 명령을 사용하여 7-Mode 볼륨과 clustered Data ONTAP 볼륨 간의 SnapMirror 관계를 삭제합니다.
+
[listing]
----
cluster1::> snapmirror delete -destination-path vs1:dst_vol
----
. 'napMirror release' 명령을 사용하여 7-Mode 시스템에서 SnapMirror 관계 정보를 제거합니다.
+
[listing]
----
system7mode> snapmirror release dataVol20 vs1:dst_vol
----


7-Mode 시스템에서 필요한 모든 볼륨이 SVM으로 전환된 경우 7-Mode 시스템과 SVM 간 SVM 피어 관계를 삭제해야 합니다.

* 관련 정보 *

xref:task_resuming_a_failed_snapmirror_transfer_transition.adoc[오류가 발생한 SnapMirror 기본 전송을 재개합니다]

xref:task_recovering_from_a_failed_lun_transition.adoc[장애가 발생한 LUN 전환 복구]

xref:task_configuring_a_tcp_window_size_for_snapmirror_relationships.adoc[SnapMirror 관계에 대한 TCP 윈도우 크기 구성]
