---
permalink: snapmirror/task_transitioning_disaster_recovery_relationship.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, disaster, recovery, relationship, vfiler, units, snapmirror 
summary: '7-Mode 시스템에서 기본 vFiler 유닛과 보조 vFiler 유닛 사이의 DR\(재해 복구) 관계를 소스 SVM과 클러스터 내 타겟 SVM 간의 재해 복구 관계로 전환할 수 있습니다.' 
---
= vFiler 유닛 간 재해 복구 관계 전환
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
7-Mode 시스템에서 기본 vFiler 유닛과 보조 vFiler 유닛 간의 DR(재해 복구) 관계를 소스 SVM과 클러스터 내 타겟 SVM 간의 재해 복구 관계로 전환할 수 있습니다.

전환 프로세스 중에 기본 vFiler 유닛이 소스 SVM으로 전환되고 보조 vFiler 유닛이 대상 SVM으로 전환됩니다.

.단계
. 기본 vFiler 유닛을 소스 SVM으로, 보조 vFiler 유닛을 대상 SVM으로 전환합니다.
. 'vserver stop' 명령을 사용하여 대상 SVM을 중지합니다.
+
볼륨의 이름을 바꾸거나 대상 SVM에 새 볼륨을 추가해서는 안 됩니다.

. 전환된 각 운영 볼륨의 경우 'snapmirror create' 명령을 사용하여 해당 보조 볼륨과 볼륨 레벨 SnapMirror 관계를 생성합니다.
+
[listing]
----
destination_cluster::> snapmirror create -source-path src_vserver:c_vol -destination-path dst_vserver:c_vol -type DP
----
. '스냅샷 재동기화' 명령을 사용하여 전환된 운영 볼륨과 2차 볼륨 간의 볼륨 레벨 SnapMirror 관계를 다시 동기화합니다.
+
재동기화가 성공적으로 수행되려면 운영 볼륨과 2차 볼륨 사이에 공통 스냅샷 복사본이 있어야 합니다.

+
[listing]
----
destination_cluster::> snapmirror resync -destination-path
dst_vserver:c_vol
----
. 재동기화 작업이 완료되고 'napmirror show' 명령을 사용하여 SnapMirror 관계가 '미러됨' 상태인지 확인합니다.
. '-identity-preserve' 옵션이 true로 설정된 상태에서 'napMirror create' 명령을 사용하여 소스와 대상 SVM 간에 SVM 재해 복구 관계를 생성합니다.
+
[listing]
----
destination_cluster::> snapmirror create -source-path src_vserver: -destination-path dst_vserver: -type DP -throttle unlimited -policy DPDefault -schedule hourly -identity-preserve true
----
. 'napmirror resync' 명령을 사용하여 소스 SVM에서 대상 SVM을 재동기화합니다.
+
[listing]
----
destination_cluster::> snapmirror resync dst_vserver:
----
. 재동기화 작업이 완료되고 'napmirror show' 명령을 사용하여 SnapMirror 관계가 '미러됨' 상태인지 확인합니다.
+
[listing]
----
destination_cluster::> snapmirror show
                                                                                    Progress
Source               Destination     Mirror       Relationship  Total               Last
Path           Type  Path            State        Status        Progress   Healthy  Updated
--------       ---- ------------     -------      -------------- --------- ------- --------
src_vserver     DP    dst_vserver    Snapmirrored  Idle           -         true    -
----

