---
permalink: snapmirror/task_transitioning_7_mode_volumes_using_snapmirror.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, volumes, snapmirror, ontap, clustered, data 
summary: Clustered Data ONTAP SnapMirror 명령을 사용하여 NAS 및 SAN 환경에서 7-Mode 볼륨을 clustered Data ONTAP 볼륨으로 전환할 수 있습니다. 그런 다음 전환이 완료된 후에 클러스터에서 프로토콜, 서비스 및 기타 구성을 설정해야 합니다 
---
= SnapMirror를 사용하여 7-Mode 볼륨 전환
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.12.1부터는 SnapMirror 기술을 사용하여 7-Mode 볼륨을 더 이상 전환할 수 없습니다.

하지만 ONTAP 9.11.1 이전 릴리즈의 경우 clustered Data ONTAP SnapMirror 명령을 사용하여 NAS 및 SAN 환경에서 7-Mode 볼륨을 clustered Data ONTAP 볼륨으로 전환할 수 있습니다. 그런 다음 전환이 완료된 후에 클러스터에서 프로토콜, 서비스 및 기타 구성을 설정해야 합니다.

* 권장 사항: * 7-Mode 전환 툴을 사용하면 ONTAP 9.11.1 이전 릴리즈용 7-Mode 볼륨을 7-Mode로 전환할 수 있습니다. 마이그레이션 프로세스에서 모든 단계에서 7-Mode와 클러스터를 모두 확인하는 사전 점검을 제공하므로 잠재적으로 많은 문제를 방지할 수 있습니다. 이 툴은 데이터 마이그레이션과 함께 모든 프로토콜, 네트워크, 서비스 구성의 마이그레이션을 크게 단순화합니다.

http://["7-Mode 전환 툴 릴리즈 노트"]

이 절차에서는 SnapMirror를 사용하여 전환하는 데 필요한 고급 작업을 제공합니다.

[NOTE]
====
ONTAP 9.12.1로 업그레이드하기 전에 다음을 수행해야 합니다.

.단계
. 다음 명령을 실행하여 SnapMirror 대상 볼륨을 쓰기 가능 상태로 만듭니다.
`snapmirror break`
. 다음 명령을 실행하여 모든 TDP SnapMirror 관계를 삭제합니다.
`snapmirror delete`


====
. xref:concept_planning_for_transition.adoc[전환할 볼륨이 전환을 지원하는지 확인합니다].
. xref:task_preparing_7_mode_system_for_transition.adoc[7-Mode 시스템의 전환을 준비합니다].
. xref:task_preparing_cluster_for_transition.adoc[전환을 위해 클러스터를 준비합니다].
. xref:task_creating_a_transition_peering_relationship.adoc[7-Mode 시스템 간에 전환 피어 관계를 소스로, SVM을 대상으로 생성합니다].
. xref:task_transitioning_volumes.adoc[두 볼륨 간에 SnapMirror 관계를 생성하여 7-Mode 볼륨에서 clustered Data ONTAP 볼륨으로 데이터를 복사합니다].


데이터 마이그레이션이 완료된 후 다음 작업을 수행해야 합니다.

* 선택 사항: SVM에 데이터 LIF를 생성하여 클라이언트 액세스를 지원합니다.
+
https://["네트워크 및 LIF 관리"].

* SVM에서 프로토콜, 네트워킹, 서비스를 구성합니다.
+
** https://["네트워크 및 LIF 관리"].
** http://["SMB/CIFS 관리"]
** https://["NFS 관리"]


* Igroup 생성 및 LUN 매핑
+
https://["SAN 관리"]

* LUN으로 볼륨을 전환하는 경우 전환된 clustered Data ONTAP 볼륨에 대한 액세스를 복원하기 전에 호스트에서 필요한 전환 후 작업을 수행해야 합니다.
+
http://["SAN 호스트 전환 및 수정"]



https://["NetApp 지원"]
