---
permalink: snapmirror/task_transitioning_secondary_volume.html 
sidebar: sidebar 
keywords: ontap, 7, mode, transition, snapmirror, volume, secondary 
summary: 2차 볼륨을 전환하려면 SnapMirror 관계 생성, 기본 전송 수행, 증분 업데이트 수행, 7-Mode 운영 볼륨과 clustered Data ONTAP 2차 볼륨 간의 SnapMirror 관계 설정 등이 포함됩니다. 
---
= 보조 볼륨을 전환하는 중입니다
:icons: font
:imagesdir: ../media/


[role="lead"]
2차 볼륨을 전환하려면 SnapMirror 관계 생성, 기본 전송 수행, 증분 업데이트 수행, 7-Mode 운영 볼륨과 clustered Data ONTAP 2차 볼륨 간의 SnapMirror 관계 설정 등이 포함됩니다.

2차 클러스터와 SVM(스토리지 가상 머신)이 이미 설정되어 있어야 합니다.

.단계
. 7-Mode 볼륨에서 clustered Data ONTAP 볼륨으로 데이터 복사:
+
.. TDP로 관계 유형과 함께 'napmirror create' 명령을 사용하여 7-Mode 시스템과 SVM 간에 SnapMirror 관계를 생성합니다.
+
[listing]
----
sec_cluster::> snapmirror create -source-path sec_system:dst_7_vol -destination-path dst_vserver:dst_c_vol -type TDP
Operation succeeded: snapmirror create the relationship with destination dst_vserver:dst_c_vol.
----
.. 기본 전송을 시작하려면 'napmirror initialize' 명령을 사용합니다.
+
[listing]
----
sec_cluster::> snapmirror initialize -destination-path dst_vserver:dst_c_vol
Operation is queued: snapmirror initialize of destination dst_vserver:dst_c_vol.
----
.. Clustered Data ONTAP 볼륨을 수동으로 업데이트할지 또는 SnapMirror 일정을 설정할지 여부에 따라 적절한 작업을 수행합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
전송을 수동으로 업데이트합니다
 a| 
... 'napmirror update' 명령어를 사용한다.
+
[listing]
----
sec_cluster::> snapmirror update -destination-path dst_vserver:dst_c_vol
----
... 'napmirror show' 명령을 사용하여 데이터 복사 상태를 모니터링합니다.
+
[listing]
----
sec_cluster::> snapmirror show -destination-path dst_vserver:dst_c_vol
                            Source Path: sec_system:dst_7_vol
                       Destination Path: dst_vserver:dst_c_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: -
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
           Number of Successful Updates: 1
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----
... 3단계로 이동합니다.




 a| 
예약된 업데이트 전송을 수행합니다
 a| 
... job schedule cron create 명령을 사용하여 업데이트 전송을 위한 스케줄을 생성합니다.
+
[listing]
----
sec_cluster::> job schedule cron create -name 15_minute_sched -minute 15
----
... SnapMirror 관계에 스케줄을 적용하려면 'napmirror modify' 명령을 사용합니다.
+
[listing]
----
sec_cluster::> snapmirror modify -destination-path dst_vserver:dst_c_vol -schedule 15_minute_sched
----
... 'napmirror show' 명령을 사용하여 데이터 복사 상태를 모니터링합니다.
+
[listing]
----
sec_cluster::> snapmirror show -destination-path dst_vserver:dst_c_vol
                            Source Path: sec_system:dst_7_vol
                       Destination Path: dst_vserver:dst_c_vol
                      Relationship Type: TDP
                Relationship Group Type: none
                    SnapMirror Schedule: 15_minute_sched
                 SnapMirror Policy Type: async-mirror
                      SnapMirror Policy: DPDefault
                            Tries Limit: -
                      Throttle (KB/sec): unlimited
                           Mirror State: Snapmirrored
 ...
           Number of Successful Updates: 1
               Number of Failed Updates: 0
           Number of Successful Resyncs: 0
               Number of Failed Resyncs: 0
            Number of Successful Breaks: 0
                Number of Failed Breaks: 0
                   Total Transfer Bytes: 278528
         Total Transfer Time in Seconds: 11
----


|===


. 증분 전송 일정이 있는 경우 컷오버를 수행할 준비가 되면 다음 단계를 수행합니다.
+
.. 'napmirror quiesce' 명령을 사용하여 향후 업데이트 전송을 모두 비활성화합니다.
+
[listing]
----
sec_cluster::> snapmirror quiesce -destination-path dst_vserver:dst_vol
----
.. 'napmirror modify' 명령을 사용하여 SnapMirror 스케줄을 삭제합니다.
+
[listing]
----
sec_cluster::> snapmirror modify -destination-path dst_vserver:dst_vol -schedule ""
----
.. 이전에 SnapMirror 전송을 중단한 경우 'napMirror resume' 명령을 사용하여 SnapMirror 전송을 활성화합니다.
+
[listing]
----
sec_cluster::> snapmirror resume -destination-path dst_vserver:dst_vol
----


. 7-Mode 볼륨과 clustered Data ONTAP 볼륨 간의 전송이 완료될 때까지 기다린 다음 7-Mode 볼륨에서 클라이언트 액세스를 분리하여 컷오버를 시작합니다.
. 'napmirror update' 명령을 사용하여 clustered Data ONTAP 볼륨에 대한 최종 데이터 업데이트를 수행합니다.
+
[listing]
----
sec_cluster::> snapmirror update -destination-path dst_vserver:dst_vol
Operation is queued: snapmirror update of destination dst_vserver:dst_vol.
----
. 'napmirror show' 명령을 사용하여 마지막 전송이 성공했는지 확인합니다.
. 'napMirror break' 명령을 사용하여 7-Mode 2차 볼륨과 clustered Data ONTAP 2차 볼륨 간의 SnapMirror 관계를 중단하십시오.
+
[listing]
----
sec_cluster::> snapmirror break -destination-path dst_vserver:dst_vol
[Job 60] Job succeeded: SnapMirror Break Succeeded
----
. 볼륨에 LUN이 구성되어 있는 경우 고급 권한 수준에서 'lun transition 7-mode show' 명령을 사용하여 LUN이 전환되었는지 확인하십시오.
+
또한 clustered Data ONTAP 볼륨에서 'lun show' 명령을 사용하여 성공적으로 전환된 모든 LUN을 볼 수도 있습니다.

. 'napmirror delete' 명령을 사용하여 7-Mode 2차 볼륨과 clustered Data ONTAP 2차 볼륨 간의 SnapMirror 관계를 삭제합니다.
+
[listing]
----
sec_cluster::> snapmirror delete -destination-path dst_vserver:dst_vol
----
. 'napMirror release' 명령을 사용하여 7-Mode 시스템에서 SnapMirror 관계 정보를 제거합니다.
+
[listing]
----
system7mode> snapmirror release dataVol20 vs1:dst_vol
----
. 7-Mode 운영 볼륨과 clustered Data ONTAP 2차 볼륨 간의 재해 복구 관계 설정:
+
.. 'vserver peer transition create' 명령을 사용하여 7-Mode 운영 볼륨과 clustered Data ONTAP 2차 볼륨 간의 SVM 피어 관계를 생성합니다.
+
[listing]
----
sec_cluster::> vserver peer transition create -local-vserver dst_vserver -src-filer-name src_system
Transition peering created
----
.. 'job schedule cron create' 명령을 사용하여 7-Mode SnapMirror 관계에 구성된 일정과 일치하는 작업 일정을 생성합니다.
+
[listing]
----
sec_cluster::> job schedule cron create -name 15_minute_sched -minute 15
----
.. 'napMirror create' 명령을 사용하여 7-Mode 운영 볼륨과 clustered Data ONTAP 2차 볼륨 간의 SnapMirror 관계를 생성합니다.
+
[listing]
----
sec_cluster::> snapmirror create -source-path src_system:src_7_vol -destination-path dst_vserver:dst_c_vol -type TDP -schedule 15_minute_sched
Operation succeeded: snapmirror create the relationship with destination dst_vserver:dst_c_vol.
----
.. 'napmirror resync' 명령을 사용하여 clustered Data ONTAP 보조 볼륨을 재동기화합니다.
+
재동기화가 성공적으로 수행되려면 7-Mode 운영 볼륨과 clustered Data ONTAP 2차 볼륨 사이에 공통 7-Mode 스냅샷 복사본이 있어야 합니다.

+
[listing]
----
sec_cluster::> snapmirror  resync -destination-path dst_vserver:dst_c_vol
----
+
*** 타겟 클러스터에서 Data ONTAP 8.3.2 이상이 실행 중인 경우 필요한 igroup을 생성하고 LUN을 수동으로 매핑해야 합니다.
*** 타겟 클러스터에서 Data ONTAP 8.3.1 이하가 실행 중인 경우 운영 볼륨의 스토리지 컷오버를 완료한 후 보조 LUN을 수동으로 매핑해야 합니다.
*** 7-Mode 시스템에서 필요한 모든 볼륨이 SVM으로 전환된 경우 2차 7-Mode 시스템과 2차 SVM 간에 SVM 피어 관계를 삭제해야 합니다.
*** 7-Mode 운영 시스템과 7-Mode 2차 시스템 간의 SnapMirror 관계를 삭제해야 합니다.






* 관련 정보 *

xref:task_recovering_from_a_failed_lun_transition.adoc[장애가 발생한 LUN 전환 복구]

xref:task_configuring_a_tcp_window_size_for_snapmirror_relationships.adoc[SnapMirror 관계에 대한 TCP 윈도우 크기 구성]
